### ISSUE TITLE
STC meeting agenda item - dapr.io update

### ISSUE THREAD

**Issue by orizohar** [dapr/community#103]
This is a suggestion for an agenda item for the next STC meeting:

The Dapr main website dapr.io is due for a refresh. I suggest discussing a proposed website update with added context of the rational behind the suggested changes, feedback on the current website and tweaks to the Dapr messaging which are based on feedback from stakeholders and the Dapr community

**Comment by msfussell** [comment]
This item was address in the https://github.com/dapr/community/issues/100 meeting
