### ISSUE TITLE
REQUEST: Approver status for @willtsai in dapr/docs

### ISSUE THREAD

**Issue by willtsai** [dapr/community#108]
### GitHub Username

@willtsai 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/docs/pull/1736
https://github.com/dapr/docs/pull/1767
https://github.com/dapr/docs/pull/1775
https://github.com/dapr/docs/pull/1776
https://github.com/dapr/docs/pull/1806
https://github.com/dapr/docs/pull/1892
https://github.com/dapr/docs/pull/1904
https://github.com/dapr/docs/pull/1910
https://github.com/dapr/docs/pull/1914
https://github.com/dapr/docs/pull/1799
https://github.com/dapr/docs/pull/1856
 
- Issues responded to
https://github.com/dapr/docs/issues/1879
https://github.com/dapr/docs/issues/1644
https://github.com/dapr/docs/issues/1633
https://github.com/dapr/docs/issues/760
https://github.com/dapr/docs/issues/179
https://github.com/dapr/docs/issues/806
https://github.com/dapr/docs/issues/1215
https://github.com/dapr/docs/issues/1764
https://github.com/dapr/docs/issues/1805
https://github.com/dapr/docs/issues/1903

**Comment by willtsai** [comment]
Flagging maintainers for this request: @msfussell @orizohar @greenie-msft

**Comment by greenie-msft** [comment]
I vote yes to approve @willtsai as a docs repository approver.

**Comment by yaron2** [comment]
> I vote yes to approve @willtsai as a docs repository approver.

We don't vote yes/no on approvers, just need 2 maintainers to support their request. But, noted :)

**Comment by orizohar** [comment]
Supporting :+1:

**Comment by msfussell** [comment]
Will was supported by 2 maintainers. Approved.
