### ISSUE TITLE
PROPOSAL: run community calls monthly

### ISSUE THREAD

**Issue by artursouza** [dapr/community#112]
The community calls do not seem to have a lot of updates since Dapr releases are focusing more on fundamentals and overall stability. I think we should move to a monthly cadence for the following reasons:

* Accumulate more content to be presented - with releasing Dapr every 2 months, it is unlikely for us to have content every 2 weeks.
* Include community presenters - have time to engage with contributors and prepare presentation, otherwise we will always be limited to maintainers' content.

In addition, I would also remove the alternate timezone call. Translating the regular community call to another language might be a better investment (IMO).

Thoughts?

**Comment by willtsai** [comment]
+1 on running community calls on a monthly basis

**Comment by dmitsh** [comment]
Agree, having monthly meetings will give us more time to gather enough material.

**Comment by msfussell** [comment]
I disagree. This is about giving people in the community a chance to ask questions as well as organizing content and even providing news updates. I believe there is plenty of content, it is just a matter of asking the community what their interests are and ensuring that we find more presenters in advance. Better to have shorter (even 40 mins) more regular than once a month which is too infrequent IMO. Also the Asia time zone for the last few month did not help with attendance/presenters.

**Comment by yaron2** [comment]
I also disagree. More calls means more content and more engagement with the broader community. This should be tackled with better planning in advance rather than reducing content and community engagement.

As for the Asia timezone meetings, we should do well to remember that the community calls are advertised through Twitter and Discord, both of which are not enabled in China. My recommendation here would be, again, to try and assess *where* the call is advertised (for example, there's a Dapr SIG in China, cc @abserari) before removing it completely.

**Comment by dmitsh** [comment]
Speaking form my own experience and observations, relatively often meetings create "attendance fatigue". For example, Prometheus with thousands of active users and dozens of participating companies has one monthly community meeting call. Even more, they alternate the time of the meetings every other month to accommodate different timezones.

**Comment by artursouza** [comment]
I second Dmitry's point on "attendance fatigue". When Dapr was still in pre stable versions, there were so many changes in such small amount of time that the community call made sense. It also helped grow the community. At this point, our priority is more in fundamentals and less in adding as many features as possible.

Also, if one of the goals is to have community calls to ask questions, we can have office hours too - those require less preparation and no recording needed.

I would rather focus on quality over quantity for our community calls. We can change that back to the current frequency later when we get into another big wave of new features.

**Comment by yaron2** [comment]
> Speaking form my own experience and observations, a frequent meeting cadence creates "attendance fatigue". For example, Prometheus with thousands of active users and dozens of participating companies has one monthly community meeting call. Even more, they alternate the time of the meetings every other month to accommodate different timezones.

Prometheus is not a good example. It differs from Dapr's state. The project is much more mature, first released in 2012, and is changing at a much slower pace than Dapr. I can list out here at least half a dozen examples of projects that meet bi-monthly that change slower than Dapr, but I do not believe that's the correct point of reference anyway.

> our priority is more on fundamentals and less in adding as many features as possible.

I don't understand who is "our" here? from a project perspective, and also STC perspective, features and code assignments are one aspect of the project, and maintaining a healthy community is another. Both are important, and the two aren't correlated. Community calls are not about the introduction of new features. It's about presenting broad content that ranges from new features to existing features to discussions about design issues, getting user feedback, making place for announcements and conducting FAQs where everyone can (literally) express their voice.
Furthermore, with Dapr now in CNCF, community calls are a great way to welcome CNCF ecosystem developers who are very much accustomed to community calls run by other projects. So timing wise, this isn't great either.

**Comment by abserari** [comment]
> I also disagree. More calls means more content and more engagement with the broader community. This should be tackled with better planning in advance rather than reducing content and community engagement.
> 
> As for the Asia timezone meetings, we should do well to remember that the community calls are advertised through Twitter and Discord, both of which are not enabled in China. My recommendation here would be, again, to try and assess _where_ the call is advertised (for example, there's a Dapr SIG in China, cc @abserari) before removing it completely.

I just provided the info of  Dapr SIG, we now have local meetings twice a month, previously, once a week, and as I know, many participants have lower knowledge about Dapr Community Call. Even I look up discord or Twitter occasionally, which I don't know about IMO. 

Otherwise, I think the more frequency to have meetings engage people to learn more, and agree that shorter meetings make participants comfortable. We transform from once a week to twice a month because I don't have time to organize, but if permitted, we would recover to once a week. Also later, I'll recommend the people in Dapr SIG in China to join the official meetings.

**Comment by daixiang0** [comment]
From my experience, community call is the best place for developers to join a project and share their ideas, not like discord or github, call is real-time, and all partners listen. The one-month interval is too long for me.

I agree with "attendance fatigue", focus on fundamentals leads to less topic on the call. In fact, we do not need to think about which topic we need to share, the call **provides a chance for every developer to talk about what they are concerned about**, even no topics, open discussion still makes sense. 

For "attendance fatigue", **taking turns to host** may help.

I have got in touch with some developers from Japan and Korea，a call for Asia time is friendly for them and can publicize Dapr in them better.

**Comment by resouer** [comment]
@artursouza @yaron2 My 2c: it worth to consider promoting Dapr SIG in China's community meetings into one of the official Dapr Community Calls, which should solve a lot problems. Dapr maintainers can then set up a channel to collaborate with local hosts, resolve issues/feedbacks, and show up per needs. Similar approach can also apply to other Asia regions if it works.

For community call, IMO bi-weekly community meeting is good even with the project is moving to stable channel. It's the main stage for community members to collaborate, discuss and show off things. I'd suggest the meeting host taken by maintainers & steering committee members in turn (it's also the practice for most CNCF project/TAG meetings). The meeting content definitely doesn't have to stick to feature walk through, even the stability/observability discussion or PR review is great. Some other examples in CNCF: [Flux meeting notes](https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/edit), [ArgoCD meeting notes](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8/edit).

**Comment by artursouza** [comment]
If we change the format of the community call to be less about presentation and more about an open forum, then it makes sense to keep the bi-weekly cadence. On top of supporting the repositories and work on deliverables, we are finding hard to come up with high quality content every 2 weeks. We are not shipping new features like we used to, this allows Dapr to become more stable and make what we have better.

We also have added a evening time to be friendly to Asia, so it would be good to see some presenters from different groups too.

**Comment by daixiang0** [comment]
> If we change the format of the community call to be less about presentation and more about an open forum, then it makes sense to keep the bi-weekly cadence. On top of supporting the repositories and work on deliverables, we are finding hard to come up with high quality content every 2 weeks. We are not shipping new features like we used to, this allows Dapr to become more stable and make what we have better.
Agree, we need an open forum.

**Comment by msfussell** [comment]
Conclusion is to keep this every 2 weeks and have more community presenter. @msfussell and @greenie-msft  will share hosting the calls
