### ISSUE TITLE
December 14th, 2021, Community Meeting Agenda

### ISSUE THREAD

**Issue by greenie-msft** [dapr/community#113]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on December 14th, 2021, at 10:00am PST. The meeting agenda will be finalized by a Community Call Host 3 days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by yaron2** [comment]
@TenSt will cover Dapr and Knative.

**Comment by greenie-msft** [comment]
> @TenSt will cover Dapr and Knative.

@TenSt, still interested/available to present this subject during the community call tomorrow (14th) at 10am PST?

**Comment by greenie-msft** [comment]
@Abhilash-Chandran will demo the new dart-sdk!

**Comment by TenSt** [comment]
@greenie-msft yes, all is ready from my side.

**Comment by msfussell** [comment]
Closing.
