### ISSUE TITLE
REQUEST: New approver status for @Taction dapr/components-contrib

### ISSUE THREAD

**Issue by Taction** [dapr/community#117]
### GitHub Username
@Taction

Nominations by existing maintainers:
@yaron2 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
dapr/components-contrib#763
dapr/components-contrib#769
dapr/components-contrib#804
dapr/components-contrib#823
dapr/components-contrib#832
dapr/components-contrib#835
dapr/components-contrib#868
dapr/components-contrib#859
dapr/components-contrib#860
dapr/components-contrib#862
dapr/components-contrib#883
dapr/components-contrib#909
dapr/components-contrib#924
dapr/components-contrib#1136
dapr/components-contrib#1177
dapr/components-contrib#1196
dapr/components-contrib#1222
dapr/components-contrib#1283

- Issues responded to
dapr/components-contrib#784
dapr/components-contrib#833
dapr/components-contrib#840
dapr/components-contrib#841
dapr/components-contrib#857
dapr/components-contrib#867
dapr/components-contrib#908
dapr/components-contrib#946
dapr/components-contrib#966
dapr/components-contrib#1135
dapr/components-contrib#1172
dapr/components-contrib#1220

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
@Taction, you have been added to the `dapr/components-contrib` approvers group. Look out for a GitHub invite.
