### ISSUE TITLE
REQUEST: New approver status for @Taction dapr/dapr

### ISSUE THREAD

**Issue by Taction** [dapr/community#118]
### GitHub Username
@Taction

Nominations by existing maintainers:
@yaron2 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
dapr/dapr#3941
dapr/dapr#3951
dapr/dapr#3993
dapr/dapr#4020
dapr/dapr#3989
dapr/dapr#3954
dapr/dapr#3657
dapr/dapr#3781
dapr/dapr#3346
dapr/dapr#3832
dapr/dapr#3901

- Issues responded to
dapr/dapr#4008
dapr/dapr#3983
dapr/dapr#3969
dapr/dapr#4012
dapr/dapr#3948
dapr/dapr#3081
dapr/dapr#3216
dapr/dapr#3288
dapr/dapr#3701
dapr/dapr#3704
dapr/dapr#3715
dapr/dapr#3759
dapr/dapr#3766

**Comment by artursouza** [comment]
I would like to observe more impactful PRs and more activity in responding to issues. I am happy to reassess in 1 month.

**Comment by Taction** [comment]
@artursouza Updated, can you kindly have a review for this?

**Comment by artursouza** [comment]
I approve this request.

**Comment by artursouza** [comment]
Please, remember that approver cannot merge PRs even if GH shows the merge button.

**Comment by yaron2** [comment]
@Taction, you have been added to the `dapr/dapr` approvers group. Look out for a GitHub invite.
