### ISSUE TITLE
February 8th 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#123]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on February 8th , 2022, at 10:00am PST. The meeting agenda will be finalized by a Community Call Host 3 days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by jjcollinge** [comment]
If there is space in the agenda at the end, I would like to get some feedback to walk through a set of proposals to improve Dapr middleware.
- Adding support for gRPC middleware: https://github.com/dapr/dapr/issues/4153
- Using CEL for middleware selectors: middleware https://github.com/dapr/dapr/issues/4167
- Using Dapr components in middleware (to support use cases like caching): https://github.com/dapr/dapr/issues/2950

**Comment by greenie-msft** [comment]
Absolutely, @jjcollinge. Adding this topic to the agenda. How much time should we allocate, 15-20 mins?

**Comment by yaron2** [comment]
@msfussell @greenie-msft isn't Feb 8th the asian-friendly timezone call?

**Comment by jjcollinge** [comment]
> Absolutely, @jjcollinge. Adding this topic to the agenda. How much time should we allocate, 15-20 mins?

It'll only take me 5-10 mins to walk through the proposals. Then it depends on how much engagement/feedback we get.

**Comment by jjcollinge** [comment]
@greenie-msft I just had a little run through the content I plan to talk about and actually I'm probably closer to 15/20 mins if I don't rush through it.

**Comment by patrickhuber** [comment]
I may be too late for this meeting, but I made progress on integrating plugins into daprd https://github.com/dapr/dapr/issues/3787#issuecomment-1030957998

**Comment by yaron2** [comment]
I believe we can squeeze that in. @greenie-msft does this close the agenda?

**Comment by greenie-msft** [comment]
@patrickhuber, yes there is room! How much time would you like for this topic?

**Comment by yaron2** [comment]
@patrickhuber you're on for tomorrow! Thanks

**Comment by greenie-msft** [comment]
@patrickhuber, @jjcollinge do either of you have slides that you plan on presenting? If so, please send me a message on discord (nickgreenfield#4810) and I can send you a link to the deck.  Also, please try to connect to the community meeting 10 minutes early for a quick tech check. 

See you then! Thanks!

**Comment by jjcollinge** [comment]
@greenie-msft I don't have any slides, I will just be sharing my screen if that's ok? Joining 10 mins early is no problem👌

**Comment by greenie-msft** [comment]
@jjcollinge Yup, that's perfect.

**Comment by patrickhuber** [comment]
I don't have any slides. I will be doing a demo.

**Comment by daixiang0** [comment]
> If there is space in the agenda at the end, I would like to get some feedback to walk through a set of proposals to improve Dapr middleware.
> 
> * [Adding support for gRPC middleware](https://github.com/dapr/dapr/issues/4153)
> * [Using CEL for middleware selectors](https://github.com/dapr/dapr/issues/4167)
> * [Using Dapr components in middleware (to support use cases like caching)](https://github.com/dapr/dapr/issues/2950)
> 
> If @daixiang0 has any further thoughts on [WASM integration](https://github.com/dapr/components-contrib/issues/1171#issuecomment-1024862285) then this could follow on.

Sorry for slow response, I would like to share it in next community.

**Comment by jjcollinge** [comment]
@greenie-msft is there time for @mstrYoda to demo his work on a HTTP cache middleware after me?

**Comment by mmisztal1980** [comment]
is there a chance to squeeze the "resiliency block" in?

**Comment by yaron2** [comment]
> is there a chance to squeeze the "resiliency block" in?

Next call 🤙

**Comment by msfussell** [comment]
Passed
