### ISSUE TITLE
REQUEST: New membership for @yaron2

### ISSUE THREAD

**Issue by ls-2018** [dapr/community#128]
### GitHub Username

ls-2018

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
- https://github.com/dapr/dapr/pull/4075
- https://github.com/dapr/dapr/pull/4072
- https://github.com/dapr/dapr/pull/4084
- https://github.com/dapr/dapr/pull/4085
- Issues responded to
- https://github.com/dapr/dapr/issues/4054
- https://github.com/dapr/dapr/issues/4052 
- https://github.com/dapr/dapr/issues/4083

 
 
Thanks

**Comment by yaron2** [comment]
Approved. @ls-2018 look for a GitHub invite in your mailbox.
