### ISSUE TITLE
[PROPOSAL] Community call organization

### ISSUE THREAD

**Issue by artursouza** [dapr/community#130]
We need a rotation to define the organizer of the community calls. Nick has been organizing those every 2 weeks but I believe the duty should be shared. In addition, we need to agree on a storage for the presentation files so presenters have an opportunity to edit it independently from which company they work.

**Comment by greenie-msft** [comment]
For now, @msfussell and I will alternate hosting responsibilities monthly. 

@msfussell will take the calls in January and I will take February and so on and so on.

**Comment by msfussell** [comment]
Agreed on the proposal above. The presentation are now stored on Google drive that is accessible be all the presenters.
