### ISSUE TITLE
REQUEST: New membership for amulyavarote

### ISSUE THREAD

**Issue by amulyavarote** [dapr/community#132]
### GitHub Username

amulyavarote

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored

Python SDK:
https://github.com/dapr/python-sdk/pull/323
https://github.com/dapr/python-sdk/pull/313
https://github.com/dapr/python-sdk/pull/312

Dapr CLI:
https://github.com/dapr/cli/pull/847
https://github.com/dapr/cli/pull/822

Dapr Docs:
https://github.com/dapr/docs/pull/2026
https://github.com/dapr/docs/pull/2021
https://github.com/dapr/docs/pull/2018
https://github.com/dapr/docs/pull/2017
https://github.com/dapr/docs/pull/2000
https://github.com/dapr/docs/pull/1965

- Issues responded to
https://github.com/dapr/python-sdk/issues/308
https://github.com/dapr/python-sdk/issues/311
https://github.com/dapr/cli/issues/832
https://github.com/dapr/docs/issues/1969

**Comment by artursouza** [comment]
@amulyavarote Please, add links to PRs and issues you contributed to.

**Comment by amulyavarote** [comment]
> @amulyavarote Please, add links to PRs and issues you contributed to.

**Comment by yaron2** [comment]
This cuts it for membership :) @amulyavarote check your email for a GH invite.

**Comment by amulyavarote** [comment]
Thanks @yaron2
