### ISSUE TITLE
[Proposal] Rename Quickstarts repo to Tutorials and create a new Quickstarts repo with simplified examples

### ISSUE THREAD

**Issue by greenie-msft** [dapr/community#135]
Work has been done to create simplified/runnable examples for each building block API for a given SDK. Currently, the source code for these examples lives in a contributor's personal GH account. 

This proposal is to rename our current quickstarts repo to tutorials (since some of the examples are more representative of real world application/scenarios, which include usage of more than one building block per example). 

IMO, Quickstarts should be a 5-minutes to "wow" experience and showing a singular value prop. I suggest we create a new "Quickstarts" repo and port over the source code from [here](https://github.com/amulyavarote/dapr-quickstarts-examples), which are simplified examples on how to use each building block with a given SDK.

**Comment by msfussell** [comment]
This proposal was accepted and approved by the Dapr STC. See https://github.com/dapr/community/issues/120

**Comment by msfussell** [comment]
This has now been implemented, but done slightly differently. Instead the existing quickstart repo was kept and the existing ones named as tutorials. This made the transition much simpler to understand without having to create a new repo.
