### ISSUE TITLE
16th February 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#136]
Placeholder for the February 2022 STC meeting.
Issues to discuss will be taken from the STC backlog project https://github.com/orgs/dapr/projects/54

Proposed Agenda (will update based on email feedback and community raised issues)
- Create SIG for SDK spec and maturity process - @artursouza
- Review [Proposal] Database API design #3354 - @paulyuk 
- Review proposal https://github.com/dapr/dapr/issues/4228 - @yaron2 
- Create SIG for preview feature maturity process - @artursouza
- Future topics?

**Comment by berndverst** [comment]
Re preview feature maturity - please consider this proposal https://github.com/dapr/dapr/issues/4228

Not sure whether a SIG is needed if that process is implemented instead.

**Comment by berndverst** [comment]
I would also like to propose the STC discuss the following proposal for performance requirements for adding new components to Dapr. https://github.com/dapr/dapr/issues/4234

**Comment by yaron2** [comment]
> I would also like to propose the STC discuss the following proposal for performance requirements for adding new components to Dapr. [dapr/dapr#4234](https://github.com/dapr/dapr/issues/4234)

Added to the agenda, I'll drive the discussion for this. Thanks!

**Comment by berndverst** [comment]
Another quick process to bring up @yaron2:

Formal removal "process" for components:
https://github.com/dapr/dapr/issues/4244

Specifically we may want to begin following that process to suggest removal of the Postmark component.

**Comment by msfussell** [comment]
Attendees:
@msfussell 
@yaron2 
@artursouza 
@beiwei30
@cvictory
@Forrest-zhao

Absent:
@paulyuk 

Notes from 16/02/2022:

Agenda:
- Create SIG for SDK spec and maturity process - @artursouza
	- @artursouza  presented a case for an SDK SIG to address conformance and consistency across the Dapr SDKs. For example some SDKs such as Java implement a pluggable serializer for on the wire serialization and others, such as Javascript, do not. Other example include naming conventions, and when should an SDK moves a stable version.
	- @beiwei30 - Asked how can we guarantee the implementation of the SDK conforms to the spec? There should be a compatibility Tests for SDKs, It was agreed that this should be include in the discussion
	- **Recommendation and action**:  The STC voted and agreed to create a SIG for the SDK specification. @artursouza to raise an issue in the community repo to describe the purpose of the SDK SIG, to create a SIG-SDK-SPEC repo https://github.com/dapr/sig-sdk-spec and to create a Discord channel for discussions (https://discordapp.com/channels/778680217417809931/94628522548122424)
	        - @artursouza to find members who will contribute. @msfussell voluteered to be the first member.

- Review proposal https://github.com/dapr/dapr/issues/4228 - @yaron2 
	- Yaron reviewed the proposed criteria for [Proposal] Criteria for Preview Feature & Experimental/Alpha API stable designation dapr#4228 
	- Points were made about the consistency of the proposed criteria and following changes suggested were agreed by the STC to be updated and then included into the doc
		○ Do not make it a requirement for SDKs to implement a runtime feature
		○ Do not require a community sponsor
		○ Make the criteria that after 4 releases a preview feature must be prioritized for the next release by the maintainer
    - **Recommendation and action**:  @Artur to update the proposal to reflect the changes discussed. See updates here https://github.com/dapr/dapr/issues/4228#issuecomment-1046535951

- Create SIG for preview feature maturity process - @artursouza
The STC talk about updating the feature maturity process and it was agreed that this can be updated into the existing guidance documentation. This includes how the release team operates which is captured in this issue. https://github.com/dapr/community/issues/45 
      - This issue needs further STC follow up.

**Comment by msfussell** [comment]
Closing this issue after time to review notes.
