### ISSUE TITLE
February 22nd 2022, Community Meeting Agenda 

### ISSUE THREAD

**Issue by msfussell** [dapr/community#139]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on February 22nd , 2022, at 7:30pm PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by berndverst** [comment]
Towards the end of this call (and all future calls) we would like the standing agenda to include a section titled **Call for Feedback** where we can list the current proposals (technical and otherwise) awaiting feedback from the community.

This isn't intended to go into detail on those proposals, but rather to have a reminder about open / pending proposals and to nudge the community.

**Comment by msfussell** [comment]
> Towards the end of this call (and all future calls) we would like the standing agenda to include a section titled **Call for Feedback** where we can list the current proposals (technical and otherwise) awaiting feedback from the community.
> 
> This isn't intended to go into detail on those proposals, but rather to have a reminder about open / pending proposals and to nudge the community.

This is a great idea. Having a regular list of places where people can contribute and know what proposal are being made would enables the community to be more involved.

**Comment by greenie-msft** [comment]
Yilin Zeng will use 15-20 minutes to present "How to use Dapr with Apache APISIX Ingress Controller".

**Comment by msfussell** [comment]
Delivered and recorded.
