### ISSUE TITLE
REQUEST: New membership for @pravinpushkar

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/community#140]
### GitHub Username

pravinpushkar

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

#### PRs reviewed / authored
- https://github.com/dapr/java-sdk/pull/676
- https://github.com/dapr/java-sdk/pull/673
- https://github.com/dapr/java-sdk/pull/670
- https://github.com/dapr/docs/pull/2161
- https://github.com/dapr/cli/pull/888
- https://github.com/dapr/dapr/pull/4211

#### Issues responded to
- https://github.com/dapr/cli/issues/869
- https://github.com/dapr/docs/issues/2138
- https://github.com/dapr/components-contrib/issues/1458
- https://github.com/dapr/java-sdk/issues/659
- https://github.com/dapr/java-sdk/issues/671

**Comment by artursouza** [comment]
Approved. Invite sent. Thanks.
