### ISSUE TITLE
REQUEST: Approver status for halspang in dapr/test-infra

### ISSUE THREAD

**Issue by halspang** [dapr/community#141]
### GitHub Username

halspang

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### PRs reviewed / authored
- https://github.com/dapr/test-infra/pull/127
- https://github.com/dapr/test-infra/pull/112
- https://github.com/dapr/test-infra/pull/109
- https://github.com/dapr/test-infra/pull/108
- https://github.com/dapr/test-infra/pull/107
- https://github.com/dapr/test-infra/pull/106
- https://github.com/dapr/test-infra/pull/104
- https://github.com/dapr/test-infra/pull/123

### Issues responded to
- https://github.com/dapr/test-infra/issues/111

Worked with @tanvigour and @wcs1only directly on several things and have also taken over investigating the longhauls during the release process. 

Sponser: @artursouza

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
Approved.

**Comment by msfussell** [comment]
Approved

**Comment by msfussell** [comment]
The required number of supporting votes was met.  Added correct approvers and maintainers to infra repo as a result. See https://github.com/dapr/test-infra/settings/access
