### ISSUE TITLE
March 8th 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#142]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on March 8th, 2022, at 10:00am PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by riezebosch** [comment]
CloudEvents: interoperable pub/sub with Dapr, MassTransit, and Rebus.

I've crafted an adapter for both MassTransit and Rebus for them to produce and consume cloud events. I'm using Dapr from an integration test both as the driver and the stub to proof interoperability. On top of that I've created a tiny library in order to do asynchronous assertions and one to manage the self-hosted sidecar.

**Comment by msfussell** [comment]
@riezebosch - Sounds interesting and certainly interested in having an overview and demo. Looks like there are two different topics here that you could cover. Is that correct. If so, could you explain the second one (the library) some more on what is covers?

In both cases writing title with a 2-3 sentence abstract and posting it here would be very helpful. For example
Title: Using Dapr and Cloud Events to integrate between MassTransit and Rebus
Abstract: In this demo I will show...

**Comment by msfussell** [comment]
@riezebosch - Following up here. Are you interested in presenting a week today, on March 8th?

**Comment by riezebosch** [comment]
I'd be honored.

**Comment by msfussell** [comment]
@riezebosch - I reached out to you on email via you github address. Or please follow up with me @ mark@diagrid.io

**Comment by msfussell** [comment]
Delivered
