### ISSUE TITLE
March 22nd 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#143]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on March 22nd, 2022, at 7:30pm PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by qqharryhwang** [comment]
Hi Mark, if time permits, we'd like to have 10-15 mins to discuss issue #4065 on multi name resolution. Thanks.

**Comment by benjaminhuo** [comment]
@msfussell @yaron2, [OpenFunction](https://github.com/OpenFunction/OpenFunction) uses Dapr and Keda as its async function runtime. As the maintainer of OpenFunction @tpiperatgod @wanjunlei @FeynmanZhou, we'd like to share with the Dapr community the following items within 15~20 mins :
- Brief Intro to OpenFunction
- The important role Dapr plays in OpenFunction
- OpenFunction Async Function Demo.

**Comment by msfussell** [comment]
@benjaminhuo - Would love to host you on this call. Please can you provide a title for the talk. 
Please drop me an email @mark@diagrid.io so that I can give you access to this deck to add your slides for the call https://docs.google.com/presentation/d/1wqFUkaSlsIXej4x0W5cUN7U8KrFVmLtx8kSqnaxXRig/edit?usp=sharing
I suggest that you take at least 20 mins to cover this.

**Comment by benjaminhuo** [comment]
@msfussell Sure, will do. Thanks for the invitation!

**Comment by msfussell** [comment]
Delivered and recorded.
