### ISSUE TITLE
REQUEST: Approver status for @paulyuk in dapr/quickstarts

### ISSUE THREAD

**Issue by paulyuk** [dapr/community#144]
### GitHub Username

paulyuk

sponsor: @msfussell 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
[authored]
https://github.com/amulyavarote/dapr-quickstarts-examples/pull/7 (reboot of pub/sub, contributed spec)
https://github.com/amulyavarote/dapr-quickstarts-examples/pull/9 (reboot of HTTP)
https://github.com/dapr/quickstarts/pull/526 (co-authored)
https://github.com/dapr/quickstarts/pull/519
https://github.com/dapr/quickstarts/pull/513
https://github.com/dapr/quickstarts/pull/478
https://github.com/dapr/quickstarts/pull/529

[reviewed]
https://github.com/dapr/quickstarts/pull/527#pullrequestreview-881035380
https://github.com/amulyavarote/dapr-quickstarts-examples/pull/10
https://github.com/dapr/quickstarts/pull/528
https://github.com/dapr/quickstarts/pull/521
https://github.com/dapr/quickstarts/pull/523
https://github.com/dapr/quickstarts/pull/515

- Issues responded to
https://github.com/dapr/quickstarts/issues/518
https://github.com/dapr/quickstarts/issues/516
https://github.com/dapr/quickstarts/issues/512
https://github.com/dapr/quickstarts/issues/503
https://github.com/dapr/quickstarts/issues/501
https://github.com/dapr/quickstarts/issues/499
https://github.com/dapr/quickstarts/issues/477

**Comment by msfussell** [comment]
+1

**Comment by greenie-msft** [comment]
+1

**Comment by msfussell** [comment]
+1.
