### ISSUE TITLE
17th March 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#148]
March 2022 STC meeting.
Issues to discuss will be taken from the STC backlog project https://github.com/orgs/dapr/projects/54

Proposed Agenda (will update based on email feedback and community raised issues)

- Review [Proposal] Database API design #3354 - @paulyuk (carried over from Feb 2022)
- Customer perspective  - PaulYuk
- "Dapr Labs" org - Artur
- Release Priorities and Themes - Artur

**Comment by artursouza** [comment]
I would like to bring the proposal about "Dapr Labs" org.

**Comment by paulyuk** [comment]
Hi,

I would really love to have the discussion around Database API per above, but was hoping @cvictory could present it as the creator.  Are we on the same page?  

+1 to Dapr Labs.

We might have a proposal around workflow ready for initial discussion, we will let you know.

Last, I'm happy to summarize a few generalized customer themes we're hearing this month that may inform future planning.  Perhaps you have some too?

**Comment by duglin** [comment]
Are there big ticket items (themes) for the next release? Often I've seen OSS projects define what their high-level goals are for the next release due to a common concern or desire. Some common examples I've seen: we need to stabilize xxx for the next release.  We need to re-vamp our docs.  

Often, just getting agreement across the leaders is enough to provide the right level of focus to result in people opening issues and PRs to align with those goals. But, of course, if there are agreed-to goals, getting people to volunteer to drive those activities would be critical to making it happen.

So, again, are there themes we'd like to achieve for the next release? If so, can we get those written down in an issue/milestone, and a volunteer to drive each one? 

If this has already happened, sorry, please point me to where I can find the info.

**Comment by paulyuk** [comment]
Thank you @duglin.  This is a good one for us to raise today.

Update: we are not quite ready to review workflow proposal today.  We would like to bring it to the next meeting if possible.

**Comment by artursouza** [comment]
> Are there big ticket items (themes) for the next release? Often I've seen OSS projects define what their high-level goals are for the next release due to a common concern or desire. Some common examples I've seen: we need to stabilize xxx for the next release. We need to re-vamp our docs.
> 
> Often, just getting agreement across the leaders is enough to provide the right level of focus to result in people opening issues and PRs to align with those goals. But, of course, if there are agreed-to goals, getting people to volunteer to drive those activities would be critical to making it happen.
> 
> Are there themes we'd like to achieve for the next release? If so, can we get those written down in an issue/milestone, and a volunteer to drive each one?
> 
> One possible items I've heard come up a few times is the concern around how many of the components are not in a "stable" phase/state. For example: https://docs.dapr.io/reference/components-reference/supported-state-stores/ might leave people with the impression that Dapr itself isn't as mature as it should be. Should there be a group-wide agreement/effort to get more into "stable" state?
> 
> If this has already happened, sorry, please point me to where I can find the info.

We have used themes before. I tried to bring it back as "priorities" to the 1.7 milestone but did not have consensus. I will bring it up again in this meeting.

**Comment by msfussell** [comment]
Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@Forrest-zhao
@paulyuk

Notes from 17/03/2022:

# Agenda:

## Review [Proposal] Database API design #3354
@paulyuk asked for more details on this issue to understand the desired direction. 
@cvictory explain that this was to allow developers to call an API to get the database connection of their choice. However the scenarios for this were not so clear and @cvictory agreed to add more details on the scenarios to the issue

## Customer perspective
@paulyuk gave a perspective of what customer Microsoft is seeing with their engagements particularly the growth of Dapr running on AKS. There are a diverse set of customers. What has been resonating with customers is Dapr providing a microservices programming model for pub/sub and service invocation.

## Dapr "incubation project" organization 
@artursouza Proposed create a new organization where new project could be started before they became part of the Dapr org. @msfussell suggested calling this "Dapr incubation" and this approach can be modelled on the CNCF process. 

The STC would vote to:
1) Accept new project into Dapr Incubation 
2) Move any project from Dapr Incubation to Dapr Org when it graduated. 
3) Move project back from Dapr Org to Dapr Incubation if they are not being worked on by maintainers. 
4) If a project is entirely abandoned in Dapr Incubation, then it may be deleted.  

There are two projects in Dapr Org 1) Workflows and 2) Azure Functions Extension that are proposed to move from Dapr Org to Dapr incubations

**Decision: The STC unanimously voted to create this new Github "Dapr Incubation" organization.**
**Action: @artursouza  to create this new org and give STC members OWNER privileges.**

## Release Priorities and Themes 
@artursouza Raised the issue of milestone planning, theme and how to set priorities in planning. This was a follow on from the discussion at the March 2022 STC which includes how the release team operates which is captured in this issue. https://github.com/dapr/community/issues/45

This mostly led to a discussion on component stability
### Component Stable status was discussed including;
- There are too many component still alpha and not stable
- How to get the AWS components to stable
- A top priority should be moved to stable

**Suggestion - Ask the different companies to help move to stable**
At-Bay have contributed to AWS to stable. CNCF provides sponsorship to AWS accounts. 

**Action: @beiwei30 (Ian Alibaba) agreed to talk with the Alibaba API team to have more of the Alibaba components move to stable status.**

**Comment by msfussell** [comment]
Notes captured and reviewed
