### ISSUE TITLE
April 5th 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#149]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on April 5th, 2022, at 10:00am PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by lechnerc77** [comment]
Title: Dapr on Kyma - What to consider and how to start
Abstract:  In this talk and demo we will show how to get started with Dapr on [Kyma](https://kyma-project.io/), how to avoid installation pitfalls and how to use it in combination with the Kyma Stack. Sneak peek available at <https://blogs.sap.com/2022/02/25/whats-new-with-kyma-2.0-installing-your-own-components/>
  
CC @yaron2 : as discussed

**Comment by yaron2** [comment]
@paulgyro will present a production use case of Dapr done by enChoice for a public sector agency.

**Comment by msfussell** [comment]
@lechnerc77 - Thanks for the title and agenda
@paulgyro - Can you suggest a title, agenda and how long you would need?

**Comment by lechnerc77** [comment]
@msfussell : My talk with demo would be something like 20 minutes. Let me know if that's okay

**Comment by paulgyro** [comment]
>@paulgyro - Can you suggest a title, agenda and how long you would need?
Title: How enChoice built a Conversion System with Dapr
Abstract: Paul Widner, Director of Solution Engineering at enChoice discusses a recent success story where his team built a Conversion System for a large public sector retirement agency using Dapr, gRPC, MongoDB, and Azure Service Bus.

**Comment by msfussell** [comment]
@paulgyro - Thanks.How long will you need? Keeping this to under 20 mins would be best.

**Comment by paulgyro** [comment]
> @paulgyro - Thanks.How long will you need? Keeping this to under 20 mins would be best.

Plan on me taking 15 minutes.

**Comment by greenie-msft** [comment]
@paulgyro - 15 minutes works well, thank you.

@lechnerc77 - confirming that you're still available to present?

Please plan on joining the community meeting 10 minutes prior to the scheduled call. That will allow time for a quick tech check. Thanks!.

**Comment by lechnerc77** [comment]
@greenie-msft I confirm that I am available to present - all ready to go :-)

How shall we join the call - is there a meeting request/link?

**Comment by lechnerc77** [comment]
@greenie-msft I have an issue: I cannot sign into the meeting - it wants me to have a commercial account that I do not have

**Comment by greenie-msft** [comment]
hmm, that should not be necessary. Have you tried the instructions listed here: https://github.com/dapr/community#community-meetings

**Comment by lechnerc77** [comment]
This is the meeting link right?
 https://us02web.zoom.us/j/85305980190

**Comment by greenie-msft** [comment]
Yes, that's the correct link.

@paulgyro - was able to sign in with his google account and then provided the passcode. Is that an option for you?

**Comment by artursouza** [comment]
Zoom Call: https://us02web.zoom.us/j/85305980190
Password: eWRhSklVTjJjSnhTaURDcFZaU2ZzQT09

**Comment by paulgyro** [comment]
Note you might need to go to Zoom.com and sign up for a free Zoom account and associate it with your personal Google account (or other supported accounts).

**Comment by lechnerc77** [comment]
@paulgyro That did the trick .. heart rate was rising a bit :-)

**Comment by msfussell** [comment]
Delivered and recorded.
