### ISSUE TITLE
REQUEST: New membership for ItalyPaleAle

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/community#152]
### GitHub Username

@ItalyPaleAle

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

Here's a selection of PRs I've reviewed or authored:

- https://github.com/dapr/dapr/pull/4315
- https://github.com/dapr/docs/pull/1777
- https://github.com/dapr/components-contrib/pull/972
- https://github.com/dapr/components-contrib/pull/1104
- https://github.com/dapr/components-contrib/pull/1290

### Notes

I'm a new engineer in @artursouza's team

**Comment by yaron2** [comment]
+1

**Comment by yaron2** [comment]
Done, check for an invite from GitHub.
