### ISSUE TITLE
Create new org for incubating projects

### ISSUE THREAD

**Issue by artursouza** [dapr/community#154]
The community has many projects related to Dapr, at many different levels of maturity. It can be an SDK or even a whole new framework on top of Dapr. Adding projects that are not production ready to Dapr org can give the perception of insufficient rigor in more stable repositories. Also, there can be projects that are highly ambitious and ambiguous that don't have a space in the Dapr community until it is "ready".

I propose we create the "Dapr Labs" organization (or similar name) to incubate projects under the Dapr brand.

IMO, these projects should be in "Dapr Labs":

- https://github.com/dapr/workflows/
- https://github.com/dapr/dart-sdk

**Comment by yaron2** [comment]
I support this and think it'll allow for greater innovation. We do need to come up with the process of how a project is created in the new org and what's the criteria for acceptance and graduation. (As an example, do we require every project to be governed by a SIG? This might help in reusing existing structures and practices and help tame governance overhead).

Let's discuss this on next week's steering committee call.

**Comment by pkedy** [comment]
I love this idea! I have a project that I have not open sourced yet that aims to make using Dapr even easier. I'd love for it to have a home in the community where it can get feedback and contributions. It's so important for new projects to obtain evidence that they solve for real pain point. Over time, I see a thriving ecosystem of tools being a way to broaden the adoption and usefulness of Dapr.

**Comment by artursouza** [comment]
I am filing a service desk issue with CNCF. Just confirming that we want the org to be named `dapr-incubations`.

**Comment by yaron2** [comment]
> I am filing a service desk issue with CNCF. Just confirming that we want the org to be named `dapr-incubations`.

Either that or `dapr-sandbox` are fine with me.

**Comment by msfussell** [comment]
Looking back, I remember that `dapr-sandbox` was a better name since this aligned with the CNCF concept of projects, where  they start in sandbox state first before move to Dapr org in order to start incubation and eventual graduation.

**Comment by artursouza** [comment]
OK, `dapr-sandbox` it is.

**Comment by msfussell** [comment]
https://github.com/dapr-sandbox created. Per https://github.com/dapr/community/issues/173#issuecomment-1151525495 moved repos to this org

**Comment by msfussell** [comment]
Project moved and ReadMe written. Closing issue
