### ISSUE TITLE
REQUEST: New membership for CrazyHZM

### ISSUE THREAD

**Issue by CrazyHZM** [dapr/community#155]
### GitHub Username

@CrazyHZM

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

dapr/dapr: 

- PRs authored
  - https://github.com/dapr/dapr/pull/3780
  - https://github.com/dapr/dapr/pull/3805
  - https://github.com/dapr/dapr/pull/3883
  - https://github.com/dapr/dapr/pull/3901
  - https://github.com/dapr/dapr/pull/4056
  - https://github.com/dapr/dapr/pull/4099
  - https://github.com/dapr/dapr/pull/4101
  - https://github.com/dapr/dapr/pull/4176
  - https://github.com/dapr/dapr/pull/4232
  - https://github.com/dapr/dapr/pull/4194
  - https://github.com/dapr/dapr/pull/4238
  - https://github.com/dapr/dapr/pull/4293
  - https://github.com/dapr/dapr/pull/4189
  - https://github.com/dapr/dapr/pull/4094
- PRs reviewed
  - https://github.com/dapr/dapr/pull/4305
  - https://github.com/dapr/dapr/pull/3842
- Issues authored
  - https://github.com/dapr/dapr/issues/4231
  - https://github.com/dapr/dapr/issues/4292
  - https://github.com/dapr/dapr/issues/3860
- Issues responded to
  - https://github.com/dapr/dapr/issues/3825
  - https://github.com/dapr/dapr/issues/4202
  - https://github.com/dapr/dapr/issues/3761
  - https://github.com/dapr/dapr/issues/3991
  - https://github.com/dapr/dapr/issues/4051

dapr/components-contrib: 

- Issues authored
  - https://github.com/dapr/components-contrib/issues/1252
- PRs authored
  - https://github.com/dapr/components-contrib/pull/1264
  - https://github.com/dapr/components-contrib/pull/1460

dapr/docs:

- PRs authored
  - https://github.com/dapr/docs/pull/2249
- Issues authored
  - https://github.com/dapr/docs/issues/2248

**Comment by yaron2** [comment]
+1.

**Comment by msfussell** [comment]
+1

**Comment by yaron2** [comment]
@CrazyHZM you have been added to the dapr org. Please look for an email invite from GitHub.
