### ISSUE TITLE
REQUEST: New membership for shivamkm07

### ISSUE THREAD

**Issue by shivamkm07** [dapr/community#156]
### GitHub Username
@shivamkm07

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
- https://github.com/dapr/components-contrib/pull/1420
- https://github.com/dapr/components-contrib/pull/1447
- https://github.com/dapr/components-contrib/pull/1564
- https://github.com/dapr/dapr/pull/4111
- https://github.com/dapr/dapr/pull/4078
- https://github.com/dapr/installer-bundle/pull/1
- Issues responded to
- https://github.com/dapr/components-contrib/issues/952
- https://github.com/dapr/components-contrib/issues/1311
- https://github.com/dapr/cli/issues/731

**Comment by yaron2** [comment]
+1

**Comment by mukundansundar** [comment]
+1

**Comment by artursouza** [comment]
I approve this request.

**Comment by mukundansundar** [comment]
+1

**Comment by msfussell** [comment]
Approved and added as member.
