### ISSUE TITLE
13th April Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#157]
April 2022 STC meeting.
Issues to discuss will be taken from the STC backlog project https://github.com/orgs/dapr/projects/54

Proposed Agenda (will update based on email feedback and community raised issues)

- @yaron2 Review 1.7 release and major items for 1.8 from Diagrid
- @msfussell Consider including Dapr update for CNCF Kubecon Europe as per this request. - [cncf-dapr-maintainers] Dapr Maintainers - CNCF and Kubernetes Project Updates for KubeCon + CloudNativeCon Europe 2022]
- See https://www.surveymonkey.com/r/FPBZ8X3 with suggested response https://1drv.ms/w/s!AiPI1_-ScL2khqkCPIOoWmHsvB79ng?e=QEruF6
- @cvictory Status of the Alibaba components moving to Beta and Stable. See https://discord.com/channels/778680217417809931/834615577372131378/963751691755343893
- Today I have a small update on a Workflow API proposal that will be first sent to the STC after this meeting. @msfussell

**Comment by paulyuk** [comment]
Today I have a small update on a Workflow API proposal that will be first sent to the STC after this meeting.

**Comment by msfussell** [comment]
Update. I posted a reply to CNCF request for Keynote information on Dapr

**Comment by msfussell** [comment]
Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@Forrest-zhao
@paulyuk

Notes from 04/13/2022:

# Agenda:

- @yaron2 Reviewed the 1.7 release and the major items for 1.8 from Diagrid. 
          - See Dapr runtime 1.8. planning item and 17th April community call for summary. STC agree that the planning list reflected the projects direction and needs
          - 
- @msfussell Consider including Dapr update for CNCF Kubecon Europe as per this request. - [cncf-dapr-maintainers] 
          - Action: @msfussell  posted this reply to the CNCF Kubecon committee for review    
          - 
- @cvictory - Covered the status of the Alibaba components moving to Beta and Stable. See https://discord.com/channels/778680217417809f931/834615577372131378/963751691755343893
         - Action @cvictory will continue to work within Alibaba to get components moved to Stable
        
- @paulyuk - Gave an update on Workflow API proposal from Microsoft that was then shared with STC. This proposal is now captured in this issue https://github.com/dapr/dapr/issues/4576

- There was general discussion on the need to have AWS components get to a stable status. @msfussell to reach out to CNCF help desk and ask if there is funding assistance from CNCF to help with paying for running this infrastructure. STC still need to address the issue of who would be willing to write the AWS tests, ideally with AWS involvement. All in STC to come back with suggestions on how to approach this issue.

**Comment by msfussell** [comment]
Notes from STC meeting captured
