### ISSUE TITLE
April 19th 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#158]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on April 19th 2022, at 7:30pm PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by ewassef** [comment]
If possible, I would like to discuss the design and validity of this issue https://github.com/dapr/dapr/issues/4475 
In other words:
Should HTTP Pipelines configured on an app hosting HTTP Endpoints be respected when invoked via Service-to-service invocation which is over grpc?

**Comment by ewassef** [comment]
If possible, I would like to discuss the design and validity of this issue https://github.com/dapr/dapr/issues/4475 
In other words:
Should HTTP Pipelines configured on an app hosting HTTP Endpoints be respected when invoked via Service-to-service invocation which is over grpc?

**Comment by greenie-msft** [comment]
@ewassef - Thank you for the suggestion. The upcoming call (4/19) will focus on the highlights of the 1.7 release. 

We will schedule #4475 into the following call if that suits your availability?

**Comment by ewassef** [comment]
that will work

**Comment by msfussell** [comment]
Delivered.
