### ISSUE TITLE
Dapr Presentation Deck: include Configuration

### ISSUE THREAD

**Issue by attilaszasz** [dapr/community#161]
Please include the Configuration building block in the powerpoint presentation deck.

**Comment by msfussell** [comment]
Agreed. If you need this ASAP, there is a version in the new Dapr DIagrams deck here http://localhost:1313/contributing/contributing-docs/#diagrams-and-images

**Comment by attilaszasz** [comment]
Thanks Mark!
Here's the working link if anybody needs it: https://v1-7.docs.dapr.io/contributing/contributing-docs/#diagrams-and-images

**Comment by msfussell** [comment]
The deck here has been updated with the latest slides https://docs.dapr.io/contributing/presentations/
