### ISSUE TITLE
REQUEST: Approver status for @hhunter-ms in dapr/docs

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/community#166]
### GitHub Username

@hhunter-ms

sponsor: @msfussell 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  *dapr/docs*
  dapr/docs#2212
  dapr/docs#2215
  dapr/docs#2235
  dapr/docs#2239 
  dapr/docs#2244
  dapr/docs#2270
  dapr/docs#2290
  dapr/docs#2309
  dapr/docs#2315
  dapr/docs#2316
  dapr/docs#2317
  dapr/docs#2319 
  dapr/docs#2320
  dapr/docs#2326
  dapr/docs#2330
  dapr/docs#2331
  dapr/docs#2340
  dapr/docs#2345
  dapr/docs#2349
  dapr/docs#2350
  dapr/docs#2356 

  *dapr/js-sdk*
  dapr/js-sdk#174

  *dapr/dotnet-sdk*
  dapr/dotnet-sdk#855

- Issues responded to

  *dapr/docs*
  dapr/docs#1721
  dapr/docs#1754
  dapr/docs#1898
  dapr/docs#1917
  dapr/docs#1980
  dapr/docs#2052 
  dapr/docs#2059
  dapr/docs#2152 
  dapr/docs#2179
  dapr/docs#2180
  dapr/docs#2213
  dapr/docs#2238
  dapr/docs#2254
  dapr/docs#2258
  dapr/docs#2273
  dapr/docs#2289
  dapr/docs#2339

  *dapr/js-sdk*
  dapr/js-sdk#160

**Comment by msfussell** [comment]
+1

**Comment by greenie-msft** [comment]
+1

**Comment by greenie-msft** [comment]
+1

**Comment by msfussell** [comment]
Approved and closed
