### ISSUE TITLE
REQUEST: Approver status for @halspang in dapr/dapr

### ISSUE THREAD

**Issue by halspang** [dapr/community#167]
### GitHub Username

@halspang

Sponsor: @artursouza 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/dapr/pull/4518
https://github.com/dapr/dapr/pull/4458
https://github.com/dapr/dapr/pull/4455
https://github.com/dapr/dapr/pull/4414
https://github.com/dapr/dapr/pull/4388
https://github.com/dapr/dapr/pull/4404
https://github.com/dapr/dapr/pull/4201
https://github.com/dapr/dapr/pull/3730
https://github.com/dapr/dapr/pull/3411
https://github.com/dapr/dapr/pull/3145
https://github.com/dapr/dapr/pull/3064

- Issues responded to
https://github.com/dapr/dapr/issues/4512
https://github.com/dapr/dapr/issues/4044
https://github.com/dapr/dapr/issues/501
https://github.com/dapr/dapr/issues/4514

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
@halspang based on what did you list your contributions here? Is this not a more complete list at least in regards to PRs authored? https://github.com/dapr/dapr/pulls?page=1&q=is%3Apr+author%3Ahalspang+is%3Aclosed

**Comment by halspang** [comment]
@yaron2 - Yeah I just filtered for PRs where I was the author/commenter. Or issues that had myself as a participant.

**Comment by yaron2** [comment]
ok, +1 from me.

**Comment by berndverst** [comment]
+1
