### ISSUE TITLE
REQUEST: New membership for cmendible

### ISSUE THREAD

**Issue by cmendible** [dapr/community#17]
### GitHub Username

[cmendible](https://github.com/cmendible)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/docs/pull/728
https://github.com/dapr/dapr/pull/1725
https://github.com/dapr/docs/pull/647
https://github.com/dapr/components-contrib/pull/361
https://github.com/dapr/dapr/pull/1634
https://github.com/dapr/docs/pull/609
https://github.com/dapr/cli/pull/347
https://github.com/dapr/components-contrib/pull/328
https://github.com/dapr/docs/pull/518
https://github.com/dapr/docs/pull/488
https://github.com/dapr/dotnet-sdk/pull/262
https://github.com/dapr/dotnet-sdk/pull/242
https://github.com/dapr/dotnet-sdk/pull/241
https://github.com/dapr/dotnet-sdk/pull/238
https://github.com/dapr/dapr/pull/1115
https://github.com/dapr/dapr/pull/1107
https://github.com/dapr/dapr/pull/1102
https://github.com/dapr/dapr/pull/1085
https://github.com/dapr/dapr/pull/1059
https://github.com/dapr/docs/pull/324
https://github.com/dapr/components-contrib/pull/206
https://github.com/dapr/components-contrib/pull/185

### Sponsors

@yaron2

**Comment by yaron2** [comment]
I support this request.

/cc @msfussell

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by cmendible** [comment]
Thanks!
