### ISSUE TITLE
May 31st 2022 Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#170]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on May 31st, at 10:00sm  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
Proposed Agenda
1) Proposal: Support HTTP Middleware configuration in service-to-service invocation - Eddie Wassef

**Comment by XavierGeerinck** [comment]
Proposed Agenda Item: Add deprecation for npm package `dapr-client` in favour or `@dapr/dapr`

^ We are moving from the NPM package and would like to announce it as deprecated

**Comment by msfussell** [comment]
Delivered
