### ISSUE TITLE
REQUEST: Approver status for @shubham1172 in dapr/js-sdk

### ISSUE THREAD

**Issue by shubham1172** [dapr/community#171]
### GitHub Username

@shubham1172 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs authored
1. https://github.com/dapr/js-sdk/pull/252
2. https://github.com/dapr/js-sdk/pull/209
3. https://github.com/dapr/js-sdk/pull/192
4. https://github.com/dapr/js-sdk/pull/202
5. https://github.com/dapr/js-sdk/pull/204, https://github.com/dapr/js-sdk/pull/191
6. https://github.com/dapr/js-sdk/pull/189, https://github.com/dapr/js-sdk/pull/210

- PRs reviewed
1. https://github.com/dapr/js-sdk/pull/174
2. https://github.com/dapr/js-sdk/pull/248
3. https://github.com/dapr/js-sdk/pull/184
4. https://github.com/dapr/js-sdk/pull/206
5. https://github.com/dapr/js-sdk/pull/212
6. https://github.com/dapr/js-sdk/pull/242

- Issues responded to
1. https://github.com/dapr/js-sdk/issues/207
1. https://github.com/dapr/js-sdk/issues/175
2. https://github.com/dapr/js-sdk/issues/177
3. https://github.com/dapr/js-sdk/issues/89
4. https://github.com/dapr/js-sdk/issues/18

**Comment by XavierGeerinck** [comment]
Huge +1 @shubham1172 is crucial in the SDK and his contributions aided a lot in the maturity of it

**Comment by berndverst** [comment]
+1

**Comment by artursouza** [comment]
I approve this.

**Comment by msfussell** [comment]
+1

**Comment by shubham1172** [comment]
Thank you everyone🙂
