### ISSUE TITLE
11th May 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#172]
May 2022 STC meeting.
[Issues to discuss can be taken from the STC backlog project https://github.com/orgs/dapr/projects/54]

Agenda
1) Update on outstanding actions from previous STC meetings

    - Update on SIG for API Spec - Yaron
    - Update on SIG for SDKs - Artur
    - Update on on the Alibaba components move to stable status - Ian
    - Update on follow up with CNCF on AWS resources - Mark
    - Action: To create this new Github "Dapr Incubation" organization.@artursouza to create this new org and give STC members OWNER privileges - Artur
    - Update on Improvement processes around releases and issue triaging https://github.com/dapr/community/issues/45 - Artur

2) Discussion and voting on accepting a new building block for Workflows based on https://github.com/dapr/dapr/issues/4576.

3) Dapr NPM_TOKEN for the dapr/js-sdk repository 

4) Other topics

**Comment by XavierGeerinck** [comment]
We would like to add the topic of requesting a new Dapr NPM_TOKEN for the dapr/js-sdk repository and the Dapr.io account on npm

**Comment by yaron2** [comment]
We will be voting on accepting a new building block for Workflows based on https://github.com/dapr/dapr/issues/4576.

**Comment by artursouza** [comment]
I would like to discuss the possibility of Dapr support of a LTS version. We release every 3 months or so, so the support model covers 6 months only.

**Comment by msfussell** [comment]
Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@Forrest-zhao

No attendance
@paulyuk

# Notes from 05/11/2022 Meeting

1) Update on outstanding actions from previous STC meetings
    - Update on SIG for API Spec - @yaron2 provided update on the SIG group and said to read latest issues in the repo
    - Update on SIG for SDKs - @artursouza  - Said no progress had been made. @artursouza, @msfussell mfussell to make progress before June STC meeting
    - Update on on the Alibaba components move to stable status - @beiwei30 gave an update that these are being worked on with 3 components expected to go to stable in v1.8 release
    - Update on follow up with CNCF on AWS resources - @msfussell  gave update the CNCF have resource and waiting to hear back
    - Action: To create this new Github "Dapr Sandbox" organization.@artursouza to create this new org and give STC members OWNER privileges - @artursouza  - No progress. @artursouza to make progress before June STC meeting
    - Update on Improvement processes around releases and issue triaging https://github.com/dapr/community/issues/45 -  @artursouza to send out suggestions on triage process improvements for the dapr and Components Contrib repos

## 2) Discussion and voting on accepting a new building block for Workflows based on https://github.com/dapr/dapr/issues/4576.
 - All attendees read the proposal in advance and there was a unanimous vote to accept this into the Dapr project as a new Building Block API.

## 3) Dapr NPM_TOKEN for the dapr/js-sdk repository 
- This proposal was to move to the the NPM name "Dapr" from currently "Dapr Client" as an improved name for the JScripts client library. There was a unanimous vote to accept this change.

## 4) Support more versions of Dapr and create a Long Term Service (LTS) branch
@artursouza  presented a position that there are customers at Microsoft who was asking for a longer term support than then current N and N-1 versions of Dapr and also asking about having an LTS which is a long stable release especially useful for industries that cannot move fast or places like remote deployments that take time up update.

 For examples of LTC in use today see 
 - https://nodejs.org/en/about/releases/
 - https://www.djangoproject.com/download/
 - https://en.wikipedia.org/wiki/Long-term_support

The proposal is to;
1) Have N and N-2 releases supported (current and previous 2 releases) to address the immediate need of having a support window that is now stretched to 9 months instead of 6 months. This would start with the v1.8 release of Dapr, meaning that v1.8, v1.7 and v1.6 would all be supported at the time of release.
2) Start preparing a plan and create a LTS branch for Dapr starting with a future release. The LTS would be 1.5 or 2 years in length (time length TBD). The proposal would be circulated in the community before committing. 

@artursouza said that given the need by Microsoft for both 1) and 2) above, that Microsoft was willing to fund both the added cost for supporting 3 releases as well as funding the cost of an LTS branch.
@beiwei30 (Ian) Indicated that he was supportive of this and could see how this would be very useful for Alibaba and their customers. 
@msfussell and @yaron2 were supportive of this saying that Diagrid customers would also benefit from this proposal.

The STC voted unanimously to accept the proposal above and Microsoft (from @artursouza) agreed to set about getting the resource funding secured. @artursouza would create a plan for how the LTS branches are managed.

**Comment by msfussell** [comment]
Meeting concluded
