### ISSUE TITLE
8th June 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#173]
June 2022 STC meeting.

Proposed Agenda will be update based on email feedback and community raised issues
STC Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@Forrest-zhao
@paulyuk

Agenda
- Update on actions items from the previous STC meeting
   - Action: @artursouza - To create this new Github "Dapr Sandbox" organization. 
     - @artursouza to create this new org and give STC members OWNER privileges. 
     - What existing repos in Dapr should be moved?
     - https://github.com/dapr/workflows
     - https://github.com/dapr/dart-sdk
     - https://github.com/dapr/generator-dapr
     - https://github.com/dapr/azure-functions-extension
     -Action: @artursouza - Document the process for Sandbox->Dapr Org
     
   - Action: @artursouza - Update on Improvement processes around releases and issue triaging https://github.com/dapr/community/issues/45.
   - Create a PR to update the docs website
      
   - Action: Update on the N-2 support and LTS. 
     - @artursouza to create a plan for how the LTS branches are managed.

 - The first meeting for the SDK Sig was held and actions items were put into the issue into SIG Repo. Update for this at the July STC.
     
- New Items
  - @msfussell - Stabilization release - Proposal to focus the v1.9 release on completing existing work and fundamentals. Notably aligning SDKs with runtime features, component certification and getting more to Stable status, finishing APIs on current building blocks, Stable releases of preview features and reducing the debt on CLI issues
  -@cvictory commented on backward compatibility of SDKs and runtime.
  - @msfussell - Update on Dapr CNCF case studies to promote Dapr's usage in production
  - @msfussell - Thoughts on holding DaprCon 2022 in the Oct/Nov timeframe. 
  - @msfussell - Update on shared Dapr credentials using 1Password account  
  - @paulyuk - Talk about KubeCon

**Comment by paulyuk** [comment]
+1 in favor of the items proposed by @msfussell 

Note I entered a placeholder CFP submission for KubeCon in Oct as well themed around Dapr resiliency.  Here is the abstract.  I would like STC's feedback, and ideally we have more co-presenters from the industry vs just me/microsoft.

**Writing reliable, scalable, fault oblivious code on K8s the easy way**

Remember when writing connected application code to do something innovative was the hard part?  These days developers have to do more than ever, not only to write innovative and elegant code to run their business, but now also have to deal with all the faults, outages, disasters, hot spots, scale points, and concurrency issues that come with building distributed apps and microservices at scale.  In this session, you will learn about the best practices to write distributed app code that sings at scale directly from the team that helped bring you Dapr and a number of hyper-scale cloud services in production.  It will focus on the topics of resiliency, distributed locking, and optimization in common tasks like async messaging & Pub-Sub, state management, secrets and more.  You will also learn about abstractions and implementations to do this the easy way in your favorite programming model and language.

**Comment by msfussell** [comment]
Resolved
