### ISSUE TITLE
June 28th 2022 Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#175]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on June 28th at 10:00am  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
@masters3d - good question. We do need to clarity this more in the repo, on the expectations and criteria for acceptance. If you are developing an SDK, these are encouraged for Dapr.  We will get something in place in the next week.

**Comment by paulyuk** [comment]
@msfussell  I'm happy to show the new Bindings quickstart and explain our modern thinking, if there's interest.
https://docs.dapr.io/getting-started/quickstarts/bindings-quickstart/

**Comment by greenie-msft** [comment]
@msfussell If possible, I'd like 5 minutes to show the GA AKS/Arc k8s Dapr extension.

**Comment by ItalyPaleAle** [comment]
If interested, I can give a 5-min demo of the "watchdog" that watches for pods that do not have the Dapr sidecar.

**Comment by DeepanshuA** [comment]
I can also demo health check endpoint APIs, slated for v1.9, if interested.

**Comment by masters3d** [comment]
Maybe next time but I am wondering if it is expected to folks to sign into to zoom
![image](https://user-images.githubusercontent.com/6539412/176242026-117b3c7c-2bdd-48a1-9dd7-83300046f869.png)

**Comment by msfussell** [comment]
Delivered
