### ISSUE TITLE
REQUEST: Approver Status for @italypaleale in Contrib

### ISSUE THREAD

**Issue by berndverst** [dapr/community#177]
As a maintainer of Components-Contrib I would like to nominate @ItalyPaleAle as an **approver** of Contrib.

I am sure everyone is aware of Alessandro's many contributions but below you will find just some of them in support of this nomination.

### List of contributions to the Dapr project

Here are some of the contribution Alessandro has made in his words:

I've implemented the core support for Azure AD auth in components. Multiple PRs, but the main relevant ones are:
- https://github.com/dapr/components-contrib/pull/972
- https://github.com/dapr/components-contrib/pull/1104
There's an open issue to track progress: https://github.com/dapr/components-contrib/issues/1103
I made too many PRs against Cosmos DB components, to add support for Azure AD, fix a bunch of bugs, etc

In the S3 component, I've made changes to make it work better with Minio, including enabling support for self-signed TLS certs:
- https://github.com/dapr/components-contrib/pull/1593

I drove the migration to Go 1.18:
- https://github.com/dapr/components-contrib/pull/1697

I've updated the Service Bus components to the new SDK:
- https://github.com/dapr/components-contrib/pull/1702

Other contributions:
- https://github.com/dapr/components-contrib/issues/1753 for AWS SNS/SQS (fixed via PR in dapr/dapr)
- https://github.com/dapr/components-contrib/pull/1737 for MQTT
- https://github.com/dapr/components-contrib/pull/1755 for Kafka
- https://github.com/dapr/components-contrib/pull/1754 for AWS SNS/SQS

Among PRs I've reviewed:
- https://github.com/dapr/components-contrib/pull/1751
- https://github.com/dapr/components-contrib/pull/1698
- https://github.com/dapr/components-contrib/pull/1726
- https://github.com/dapr/components-contrib/pull/1685
- https://github.com/dapr/components-contrib/pull/1708

**Comment by berndverst** [comment]
I support this nomination :)

**Comment by msfussell** [comment]
I support this nomination

**Comment by yaron2** [comment]
This request can now be approved as there are no pending objections from current maintainers.
