### ISSUE TITLE
REQUEST: New membership for hueifeng

### ISSUE THREAD

**Issue by hueifeng** [dapr/community#179]
### GitHub Username

@hueifeng

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

#### PRs

- [dapr/cli](https://github.com/dapr/cli/pulls?q=is%3Apr+author%3Ahueifeng+)
- [dapr/dapr](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3Ahueifeng+)
- [dapr/dotnet-client](https://github.com/dapr/dotnet-sdk/pulls?q=is%3Apr+author%3Ahueifeng+)
- [dapr/dashboard](https://github.com/dapr/dashboard/pulls?q=is%3Apr+author%3Ahueifeng+)

#### reviews
- [dapr/cli](https://github.com/dapr/cli/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40me)

#### issues

- [dapr:3837](https://github.com/dapr/dapr/issues/3837#issuecomment-997635349)
- [(dapr:cli):962](https://github.com/dapr/cli/issues/962)
- [(dapr:cli):991](https://github.com/dapr/cli/issues/991)
- [(dapr:cli):925](https://github.com/dapr/cli/issues/925)
- [(dapr:cli):952](https://github.com/dapr/cli/issues/952)
- [(dapr:cli):916](https://github.com/dapr/cli/issues/916)
- [(dapr:cli):978](https://github.com/dapr/cli/issues/978)
- [(dapr:cli):1003](https://github.com/dapr/cli/issues/1003)
- [(dapr:dashboard):201](https://github.com/dapr/dashboard/issues/201)
- https://github.com/dapr/cli/issues/884

Thanks

**Comment by yaron2** [comment]
I support this membership request.

**Comment by artursouza** [comment]
I support this request.
