### ISSUE TITLE
REQUEST: New membership for @sayboras

### ISSUE THREAD

**Issue by sayboras** [dapr/community#18]
### GitHub Username

@sayboras

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [PRs reviewed / authored](https://github.com/pulls?q=is%3Apr+org%3Adapr+author%3Asayboras+)
- [Issues responded to](https://github.com/pulls?q=is%3Aissue+org%3Adapr+author%3Asayboras+)

/cc @yaron2 @youngbupark

**Comment by yaron2** [comment]
I support this request.

**Comment by youngbupark** [comment]
I support this request as well.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yaron2** [comment]
Added
