### ISSUE TITLE
13th July 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#182]
July 2022 STC meeting.

Proposed Agenda will be update based on email feedback and community raised issues

STC Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@Forrest-zhao
@paulyuk

Agenda - See below

**Comment by artursouza** [comment]
Community Call's schedule is not friendly to India timezone. We should consider moving to 9am PST since that is the only call we have in English. We have moved the PST evening to the Chinese Dapr community.

**Comment by artursouza** [comment]
Another topic, as requested by @skyao:

dapr china community website

This is for preview: 

[https://dapr.skyao.io](https://dapr.skyao.io) 

Actions: 

Apply to use domain cn.dapr.io
add dns of "cn.dapr.io" to point to IP 101.32.220.15 for preview
Web site host:
near China, suggest to HongKong
Change DNS of “cn.dapr.io”
github workflow to auto deploy this web site

**Comment by artursouza** [comment]
Another update for Chinese community:

Create an official channel in https://bilibili.tv

Add link to YouTube and BiliBili on https://github.com/dapr/dapr#videos-and-podcasts

**Comment by cvictory** [comment]
I have one thing need to discuss:
@beiwei30 will return to alibaba group from alicloud, and I will go to new department. I spend half of my time in e-commerce promotions, and the other half of my time is responsible for dev ops system.
As you known, at alicloud, we use dapr in faas situation. The faas team will continue to work at dapr and will use dapr in faas instead of [rsocket](https://rsocket.io/) proxy.  So I discussed with @beiwei30 and have some suggestion as following：
1. @beiwei30  will give up the stc seat to faas team member.
2. I'm keeping my seat for now, and it's also convenient to make a handover with faas team member. I will spend some time on community things, and internal landing things will be handed over to faas team. I will continue to focus on the possibility of dapr commercial exploration.

**Comment by msfussell** [comment]
Agenda
- Previous agenda item updates
- Action: @artursouza - Document the process for what is accepted into Sandbox and Sandbox->Dapr Org
- Action: @artursouza to create a plan for how the LTS branches are managed.
- Action: @msfussell - Case studies. Two cases studies are currently in progress and plan to be published in the next 3 weeks
- Action: @msfussell AWS Dapr Infrastructure account. Using the dapr.io email account a request has been submitted on 7/12 to AWS for credits as a OSS CNCF project. 


New Items
- Alibaba seat 
- DaprCon 2022. Having talked with CNCF events coordinator, propose having a DaprCon2022, similar to these events https://events.linuxfoundation.org/wp-content/uploads/2022/07/sponsor-cncf-2022-07.11.22.pdf
- Community call time slot

**Comment by msfussell** [comment]
## STC Attendees:
@msfussell
@yaron2
@artursouza
@beiwei30
@cvictory
@paulyuk

Absent (vacation)
@Forrest-zhao

## Agenda

Previous agenda/actions item updates
Action: @artursouza - Document the process for what is accepted into Sandbox and Sandbox->Dapr Org. This issue https://github.com/dapr/community/issues/183. @artursouza will continue to work on the issue. 
Action: @artursouza to create a plan for how the LTS branches are managed. On going
Action: @msfussell CNCF Case studies. Two cases studies are currently in progress and plan to be published in the next 3 weeks
Action: @msfussell AWS Dapr Infrastructure account. Using the dapr.io email account a request has been submitted on 7/12 to AWS for credits as a OSS CNCF project. Waiting on AWS to approve/deny.
Action: @msfussell - Update on shared Dapr credentials using 1Password account. This is still ongoing and needs help from Microsoft. 

## New Items
+ Alibaba seat @cvictory @beiwei30 - Explain that due to change of work commitments @beiwei30 (Ian) would be stepping down from the STC. Under the bootstrap period Alibaba would will nominate a new person in Ian's place on the STC, who will start next month in Aug. 

+ DaprCon 2022. @msfussell - Having talked with CNCF events coordinator, propose having a DaprCon2022, similar to these events. The STC agreed that having an in-person DaprCon half-day event at KubeCon 2022 NA was the preferred choice. @msfussell will work with Nyemade from Microsoft on preparing an agenda and working with CNCF events committee.

+ KubeCon 2022 Dapr Maintainers talk submitted - @artursouza. The talk will cover the pluggable components model for Dapr. 

+ Community call time slot @artursouza - Proposed and accepted to change this time to be 9am on Wednesday's starting in Aug/Sept so that people in India could attend. @artursouza to update PR to change times on the community page

+ Discussed the ongoing growth in the China community. The community is growing rapidly.  @skyao (Microsoft) launched a new website https://cn.dapr.io/, will work closely with Alibaba and Intel to promote Dapr content in China and publish new videos on an official Dapr channel in https://bilibili.com/. @artursouza to work with @skyao to update the community overview page to list (in chinese) the location and time of these China events and videos.

**Comment by skyao** [comment]
update for “to update the community overview page to list (in chinese) the location and time of these China events and videos.”

https://github.com/dapr/community/pull/194

**Comment by skyao** [comment]
> Web site host:
> near China, suggest to HongKong
> Change DNS of “cn.dapr.io”
> github workflow to auto deploy this web site

Who can help to do this?

**Comment by artursouza** [comment]
@msfussell How can we host the Chinese website for Dapr? Right now it is under skyao's account.

**Comment by msfussell** [comment]
> @msfussell How can we host the Chinese website for Dapr? Right now it is under skyao's account.

You can raise a ticket with CNCF service desk. They have a website service and can help set this up for you.

**Comment by msfussell** [comment]
Closing
