### ISSUE TITLE
Process for Sandbox Projects

### ISSUE THREAD

**Issue by artursouza** [dapr/community#183]
We now have the `dapr-sandbox` org in GitHub but we don't have a process to accept or graduate projects. I propose the process:

## Admission to dapr-sandbox

A project is admitted to the `dapr-sandbox` project if it is approved by at least 3 STC members and not rejected by any within 7 days of the request being filed. The request must be filed within the `dapr/community` repo.

### Admission Form

1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.
2. Which programming languages will be used?
3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform
4. Enumerate the repositories this project will need to be created.
5. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?
6. Who are the maintainers of this project and corresponding employers?

## Graduation

A project is graduated from `dapr-sandbox` to `dapr` org if at least 2/3 of the STC members vote approving the graduation. The request to graduate must be filed within the `dapr/community` repo.

### Graduation Form

1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios. Highlight changes from the original vision.
2. Who are the maintainers for the project and corresponding employers?
3. Will any maintainer stop contributing in case of employment change?
4. Describe 3 users with 1 scenario each in production.
5. Which automated tests are implemented in the project (unit tests, end-to-end tests, performance tests, stress tests, etc). Please, provide a link to most recent test runs.
6. Please, provide link to samples, documentation and milestone planning.

**Comment by msfussell** [comment]
Each  project needs to have a  sandbox submission form with a set of questions so that people understand whether they would be successful or not. What is the acceptance criteria. Then the STC knows what they are voting on and this is not subjective. What projects have a likelihood of being accepted and which one rejected. And if rejected, do we provide a explanation for the rejection or not?

The CNCF has this form and the same is needed for Dapr sandbox.  The CNCF holds sandbox review meetings every 6 months and published the reasons for accepting and rejecting
https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true

**Comment by masters3d** [comment]
Is a project synonymous to git repo? In the case of SDKs we seem to have chosen to have separate git repositories per language but I assume that we want to support as many languages as there are maintainers. 

If we consider SDKs under the singular umbrella of "Client SDK" then a new language support in just a sub feature of the SDK main feature.  I guess perhaps I am trying to say that client SDK should have their own criteria that focuses on parity

**Comment by artursouza** [comment]
> Each project needs to have a sandbox submission form with a set of questions so that people understand whether they would be successful or not. What is the acceptance criteria. Then the STC knows what they are voting on and this is not subjective. What projects have a likelihood of being accepted and which one rejected. And if rejected, do we provide a explanation for the rejection or not?
> 
> The CNCF has this form and the same is needed for Dapr sandbox. The CNCF holds sandbox review meetings every 6 months and published the reasons for accepting and rejecting https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true

We should have a form but I don't think we should wait for a semester to decide to accept a project (github repo). The bar is not that high. To graduate into the main Dapr org, we should have that as part of the STC. I will update the proposal to include a template.

**Comment by artursouza** [comment]
> > Each project needs to have a sandbox submission form with a set of questions so that people understand whether they would be successful or not. What is the acceptance criteria. Then the STC knows what they are voting on and this is not subjective. What projects have a likelihood of being accepted and which one rejected. And if rejected, do we provide a explanation for the rejection or not?
> > The CNCF has this form and the same is needed for Dapr sandbox. The CNCF holds sandbox review meetings every 6 months and published the reasons for accepting and rejecting https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true
> 
> We should have a form but I don't think we should wait for a semester to decide to accept a project (github repo). The bar is not that high. To graduate into the main Dapr org, we should have that as part of the STC. I will update the proposal to include a template.

Updated the proposal with template forms.

**Comment by Haishi2016** [comment]
Can we specify how to submit the form?

**Comment by mukundansundar** [comment]
@artursouza As a follow-up are there scenarios that we should consider on either archiving/moving to sandbox a repo in main project that's not maintained currently?? Is there any guidelines regarding that?

**Comment by artursouza** [comment]
> @artursouza As a follow-up are there scenarios that we should consider on either archiving/moving to sandbox a repo in main project that's not maintained currently?? Is there any guidelines regarding that?

Not yet. I think we can focus on that next. I would like to agree on the criteria to start the process first.

**Comment by paulyuk** [comment]
Per chat, suggest we emphasize maintainer's plan to stay with it, more so than a company/employer.  

Otherwise LGTM

**Comment by paulyuk** [comment]
Should we have graduation criteria around existence or plans for SDKs and Docs, so a sandbox does not graduate and create instant debt?  Also how do we decide if something goes into the core Dapr builds, or an pluggable component?

**Comment by msfussell** [comment]
This was discussed in STC and the process captured into the repo
