### ISSUE TITLE
Tuesday July 12th Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#184]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday July 12th, at 10am  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
@johnewart - I will demo pluggable components, I have a barebones .NET SDK and Redis state store + in-memory pub/sub component I will record it ahead of time to avoid live demos, so I can pretty easily squeeze it into 5 minutes or so

**Comment by shubham1172** [comment]
I can present the new support for installing certificates in Dapr sidecar by demonstrating the scenario from https://github.com/dapr/dapr/issues/4587. I can also record it ahead of time, 5-10 minutes should suffice.

**Comment by msfussell** [comment]
Building an agenda
- Support for certificates load on sidecars
- Pluggable components.
- ?

**Comment by pravinpushkar** [comment]
I can talk about components capabilities API change (metadata API). It will not take more than 3-4 mins.

**Comment by msfussell** [comment]
Delivered
