### ISSUE TITLE
Tuesday July 26th, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#185]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Tuesday July 26th, at 10am PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
Q:  From George Stevens - If not at the next community meeting, but perhaps the next one, please present the Dapr Workflow proposal.  Lotsa people will love it!  Just a sketch of what's in the works would work fine.  No need to have running code.... yet.

**Comment by msfussell** [comment]
Demo this 1.9 feature https://github.com/dapr/community/issues/175#issuecomment-1168169165

**Comment by nyemade-uversky** [comment]
I have a topic idea - DaprCon. We're already in the process of discussing what DaprCon could look like with CNCF so the community call would be a great chance to share: (1) where we are on that and (2) do an open call for community members interested in participating

**Comment by nyemade-uversky** [comment]
Another topic idea - Pluggable Component proposal walkthrough by @johnewart . He gave a demo last week but I think it could still be valuable to discuss the actual proposal [#4925](https://github.com/dapr/dapr/issues/4925) on a community call.

**Comment by greenie-msft** [comment]
@DeepanshuA would you be open to covering the health check endpoint APIs feature?

**Comment by artursouza** [comment]
I will present `{podName}` feature in pubsub.
