### ISSUE TITLE
REQUEST: New membership for RicardoNiepel

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/community#19]
### GitHub Username

@RicardoNiepel

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x]  I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [https://github.com/dapr/dapr/issues?q=author%3ARicardoNiepel+](runtime repo)
- [https://github.com/dapr/docs/issues?q=author%3ARicardoNiepel+](docs repo)
- [https://github.com/dapr/components-contrib/issues?q=author%3ARicardoNiepel+](comp repo)
- [https://github.com/dapr/dotnet-sdk/issues?q=author%3ARicardoNiepel](sdk repo)

### Sponsors

@yaron2 @msfussell

**Comment by yaron2** [comment]
I support this request.

**Comment by RicardoNiepel** [comment]
Adding also @artursouza as **Sponsor**

### Contributions
Adding also my already done public talks ([slides](https://github.com/RicardoNiepel/talks#2020))
* 28.04. - 14. Azure Enterprise Architects Forum
  Einführung in die Entwicklung verteilter Anwendungen mit Dapr
* 11.05. - Microsoft Virtual Training Week Germany, Mai 2020
  Introduction into building distributed apps using dapr.io
* 23.09. - BASTA! – Konferenz für .NET, Windows & Open Innovation, Herbst 2020
  Distributed Application Runtime (Dapr) für .NET-Entwickler

And upcoming talks
* 28.10. - [Cloud Native Club](https://www.microsoft.com/de-de/techwiese/cloud-native-community-blog/neue-video-reihe-cloud-native-club.aspx)

as contributions to the overall project.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by artursouza** [comment]
Double approved 👍

**Comment by yaron2** [comment]
Added
