### ISSUE TITLE
REQUEST: New approver request for amulyavarote

### ISSUE THREAD

**Issue by amulyavarote** [dapr/community#190]
### GitHub Username

e.g. (at)example_user

amulyavarote

Sponsored by @XavierGeerinck 

Request for becoming the approver in js-sdk repo.

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored

https://github.com/dapr/js-sdk/pull/306
https://github.com/dapr/js-sdk/pull/212
https://github.com/dapr/js-sdk/pull/211
https://github.com/dapr/js-sdk/pull/190
https://github.com/dapr/js-sdk/pull/181

- Issues responded to

https://github.com/dapr/js-sdk/issues/284
https://github.com/dapr/js-sdk/issues/283
https://github.com/dapr/js-sdk/issues/258

**Comment by XavierGeerinck** [comment]
Amulya was key in helping on the JS SDK, I support the approver status for her :)

**Comment by artursouza** [comment]
I approve this request as well.
