### ISSUE TITLE
REQUEST: Approver status for @pravinpushkar in dapr/cli

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/community#191]
### GitHub Username

@pravinpushkar

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/cli/pull/888
https://github.com/dapr/cli/pull/899
https://github.com/dapr/cli/pull/912
https://github.com/dapr/cli/pull/920
https://github.com/dapr/cli/pull/982
https://github.com/dapr/cli/pull/926
https://github.com/dapr/cli/pull/930
https://github.com/dapr/cli/pull/931
https://github.com/dapr/cli/pull/940
https://github.com/dapr/cli/pull/983
https://github.com/dapr/cli/pull/984
https://github.com/dapr/cli/pull/986
https://github.com/dapr/cli/pull/1014
https://github.com/dapr/cli/pull/994
https://github.com/dapr/cli/pull/895
     
- Issues responded to
https://github.com/dapr/cli/issues/974
https://github.com/dapr/cli/issues/981
https://github.com/dapr/cli/issues/1001
https://github.com/dapr/cli/issues/891
https://github.com/dapr/cli/issues/1013
https://github.com/dapr/cli/issues/979

**Comment by mukundansundar** [comment]
+1

**Comment by hueifeng** [comment]
+1

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
Changes done. Closing. Congrats, @pravinpushkar!
