### ISSUE TITLE
Wednesday August 10th, Community Meeting Agenda

### ISSUE THREAD

**Issue by greenie-msft** [dapr/community#199]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on <Date>, at <Time>  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by nyemade-uversky** [comment]
Topic idea: DaprCon update

**Comment by yaron2** [comment]
I'll do a demo for "Efficient AWS S3 file uploads"

**Comment by yaron2** [comment]
I'll also talk about the upcoming support for the OpenTelemetry protocol in Dapr 1.9.

**Comment by nyemade-uversky** [comment]
@greenie-msft  would you be able to close this issue now that the call has passed?
