### ISSUE TITLE
REQUEST: Approver status for @shubham1172 in dapr/cli

### ISSUE THREAD

**Issue by shubham1172** [dapr/community#202]
### GitHub Username

@shubham1172 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

PRs authored
- https://github.com/dapr/cli/pull/1040
- https://github.com/dapr/cli/pull/1036
- https://github.com/dapr/cli/pull/1033
- https://github.com/dapr/cli/pull/1020
- https://github.com/dapr/cli/pull/1000
- https://github.com/dapr/cli/pull/905

PRs reviewed
- https://github.com/dapr/cli/pull/993
- https://github.com/dapr/cli/pull/878
- https://github.com/dapr/cli/pull/895
- https://github.com/dapr/cli/pull/899
- https://github.com/dapr/cli/pull/912
- https://github.com/dapr/cli/pull/940

Issues responded to
- https://github.com/dapr/cli/issues/979
- https://github.com/dapr/cli/issues/965
- https://github.com/dapr/cli/issues/1003
- https://github.com/dapr/cli/issues/684
- https://github.com/dapr/cli/issues/879
- https://github.com/dapr/cli/issues/964

**Comment by mukundansundar** [comment]
+1

**Comment by hueifeng** [comment]
+1

**Comment by pravinpushkar** [comment]
+1

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
Done. Congrats, @shubham1172!

**Comment by shubham1172** [comment]
Thank you everyone!
