### ISSUE TITLE
REQUEST: Approver status for @italypaleale in dapr/dapr

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/community#206]
### GitHub Username
@ItalyPaleAle

### Sponsor

@artursouza

### Requirements
* [x]  I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account. See https://github.com/settings/security
* [x]  I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
* [x]  I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

I'm limiting this to a **small selection** from the runtime repo 

PRs authored

* [A lot](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3Aitalypaleale)
* Small selection of high profile ones:
   * https://github.com/dapr/dapr/pull/4846
   * https://github.com/dapr/dapr/pull/4903 and all its spin-offs
   * https://github.com/dapr/dapr/pull/4764
   * https://github.com/dapr/dapr/pull/4729
   * https://github.com/dapr/dapr/pull/4707

PRs reviewed

* https://github.com/dapr/dapr/pull/5024
* https://github.com/dapr/dapr/pull/4808
* https://github.com/dapr/dapr/pull/5033
* https://github.com/dapr/dapr/pull/5025
* https://github.com/dapr/dapr/pull/5054
* https://github.com/dapr/dapr/pull/4923
* https://github.com/dapr/dapr/pull/4862
* https://github.com/dapr/dapr/pull/4842

Issues responded to

* https://github.com/dapr/dapr/issues/5059
* https://github.com/dapr/dapr/issues/4804
* https://github.com/dapr/dapr/issues/5023
* https://github.com/dapr/dapr/issues/4970
* https://github.com/dapr/dapr/issues/3968
* https://github.com/dapr/dapr/issues/4921
* https://github.com/dapr/dapr/issues/4866
* https://github.com/dapr/dapr/issues/4892

Misc

* I drove the release of the last 5 hotfix releases (1.7.4, 1.8.1 through 1.8.4)

**Comment by berndverst** [comment]
👍

**Comment by artursouza** [comment]
I approve this.
