### ISSUE TITLE
14th Sept 2022 : Steering and Technical Committee (STC) Agenda 

### ISSUE THREAD

**Issue by msfussell** [dapr/community#208]
Sept 2022 STC meeting.

Proposed Agenda will be update based on email feedback and community raised issues

STC Attendees:
@msfussell
@yaron2
@artursouza
Jack Zhao (Alibaba)
@cvictory
@Forrest-zhao
@paulyuk

Sept 2022 STC Agenda

- Review of outstanding action items from Aug STC - Mark

  - Action: @paulyuk - Update on shared Dapr credentials using 1Password account. Ongoing and will be closed out for the Sept STC meeting
  - Action: @paulyuk - Took on responsibility to update the Dapr website (dapr.io) before KubeCon 2022 to include new cases studies and refresh any of the graphics and wording. This will be reviewed by the STC before publishing.
  - Action: @artursouza to create a plan for how the LTS branches are managed.

- Next security audit for Dapr- Artur
- Submitted DaprCon 2022 submissions - Mark
- Next STC meeting 12th Oct 2022 - Mark

**Comment by artursouza** [comment]
Proposed agenda item: next security audit for Dapr

**Comment by msfussell** [comment]
# Attendees
In attendance
@msfussell
@yaron2
@artursouza
@cvictory
Jack Zhao

No attendance
@Forrest-zhao
@paulyuk

# Notes from Sept 2022 STC  meeting

1. Reviewed of Aug agenda/actions item updates (see https://github.com/dapr/community/issues/192)

  - Action: @paulyuk - Update on shared Dapr credentials using 1Password account. Ongoing and will be closed out for the Sept STC meeting. No update. 
  - Action: @paulyuk - Took on responsibility to update the Dapr website (dapr.io) before KubeCon 2022 to include new cases studies and refresh any of the graphics and wording. @msfussell has update the cases studies on the website. @paulyuk to review any other changes. 
  - Action: @artursouza to create a plan for how the LTS branches are managed. On hold. 

2. Next security audit for Dapr - Artur
STC agreed to hold the next independent security audit in Jan 2023 and set a cadence of having one every 2 years.
Action: @artursouza - Reach out to CNCF for funding 
Action: @msfussell - Update the documentation. https://github.com/dapr/docs/issues/2795

3. Submitted DaprCon 2022 submissions - Mark
@msfussell reviewed with the STC the final the set of sessions being submitted to CNCF for DaprCon

4. Agreed next STC meeting 12th Oct 2022

**Comment by msfussell** [comment]
Resolved

**Comment by msfussell** [comment]
Resolved
