### ISSUE TITLE
September 21st, Community Meeting Agenda

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/community#211]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on September 21st, at 9AM PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by nyemade-uversky** [comment]
@mcandeia Did you still want to present at this community call? 

You mentioned you wanted to share your work with conformance tests as a github action for pluggable components

**Comment by mcandeia** [comment]
Yes, please @nyemade-uversky include my demo there, it should be short, something around 10 minutes max.

**Comment by DanielMeixner** [comment]
Hey, if there's 20min available in this session I'd love to show a demo on dapr resiliency I built.

**Comment by nyemade-uversky** [comment]
I'll speak on DaprCon updates (as usual)

**Comment by yaron2** [comment]
> Hey, if there's 20min available in this session I'd love to show a demo on dapr resiliency I built.

Please show up, it'd be great to demo this.

**Comment by msfussell** [comment]
Delivered
