### ISSUE TITLE
October 19th, Community Meeting Agenda

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/community#213]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on October 19th, at 9AM PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by rahulbhargav** [comment]
Hey, can I have a 15 min slot in this session to talk about and demo the dapr SDK we are working on for Haskell language? [haskell-dapr](https://github.com/nodew/)

**Comment by nyemade-uversky** [comment]
@rahulbhargav That's awesome to hear! Would you be able to fill out this short form to tell us more about the topic you wanted to speak about?

Here's the form: [Community call presenter sign-up](https://forms.gle/hhnQEnCSifkceia28)

**Comment by nyemade-uversky** [comment]
@rahulbhargav would you be able to say more about what your presentation will be about?

**Comment by yaron2** [comment]
I'll cover a "Milestone overview for Dapr 1.10".

**Comment by berndverst** [comment]
I will be covering the DocumentStore as a new building block proposal.

https://github.com/dapr/dapr/issues/5146
