### ISSUE TITLE
12th Oct 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#218]
Oct 2022 STC meeting.

Proposed Agenda will be update based on email feedback and community raised issues

STC Attendees:
@msfussell
@yaron2
@artursouza
Jack Zhao (Alibaba)
@cvictory
@Forrest-zhao
@paulyuk

Previous Sept meeting notes https://github.com/dapr/community/issues/208

# Action items from previous meetings
1) Action: @paulyuk - Update on shared Dapr credentials using 1Password account. 
2) Action: @artursouza to create a plan for how the LTS branches are managed. On hold.
3) Action: @msfussell - Update the documentation. Update the cadence for security reviews and releases.  docs#2795

# Oct 2022 STC  New Agenda
1) @yaron2 -  how/if we can accept pluggable components contributions into Dapr. See discussion here: https://github.com/dapr/community/issues/231
2) @paulyuk - I'd like to share initial ideas to try this month on a revision of the dapr.io website.
3) @msfussell - Make STC aware of the Dapr release lifecycle proposal document. Shared here https://docs.google.com/document/d/1IOkhZSLsRxwhXqrhnCB6vTCD3JxLQ7nmc4P8Ua2uWJ8/edit
4) 1.10 release schedule. Planned for next Jan/Feb next year. 
5) Agreed next STC meeting Thurs 10th Nov 2022

**Comment by yaron2** [comment]
I'd like to discuss how/if we can accept pluggable components contributions into Dapr. See discussion here: https://github.com/dapr/community/issues/231.

**Comment by paulyuk** [comment]
I'd like to share initial ideas to try this month on a revision of the `dapr.io` website.  Note, unfortunately we do not have page-by-page level analytics working on this site, so my first proposal is to add deeper instrumentation this month, so we can learn about where users like content and/or drop off, and that will inform highest priority changes to make for next month.

**Comment by paulyuk** [comment]
I'm also pleased to report the progress of moving all Dapr assets to the identity and credential vault used by STC, along with 2FA protection

![image](https://user-images.githubusercontent.com/1968137/195413008-66eac4ee-ecbf-48f1-8e5e-8c3c559f9e57.png)

**Comment by msfussell** [comment]
Resolved
