### ISSUE TITLE
REQUEST: New membership for @jigargandhi

### ISSUE THREAD

**Issue by jigargandhi** [dapr/community#22]
### GitHub Username

@jigargandhi

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
I have contributed to 7 PRs and one is in progress in, see [my PRs](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3Ajigargandhi+is%3Aclosed)

**Comment by yaron2** [comment]
I support this request.

**Comment by yaron2** [comment]
@youngbupark as additional approver

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yaron2** [comment]
Added
