### ISSUE TITLE
REQUEST: Approver status for tanvigour in dapr/test-infra

### ISSUE THREAD

**Issue by tanvigour** [dapr/community#220]
### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/test-infra/pull/144
https://github.com/dapr/test-infra/pull/146
https://github.com/dapr/test-infra/pull/143
https://github.com/dapr/test-infra/pull/140
https://github.com/dapr/test-infra/pull/138
https://github.com/dapr/test-infra/pull/130
https://github.com/dapr/test-infra/pull/136
https://github.com/dapr/test-infra/pull/132
 
- Issues responded to
https://github.com/dapr/test-infra/issues/103
https://github.com/dapr/test-infra/issues/147
https://github.com/dapr/test-infra/issues/148
https://github.com/dapr/test-infra/issues/122

Also, I have had most of my contribution to test-infra for longhaul setup early on, which was run at that time through my fork for most part which is why these don't cover all the contributions I made that time.
 
Advocate/Reference : @halspang

**Comment by artursouza** [comment]
I support this request.

**Comment by artursouza** [comment]
Making Tanvi approver of test-infra.
