### ISSUE TITLE
Request for new sandbox project: <haskell-sdk>

### ISSUE THREAD

**Issue by nodew** [dapr/community#221]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.
>Haskell is an advanced, purely functional programming language.
>This project is to build a Dapr SDK for Haskell users.
>This project is a good example for how we can port Dapr to functional programming language.

2. Which programming languages will be used?
>Haskell

3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform
>No

4. Enumerate the repositories this project will need to be created.
>haskell-sdk

5. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?
>In 6 months.

6. Who are the maintainers of this project and corresponding employers?
>Qiao Wang from Microsoft

7. Others
> There's already a project in my personal repo <[haskell-dapr](https://github.com/nodew/haskell-dapr)>

**Comment by artursouza** [comment]
@nodew repo has been created - see invite in your e-mail's inbox.

https://github.com/dapr-sandbox/haskell-sdk
