### ISSUE TITLE
Request to rename/rebrand the Logic Apps-based workflows sandbox project

### ISSUE THREAD

**Issue by cgillum** [dapr/community#223]
The following sandbox project is called "workflows", which is confusing since it's not related to the [Dapr Workflow](https://github.com/dapr/dapr/issues/4576) proposal that was more recently accepted by the STC.

https://github.com/dapr-sandbox/workflows

For example, a Google search for "Dapr Workflow" shows this project as the top result.

![image](https://user-images.githubusercontent.com/2704139/191874441-c93e7918-8c0e-4b92-9052-327c7390e068.png)

This issue is to request a rebranding of this project to help reduce confusion between this project (which I don't believe is being maintained) and the Dapr Workflow project which is under active development.

**Comment by yaron2** [comment]
I'm in favor of archiving (and renaming) the current Dapr Workflows repository. I'll bring this up with STC next meeting.

**Comment by artursouza** [comment]
I also approve renaming or archiving. If we decide to archive, then a 3rd party can decide to fork and continue development.

**Comment by artursouza** [comment]
Done: https://github.com/Azure/dapr-logicapps-extension

**Comment by msfussell** [comment]
Closing issue
