### ISSUE TITLE
Create repo `winget-pkgs` under dapr org

### ISSUE THREAD

**Issue by shivamkm07** [dapr/community#229]
A new repo `winget-pkgs` is required under dapr organization which should be the fork of official [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo. This is required as a part of the work done for https://github.com/dapr/cli/issues/424. 

For every release of a package in winget, a new manifest need to be added in [winget-pkgs](https://github.com/microsoft/winget-pkgs) by creating a PR: https://learn.microsoft.com/en-us/windows/package-manager/package/repository. To avoid manually creating PRs at every release, there is the option to use official Microsoft [wingetcreate](https://github.com/microsoft/winget-create), which will create PRs automatically with updated release information like version, InstallerUrl etc. This however requires a source repo to create the PRs from, which should be a fork of the official [winget-pkgs](https://github.com/microsoft/winget-pkgs). Also, a token is required for creating the PRs , which should have at least `public:repo` permissions: [github-personal-access-token-permissions]( https://github.com/microsoft/winget-create#github-personal-access-token-permissions).

So following two actions need to be taken:
1. Create fork of [winget-pkgs](https://github.com/microsoft/winget-pkgs) under dapr org
2. Enable `public:repo` scope for `DAPR_BOT_TOKEN`

**Comment by shivamkm07** [comment]
cc @artursouza @mukundansundar

**Comment by artursouza** [comment]
If the goal is to create a fork for PRs, can we get it done in the dapr-bot org itself?

**Comment by shivamkm07** [comment]
> If the goal is to create a fork for PRs, can we get it done in the dapr-bot org itself?

Yes it can. That would be better. Just we need the token with required permissions to create the PR

**Comment by artursouza** [comment]
Fork created in dapr-bot: https://github.com/dapr-bot/winget-pkgs
