### ISSUE TITLE
REQUEST: New membership for ShaileshSurya

### ISSUE THREAD

**Issue by ShaileshSurya** [dapr/community#23]
### GitHub Username

@ShaileshSurya

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project
Have contributed to Dapr Recently. [List Of PR's ](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3AShaileshSurya)
https://github.com/dapr/dapr/pull/1962

### Sponsor 
@yaron2

**Comment by yaron2** [comment]
I support this request.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yaron2** [comment]
Added
