### ISSUE TITLE
Request for 2 sandbox projects for pluggable components

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/community#231]
This request is for migrating two projects to the dapr-sandbox org, containing two pluggable components:

- [dapr-sqlite-statestore](https://github.com/ItalyPaleAle/dapr-sqlite-statestore)
- [dapr-ipfs-binding](https://github.com/hypernova3/dapr-ipfs-binding)

Both these components were originally included in the dapr/components-contrib repo:

- The SQLIte state store was contributed by @lotuc in a PR (dapr/components-contrib#1654) which could not be merged due to a dependency on CGo
- The IPFS binding was contributed by @hypernova3 and was merged into the master tree, but it never shipped with the official Dapr runtime due to a strong performance regression (just embedding the component, without initializing it, increased the memory footprint of the runtime significantly)

1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.

> Both components above are in my opinion great examples of pluggable components and can act as showcases of this new technology that is shipping with Dapr 1.9.
> 
> The SQLite state store has been requested by the community in more than one instance and will arguably be very useful to developers especially during local development. It was contributed by a community member in April and at that time we thought we would ship this as pluggable component instead.
>
> The IPFS binding was already reviewed by the maintainers of components-contrib and was close to being shipped with the runtime. It's a fun one, with some potential use even outside of the "web3" space (e.g. sharing state across multiple instances of daprd in a cluster?).

2. Which programming languages will be used?

> Go

4. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform

> Both depend on Docker and, of course, Dapr. The IPFS one depends on libraries published by the IPFS project (Protocol Labs). The SQLite state store depends on the SQLite library.

6. Enumerate the repositories this project will need to be created.

>

7. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?

> No ETA. These can stay in the sandbox org for the foreseeable future.

8. Who are the maintainers of this project and corresponding employers?

> - SQLite: you can make me (@ItalyPaleAle) as maintainer for now
> - IPFS: @hypernova3 (whom I've been helping making the component available as pluggable). Or, if you need someone who's a member of the Dapr org, you can make me (@ItalyPaleAle) and I'll work with @hypernova3

**Comment by yaron2** [comment]
The Dapr sandbox org is not a good place for pluggable components. This is very evident by the answer to question number 7. All sandbox projects are expected to graduate into the Dapr org at some point. If we accept pluggable components as separate repos into the dapr org, that will result in an unmaintainable proliferation of projects.

As such, I'm inclined to reject this request for now as sandbox doesn't seem to be a good fit. However, I do think there's place to explore accepting pluggable components directly into the dapr org in a mono repo design, not too unsimilar to how the samples repository is maintained, where pluggable components do not require a long term maintainer.

**Comment by ItalyPaleAle** [comment]
I understand. Perhaps we can agree that there would be a plan to graduate them into the Dapr org? Or we could have a separate org for pluggable components?

I am not a big fan of the monorepo approach because one big advantage of pluggable components is that they can have a separate lifecycle from the Dapr runtime's, which would be very cumbersome within a monorepo.

**Comment by ItalyPaleAle** [comment]
I understand. Perhaps we can agree that there would be a plan to graduate them into the Dapr org? Or we could have a separate org for pluggable components?

I am not a big fan of the monorepo approach because one big advantage of pluggable components is that they can have a separate lifecycle from the Dapr runtime's, which would be very cumbersome within a monorepo.

The biggest problem right now IMHO is discoverability. Having the components scattered around GitHub makes it harder to find them, especially at the beginning while the technology is new. Additionally, while the IPFS component is more of a "fun toy", the SQLite one is definitely answering a need from our users.

**Comment by yaron2** [comment]
A separate, single repository under the dapr org would solve both discoverability (in actuality, make it more discoverable than in dapr-sandbox), and allow the pluggable components to exist independently of the dapr runtime.

**Comment by ItalyPaleAle** [comment]
What about the ability to release each component individually? Right now each repo linked above has its own pipeline and own Dockerfile. Given the variety of technologies we expect pluggable components to be written with, I think separate lifecycles would be very beneficial, something hard to achieve with a monorepo.

**Comment by yaron2** [comment]
> What about the ability to release each component individually? Right now each repo linked above has its own pipeline and own Dockerfile. Given the variety of technologies we expect pluggable components to be written with, I think separate lifecycles would be very beneficial, something hard to achieve with a monorepo.

Pluggable components shouldn't be released, by their very nature they should be consumed as a binary or built into a container by users. Releasing pluggable components comes with many responsibilities and very little actual benefits. Even then, a monorepo can offer independent lifecycles for each component.

**Comment by ItalyPaleAle** [comment]
What's the recommended way to consume them?

Right now the two repos above include Docker containers published via Actions, so the components can be consumed on K8s or a Docker cluster. Is that not recommended?

**Comment by ItalyPaleAle** [comment]
Ok, I see no problem with the repos above publishing the Docker images on GHCR then. Helps removing friction so they're ready to be consumed.

**Comment by yaron2** [comment]
> Ok, I see no problem with the repos above publishing the Docker images on GHCR then. Helps removing friction so they're ready to be consumed.

I don't think it's necessary but don't see a problem with it

**Comment by yaron2** [comment]
Closing this as a sandbox proposal. I will bring this up in the next STC meeting to examine how we can accept pluggable components contributions.
