### ISSUE TITLE
Request for new sandbox project: spring-cloud-dapr

### ISSUE THREAD

**Issue by skyao** [dapr/community#232]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.

> Make spring cloud user easy to use dapr.
> (Almost) No code change for the developer to migrate spring cloud apps into dapr. 
> Make spring cloud apps lightweigh and suitable for serverless / function computing
> Help spring cloud apps to be Java AOT and especially suitable for serverless / function computing

2. Which programming languages will be used?

> Java.

3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform

> Spring cloud and spring boot/spring framework.

4. Enumerate the repositories this project will need to be created.

> spring-cloud-dapr

5. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?

> In 6 or 12 months (depends on the scope of integrated spring cloud subprojects) 

6. Who are the maintainers of this project and corresponding employers?

> Xiaojian Ao from microsoft. 

7. others

> This is already a project in my personal repo and waiting for PR: https://github.com/skyao/spring-cloud-dapr
> The proposal for this project:  https://github.com/dapr/dapr/issues/5196

**Comment by artursouza** [comment]
I approve this request.

**Comment by paulyuk** [comment]
I approve this.  I'm excited to see members of spring community and dapr working together on this sandbox project.

**Comment by msfussell** [comment]
I approve this request.

**Comment by yaron2** [comment]
Supportive.

**Comment by artursouza** [comment]
Done: https://github.com/dapr-sandbox/spring-cloud-dapr
