### ISSUE TITLE
REQUEST: New membership for akhilac1

### ISSUE THREAD

**Issue by akhilac1** [dapr/community#233]
### GitHub Username

@akhilac1

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  - https://github.com/dapr/components-contrib/pull/2063
  - https://github.com/dapr/dapr/pull/5255
  - https://github.com/dapr/dapr/pull/5250
  - https://github.com/dapr/dapr/pull/5153
  - https://github.com/dapr/docs/pull/2800
  - https://github.com/dapr/quickstarts/pull/685
  - https://github.com/dapr/dapr/issues/4760
  - https://github.com/dapr/quickstarts/pull/675
  
- Issues responded to
  - https://github.com/dapr/dapr/issues/5236
  - https://github.com/dapr/quickstarts/pull/683
  - https://github.com/dapr/dapr/issues/4912
  - https://github.com/dapr/dapr/issues/5183

**Comment by akhilac1** [comment]
@artursouza  @mukundansundar @shubham1172 - please approve

**Comment by shubham1172** [comment]
+1, I support this request.

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
@akhilac1 see invitation in your e-mail's inbox to join Dapr org.
