### ISSUE TITLE
Document the Dapr release lifecycle

### ISSUE THREAD

**Issue by greenie-msft** [dapr/community#236]
There should be a formal documented process that all Dapr releases conform to. This document is critical for driving clarity and setting release expectations. It also helps provide guidance on how the community can get started participating in a Dapr release. 

The process should include:
- Release cycle - timeline of events (planning, execution, endgame)
- Roles involved for coordinating a release
- Communication & meetings throughout a release

**Comment by greenie-msft** [comment]
PR: https://github.com/dapr/community/pull/235

**Comment by msfussell** [comment]
Resolved
