### ISSUE TITLE
REQUEST: New membership for yittg

### ISSUE THREAD

**Issue by yittg** [dapr/community#24]
### GitHub Username

@yittg

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [PRs reviewed / authored](https://github.com/pulls?q=org%3Adapr+is%3Apr+involves%3Ayittg)
- [Issues responded to](https://github.com/issues?q=org%3Adapr+is%3Aissue+involves%3Ayittg)

/cc @yaron2

**Comment by yaron2** [comment]
I support this request.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yittg** [comment]
@yaron2 thanks
