### ISSUE TITLE
REQUEST: New membership for @nyemade-uversky

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/community#243]
### GitHub Username

@nyemade-uversky

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

**PRs reviewed / authored**
- https://github.com/dapr/docs/pull/2469 
- https://github.com/dapr/docs/pull/2593
- https://github.com/dapr/docs/pull/2657
- https://github.com/dapr/docs/pull/2688
- https://github.com/dapr/dapr/pull/5153
- https://github.com/dapr/dapr/pull/5158
- https://github.com/dapr/docs/pull/2575
- https://github.com/dapr/docs/pull/2672
- https://github.com/dapr/docs/pull/2691
- https://github.com/dapr/docs/pull/2419

**Issues responded to**
- https://github.com/dapr/docs/issues/2799
- https://github.com/dapr/docs/issues/1727
- https://github.com/dapr/docs/issues/2420
- https://github.com/dapr/docs/issues/2799
- https://github.com/dapr/quickstarts/issues/733
- https://github.com/dapr/dapr/issues/5373

**Sponsorship:**
@greenie-msft , @msfussell, @yaron2 , @paulyuk

**Comment by msfussell** [comment]
I support this request for the community repo.
👍

**Comment by artursouza** [comment]
Done.
