### ISSUE TITLE
REQUEST: Approver status for @nyemade-uversky for community repo

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/community#244]
### GitHub Username

@nyemade-uversky 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories
​
### List of contributions to the Dapr project
​
**PRs reviewed / authored**
- https://github.com/dapr/community/pull/198
- https://github.com/dapr/community/pull/216
- https://github.com/dapr/community/pull/224
- https://github.com/dapr/community/pull/228
- https://github.com/dapr/community/pull/235
- https://github.com/dapr/community/pull/216
- https://github.com/dapr/community/pull/196
- https://github.com/dapr/community/pull/241
- https://github.com/dapr/community/pull/239

​

**Issues responded to**
- https://github.com/dapr/community/issues/210
- https://github.com/dapr/community/issues/211
- https://github.com/dapr/community/issues/213
- https://github.com/dapr/community/issues/200
- https://github.com/dapr/community/issues/199
- https://github.com/dapr/community/issues/242
- https://github.com/dapr/community/issues/240
​
**​Sponsorship**
@paulyuk @msfussell @artursouza @greenie-msft @yaron2 @berndverst

**Comment by msfussell** [comment]
I support this request.
👍

**Comment by greenie-msft** [comment]
👍

**Comment by berndverst** [comment]
👍

**Comment by shubham1172** [comment]
👍🏻

**Comment by paulyuk** [comment]
👍🏻

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
DOne.
