### ISSUE TITLE
REQUEST: New membership for @tmacam

### ISSUE THREAD

**Issue by tmacam** [dapr/community#246]
### GitHub Username

`@tmacam`

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

#### PRs reviewed / authored

dapr
* https://github.com/dapr/dapr/pull/5208
* https://github.com/dapr/dapr/pull/5052
* https://github.com/dapr/dapr/pull/5039
* https://github.com/dapr/dapr/pull/4989

components-contrib
* https://github.com/dapr/components-contrib/pull/2140
* https://github.com/dapr/components-contrib/pull/2116
* https://github.com/dapr/components-contrib/pull/2069
* https://github.com/dapr/components-contrib/pull/2031
* https://github.com/dapr/components-contrib/pull/1958

docs
* https://github.com/dapr/docs/pull/2898
* https://github.com/dapr/docs/pull/2891
* https://github.com/dapr/docs/pull/2885
* https://github.com/dapr/docs/pull/2863
* https://github.com/dapr/docs/pull/2856
* https://github.com/dapr/docs/pull/2836

go-sdk
* https://github.com/dapr/go-sdk/pull/329

dotnet-sdk
* https://github.com/dapr/dotnet-sdk/pull/924

python-sdk
* https://github.com/dapr/python-sdk/pull/450
* https://github.com/dapr/python-sdk/pull/446
* https://github.com/dapr/python-sdk/pull/442
* https://github.com/dapr/python-sdk/pull/434
* https://github.com/dapr/python-sdk/pull/431

js-sdk
* https://github.com/dapr/js-sdk/pull/337

#### Issues responded to

dapr
* https://github.com/dapr/dapr/issues/5211
* https://github.com/dapr/dapr/issues/5051
* https://github.com/dapr/dapr/issues/5038
* https://github.com/dapr/dapr/issues/4988

components-contrib
* https://github.com/dapr/components-contrib/issues/2142
* https://github.com/dapr/components-contrib/issues/2117
* https://github.com/dapr/components-contrib/issues/2047
* https://github.com/dapr/components-contrib/issues/1950
* https://github.com/dapr/components-contrib/issues/1929
* https://github.com/dapr/components-contrib/issues/1926

docs
* https://github.com/dapr/docs/issues/2897
* https://github.com/dapr/docs/issues/2857
* https://github.com/dapr/docs/issues/2835
* https://github.com/dapr/docs/issues/2820
* https://github.com/dapr/docs/issues/2787
* https://github.com/dapr/docs/issues/2786
* https://github.com/dapr/docs/issues/2600

community
* https://github.com/dapr/community/issues/209

dotnet-sdk
* https://github.com/dapr/dotnet-sdk/issues/921

python-sdk
* https://github.com/dapr/python-sdk/issues/445
* https://github.com/dapr/python-sdk/issues/440
* https://github.com/dapr/python-sdk/issues/433

js-sdk
* https://github.com/dapr/js-sdk/issues/336

**Comment by tmacam** [comment]
Note to future self:

```shell
for repo in dapr components-contrib docs community go-sdk dotnet-sdk java-sdk python-sdk js-sdk cli; do
 echo ""
 echo $repo; 
 gh api -X GET search/issues -f q='repo:dapr/'$repo' author:tmacam' --jq '.items[] | .html_url' | sed -e 's#^#* #' ; sleep 1;
done
```

**Comment by artursouza** [comment]
Done.

**Comment by tmacam** [comment]
For the fututure, those queries should be modified as I only listed the issues and PRs I opened. To inclued the rest the query in that command above should be updated to the following:

* Only PRs authored by me: `repo:dapr/$repo is:pr author:tmacam`
* Only PRs reviewed but not created by me : `repo:dapr/$repo is:pr -author:tmacam involves:tmacam`
* Any issues assigned, commended or created by me (outside a PR): `repo:dapr/$repo -is:pr involves:tmacam`

**Comment by tmacam** [comment]
I used the following script to generate the above:


```shell
#!/bin/bash

DAPR_REPOS=( dapr components-contrib docs community go-sdk dotnet-sdk java-sdk python-sdk js-sdk cli )

GH_USERNAME=tmacam

PRS_AUTHORED="is:pr author:${GH_USERNAME}"
PRS_INVOLVED="is:pr -author:${GH_USERNAME} involves:${GH_USERNAME}"
ISSUES_AUTHORED="is:issue author:${GH_USERNAME}"
ISSUES_INVOLVED="is:issue -author:${GH_USERNAME} involves:${GH_USERNAME}"

function searchRepos() {
    local header=$1
    local issues_selector=$2

    echo -e "#### $header\n"

    for repo in "${DAPR_REPOS[@]}" ; do
        local repo_selector="repo:dapr/$repo"
        local query="$repo_selector $issues_selector"
        echo -e "* $repo"; 
        gh api -X GET search/issues -f q="$repo_query $query" --jq '.items[] | .html_url' | sed -e 's#^#    * #' ; 
        sleep 2; 
    done

    echo ""
}

searchRepos "PRs Authored" "$PRS_AUTHORED"
searchRepos "PRs Reviewed" "$PRS_INVOLVED"
searchRepos "Issues Opened" "$ISSUES_AUTHORED"
searchRepos "Issues responded" "$ISSUES_INVOLVED"
```
