### ISSUE TITLE
Request: `dapr/kit` maintainers / approvers should inherit from `contrib` and `dapr/dapr` roles

### ISSUE THREAD

**Issue by berndverst** [dapr/community#248]
# Background

`dapr/kit` used to be code inside contrib and runtime but was refactored into its own repo for code sharing.

# Justification
This is heavily used by contrib and runtime, but we currently do not have maintainers for this repo.

To enable easy code reuse and consistency across runtime and contrib we need maintainers and approvers for this repo.

There are simply not enough changes made to this repo to justify a completely separate maintainership process. Additionally, it would require too much coordination with runtime and contrib maintainers. For this reason it is best to give control to maintainers of runtime and contrib.

# Request
I propose that `dapr/kit` maintainers will be: @dapr/maintainers-dapr and @dapr/maintainers-components-contrib 
And approvers will be: @dapr/approvers-dapr and @dapr/approvers-components-contrib

**Comment by berndverst** [comment]
cc @dapr/steering-and-technical-committee

**Comment by skyao** [comment]
Agree!

**Comment by artursouza** [comment]
Agree.

**Comment by yaron2** [comment]
+1

**Comment by artursouza** [comment]
Done:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/130954/202770276-a4315920-da5f-42ec-9cc9-ef3cfd3d7228.png">

**Comment by artursouza** [comment]
Clarifying that this issue also approved removing approvers-kit and maintainers-kit. It will only affect @pkedy since he will not be maintainer anymore after this change.
