### ISSUE TITLE
REQUEST: New membership for @skyao

### ISSUE THREAD

**Issue by skyao** [dapr/community#25]
### GitHub Username

Sky Ao - @skyao

I'm working for Alibaba / Alicloud, we are now trying to migrate Dapr onto Alicloud.

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [PRs in dapr/dapr](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3Askyao)
- [PRs in dapr/go-sdk](https://github.com/dapr/go-sdk/pulls?q=is%3Apr+author%3Askyao+is%3Aclosed)
- [PRs in dapr/components-contrib](https://github.com/dapr/components-contrib/pulls/skyao)

### Related contributions

- [PR in etcd to upgrade to new grpc version](https://github.com/etcd-io/etcd/pull/12398): so later we can add etcd state store back. Discussion is [here](https://github.com/etcd-io/etcd/issues/12124) 

### Sponsors

@yaron2

**Comment by mchmarny** [comment]
+1 from me for the dapr/go-sdk contributions

**Comment by yaron2** [comment]
I support this request.

**Comment by yaron2** [comment]
Your membership has been approved, looks out for a GitHub invite to join the members team on the Dapr org.

**Comment by yaron2** [comment]
Added
