### ISSUE TITLE
10th Nov 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#250]
Nov 2022 STC meeting.

Proposed Agenda will be update based on email feedback and community raised issues

STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@artursouza (Microsoft)
@jackzhao (Alibaba)
@cvictory (Alibaba)
@Forrest-zhao (Intel)
@paulyuk (Microsoft)

Previous Oct meeting notes https://github.com/dapr/community/issues/218

# Action items from previous meetings
1) Action: @msfussell - Update the documentation. Update the cadence for security reviews and releases.  docs [#2795](https://github.com/dapr/docs/issues/2795)

# Nov 2022 STC  Agenda
1) @artursouza  -  https://github.com/dapr/community/issues/223
Approved. STC voted that this can be moved into an Azure repo. 
2) @artursouza  - https://github.com/dapr/community/issues/222
Approved. STC voted to create this as a project
3) Discuss this new sandbox project proposal https://github.com/dapr/community/issues/221
Approved. STC voted to create this as a project. See https://github.com/dapr-sandbox/haskell-sdk
4) Agreed next STC meeting Wed 14th Dec 2022

**Comment by paulyuk** [comment]
I suggest we discuss pros and cons with this year's DaprCon format and impact, and discuss any changes we want to try for next year.

**Comment by msfussell** [comment]
@paulyuk - we can, however this is very NA specific

> I suggest we discuss pros and cons with this year's DaprCon format and impact, and discuss any changes we want to try for next year.

@paulyuk - we can, however this is very NA specific

**Comment by paulyuk** [comment]
I'm of split mind. We are the WW STC so it might be good to generalize what we learned from it on NA side

**Comment by msfussell** [comment]
Resolved
