### ISSUE TITLE
Dec 2022 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#251]
#Dec 2022 STC meeting.

Agenda and notes update Dec 15th 2022

STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@artursouza (Microsoft)
@cvictory (Alibaba)
@paulyuk (Microsoft)

Absent (vacation)
@Forrest-zhao (Intel)
@jackzhao (Alibaba)

Previous Nov meeting notes https://github.com/dapr/community/issues/250

## Action items from previous meetings
Notes from Nov 2022 meeting https://github.com/dapr/community/issues/250

## Dec 2022 Agenda
1)  Discuss 2023 Objectives and Goals for the Dapr project - @msfussell 

@msfussell  presented proposed goals for the Dapr project in 2023 for STC to review and agree on on the Jan 2023 STC meeting sync. STC agreed that this was the correct first set to consider. These are:

**Increase enterprise confidence** 
- Stabilize all current AWS and GCP Components, starting 1.10.0
- Stabilize: 
- Resiliency policies (1.10.0), 
- Configuration API (1.11.0)
- Pluggable components (1.12.0)
- Distributed lock API (1.13.0)
- E2E tests passing at 80% rate on Azure, GCP and AWS
- Longhaul environments on AWS and GCP

**Introduce workflow API (1.10.0)**
- Brings Dapr into mainstream business application workflow development space
- Goal to stabilize workflow API for 1.13.0

**Invest in community building**	
- Grow Dapr to 3.2k Contributors, 8k Discord members and 26k Github stars
            - End 2021 - 1.48k Contributors, 3.5k Discord, 15.1k Github stars
            - End 2022 - 2.3k Contributors, 5.1k Discord, 20k Github stars
- Make Dapr the 7th largest project in CNCF and increase visibility at CNCF events
- Publish 3 more case studies
- Hold two-day DaprCon 2023 in Q3 in North America

**Add maintainer/approvers**
**Grow the STC to 9 members**

2) Tools to gain deeper insights into who is using Dapr project - @msfussell 
@msfussell proposed using trials for 
- Common Room (https://www.commonroom.io/ ) which gives insights from Discord, Github and Twitter into the users
- Scarf (https://about.scarf.sh/) a platform for download and adoption metrics for open source software projects. Used by Linkerd, and other CNCF projects. This would be used on the dapr.io and docs website. 

These would provide insights to the Dapr OSS project to enable to grow and support the community better. STC Approved to enable these tools as trials and see the information they provide. 

3) I would like to share a proposal for the administrator role: https://github.com/dapr/community/issues/264 - @artursouza
The STC Approved this issue. @artursouza  to update the STC Charter document.

**Comment by msfussell** [comment]
Two topics I would like to add to the agenda:

1) Discuss 2023 Objectives and Goals for the Dapr project? Where would we like to be in 1 year's time and what do we track?
2) Ways to get better insights into who is using Dapr project. 
 - Two tools that have been recommended are https://www.commonroom.io/ and https://about.scarf.sh/ which can provide deeper community engagements.

**Comment by artursouza** [comment]
I would like to share a proposal for the `administrator` role: https://github.com/dapr/community/issues/264

**Comment by paulyuk** [comment]
Hello could someone pls resend invite to me ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msfussell** [comment]
Meeting held with notes recorded.
