### ISSUE TITLE
December 14th, Community Meeting Agenda

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/community#255]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Wednesday, December 14th, at 9am PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
Host: @msfussell

**Comment by sarsharma** [comment]
Hello, I would like to get a few minutes to present Quickstarts for Configuration API https://github.com/dapr/quickstarts/pull/743

**Comment by ItalyPaleAle** [comment]
I can present about some new security things added between 1.9 and 1.10 for Dapr in K8s:

- automountServiceAccountToken = false
- runAsRoot = false
- readOnlyFileSystem = true

As well as the consequences of those :)

I won’t need more than 5 mins

**Comment by yaron2** [comment]
I'll present on "Multi-tenant Dapr on K8s with VCluster".

Should take ~15m.

**Comment by olitomlinson** [comment]
Happy to do a little Show & Tell on what I did with a [pluggable State Store](https://github.com/olitomlinson/tenant-aware-dapr-pluggable-state-store)

5-10 minutes, but I can be more brief if needed.

**Comment by nyemade-uversky** [comment]
@olitomlinson sounds good! I'll add you to the schedule for tomorrow.

**Comment by msfussell** [comment]
Delivered
