### ISSUE TITLE
REQUEST: New membership for RyanLettieri

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/community#257]
### GitHub Username

(at)RyanLettieri

### Requirements

- [x ] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x ] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [ x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
- https://github.com/dapr/dapr/pull/5158
- https://github.com/dapr/components-contrib/pull/2035
- Issues responded to

### Sponsors
@artursouza

**Comment by berndverst** [comment]
There are several other PRs from Ryan in flight and I have collaborated with him.

I support this.

**Comment by artursouza** [comment]
I confirm my sponsorship.

**Comment by artursouza** [comment]
@ RyanLettieri - see invite in your e-mail's inbox.
