### ISSUE TITLE
REQUEST: @berndverst as approver in dapr/dapr

### ISSUE THREAD

**Issue by artursouza** [dapr/community#259]
### GitHub Username

@berndverst as approver in dapr/dapr

PRs:
https://github.com/dapr/dapr/pulls?q=author%3Aberndverst+ (Total: 98)

Highlights:
https://github.com/dapr/dapr/pull/5516
https://github.com/dapr/dapr/pull/5503
https://github.com/dapr/dapr/pull/5041
https://github.com/dapr/dapr/pull/5018
https://github.com/dapr/dapr/pull/4864
https://github.com/dapr/dapr/pull/4329
https://github.com/dapr/dapr/pull/4328
https://github.com/dapr/dapr/pull/4299
https://github.com/dapr/dapr/pull/3684
https://github.com/dapr/dapr/pull/3373

PRs reviewed: https://github.com/dapr/dapr/pulls?q=-author%3Aberndverst+involves%3Aberndverst (Total: 89)

Issues created: https://github.com/dapr/dapr/issues?q=is%3Aissue+author%3Aberndverst+

Issues from others contributed to: https://github.com/dapr/dapr/issues?q=is%3Aissue+-author%3Aberndverst+involves%3Aberndverst (Total: 49)

Sponsor: @artursouza

**Comment by yaron2** [comment]
+1

**Comment by shubham1172** [comment]
+1

**Comment by berndverst** [comment]
@daixiang0 would you be willing to support this? 🙂

**Comment by mukundansundar** [comment]
+1
