### ISSUE TITLE
REQUEST: New membership for @XavierGeerinck

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/community#26]
### GitHub Username

@XavierGeerinck

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

* Issues
    * https://github.com/dapr/dapr/issues/843
    * https://github.com/dapr/dapr/issues/1833
* Blog posts
    * https://xaviergeerinck.com/post/dapr/kafka-bindings/
    * https://xaviergeerinck.com/post/iot/digital-twin-dapr/
    * https://xaviergeerinck.com/post/dapr/creating-account-microservice/
    * https://xaviergeerinck.com/post/dapr/getting-started/
    * More coming soon ;)

**Comment by yaron2** [comment]
I support this request.

**Comment by msfussell** [comment]
I support this request

**Comment by yaron2** [comment]
@XavierGeerinck you have been added. look out for a GitHub invite.

**Comment by youngbupark** [comment]
+1 I support this request too :)
