### ISSUE TITLE
New role in Dapr's governance: `administrator`

### ISSUE THREAD

**Issue by artursouza** [dapr/community#264]
In addition to approver, maintainer and STC members, I propose Dapr to have the `administrator` role. This role is designed for some of the maintainers to have full access to credentials in 1Password and execute on decisions done by the STC and keep up with day-to-day operational burden within the guidance of the STC BUT without making any decision on behalf of the STC.

The process I propose would be for any maintainer to self nominate as an administrator via an issue in dapr/community and add that to the next STC meeting's agenda. The STC will then vote and it would require a 3/5 majority for the person to be nominated as an administrator. The administrator role must be renewed every 6 months, following the same process.

At any moment, any STC member can temporarily suspend administrator access from any individual, for any reason, without requiring an STC meeting for so - this will enable de-risking situations where there is misuse of the power or suspicion of leaked credentials. Reinstating administrator access follows the same process as requesting it for the first time.

Since being a maintainer is a pre-requisite to be an administrator, dropping from the maintainer role automatically removes the administrator role.

To minimize the number of people with access to credentials, there might be up to 3 administrators at a given time. Adding a forth administrator automatically requires one current administrator to removed permanently. Removing an active or suspended administrator prior to the end of the 6-month term requires a 3/5 majority by STC as well.

**Comment by artursouza** [comment]
The STC should also come up with a list of things that the administrator are allowed and not allowed to do. Although it is not possible to have a comprehensive list, it will avoid confusion in most cases. For example:

Allowed autonomy:
* Rotate existing credentials
* Update existing credentials on GitHub
* Rerun failed test runs
* Provision cloud resources

Requires approval from one STC member:
* Force merge pull request
* Create project in sandbox
* Sign up to a new paid service or cloud provider

When in doubt, ask an STC member.

**Comment by tanvigour** [comment]
This would be great! We have had many blockers at times with as simple as being able to add a secret to a repo without STC member around in the past, this should reduce such blockers.

**Comment by yaron2** [comment]
STC voted to approve this proposal. @artursouza to follow up with documentation and procedure.

**Comment by berndverst** [comment]
This would help me so much for contrib and Python SDK. Amazing! Didn't even know this proposal was happening!

**Comment by msfussell** [comment]
Closed with this PR https://github.com/dapr/community/pull/269
