### ISSUE TITLE
Jan 2023 : Steering and Technical Committee (STC) Agenda 

### ISSUE THREAD

**Issue by msfussell** [dapr/community#265]
# Jan 2023 STC meeting.

STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@artursouza (Microsoft)
@cvictory (Alibaba)
@paulyuk (Microsoft)
@Forrest-zhao (Intel)

Absent
@jackzhao (Alibaba)

Previous Dec 2022 meeting notes https://github.com/dapr/community/issues/251

## Action items from previous meetings
@msfussell - Follow up on proposed Dapr project 2023 priorities

## Agenda
1) Update on Arthur and voting his role as administrator - https://github.com/dapr/community/issues/273. 
 - See role details here https://github.com/dapr/community/blob/master/ADMINISTRATORS.md

    - @artursouza is stepping down from the STC and Microsoft will announce a replacement person before the next STC meeting in Feb 2023. Thank you Artur for your tremendous contributions.
     - The STC unanimously voted to make @artursouza a Dapr project Administrator (see link above) starting immediately. 

2) Feedback on the priorities for Dapr project 2023? See Dec 2022 meeting notes
    - @msfussell - Revisited the goals for the Dapr project in 2023. The STC reviewed and acknowledge the STC goals for 2023 and will revisit these again in 6 months. STC agreed that growing the STC membership and inclusiveness is a high priority.

3) Common Room (https://www.commonroom.io/ ) which gives insights from Discord, Github and Twitter into the users
and Scarf (https://about.scarf.sh/) on Dapr Website/docs have been set up for Dapr. 
    - @msfussell showed these two community tools and how they are useful to understand the Dapr community more. 
    - @msfussell added the STC members to both CommonRoom app https://app.commonroom.io/community/2474-dapr/home. and to Scarf (https://app.scarf.sh/home/Dapr) as owners. As owners in these tools the STC are empowered to invite others who you feel a need access to the data.

**Comment by artursouza** [comment]
https://github.com/dapr/community/issues/266

**Comment by msfussell** [comment]
Resolved
