### ISSUE TITLE
Maintainers to have Admin rights to their respective repos

### ISSUE THREAD

**Issue by berndverst** [dapr/community#266]
This is a request for maintainers to have admin rights to the specific repos of which they are maintainers.

For example, I would personally receive admin rights only to components-contrib, kit, python-sdk.

Why? Maintainers should be able to:
- Have the ability to configure and update which tests are required for the repo.
- Add repo specific secrets if necessary.
- Force merge PRs. For example in contrib we constantly need to address `go.mod` conflicts which triggers 70 tests to run, but at that time it is already known the PR will pass all tests and can be force merged. This would save a lot of maintainer time!

**Comment by berndverst** [comment]
Here is an example why I need this from a contrib perspective:

The conformance test workflow was broken when this PR was created https://github.com/dapr/components-contrib/pull/2365. As a result the required tests are not running and this PR is stuck. As a maintainer I cannot get this PR unstuck as I do not have admin rights.

**Comment by yaron2** [comment]
Approved by STC.

**Comment by berndverst** [comment]
@yaron2 can you assign me admin access for Python SDK also please? Thanks!
