### ISSUE TITLE
REQUEST: New membership for @gbaeke

### ISSUE THREAD

**Issue by gbaeke** [dapr/community#27]
### GitHub Username

@gbaeke

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

* InfluxDB binding: https://github.com/dapr/components-contrib/commit/467375c254e097adfae4599509927647532be88b

- Videos
  - Techtrain talk: https://youtu.be/MjyulcRqh20
  - Full Dapr playlist on Youtube channel: https://www.youtube.com/playlist?list=PLG9qZAczREKnLb3O0H1T7hfcHlOe8NlRM

- Blog posts
  - From MQTT to InfluxDB with Dapr: https://blog.baeke.info/2020/08/22/from-mqtt-to-influxdb-with-dapr/
  - Using the Dapr InfluxDB binding: https://blog.baeke.info/2020/08/21/using-the-dapr-influxdb-component/
  - Service invocation between HTTP Python client and GRPC Go server: https://blog.baeke.info/2020/07/17/dapr-service-invocation-between-an-http-python-client-and-a-grpc-go-server/

**Comment by yaron2** [comment]
I support this request.

**Comment by mchmarny** [comment]
I support this request.

**Comment by yaron2** [comment]
@gbaeke you have been added to the Dapr org. Look out for a GitHub invite.

**Comment by yaron2** [comment]
Added
