### ISSUE TITLE
Add `artursouza` as Administrator

### ISSUE THREAD

**Issue by artursouza** [dapr/community#273]
As per new rules defined in https://github.com/dapr/community/blob/master/ADMINISTRATORS.md, I would like to self-nominate as an administrator of Dapr project.

I am currently a maintainer of dapr/dapr, dapr/components-contrib, dapr/java-sdk and dapr/dashboard

UPDATE: This request is bundled with my removal from STC given my (soon) change of employment would cause one company to exceed the 2 seats limit.

**Comment by yaron2** [comment]
Thanks, this will be voted on in today's STC meeting.
Added to agenda [here](https://github.com/dapr/community/issues/265).

**Comment by msfussell** [comment]
As per the STC meeting https://github.com/dapr/community/issues/265  @artursouza is now an administor.
@artursouza - Please submit a PR to update the role document.
