### ISSUE TITLE
Feb 8th, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#276]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Wednesday Feb 8th, at 9:00am  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
- Thomas Kunnumpurath (Solace.com engineering) can present on the Dapr AMQP-Solace component and  how Dapr  is used Solace products and communities

**Comment by yaron2** [comment]
I will talk about Apache Pulsar schema validation in 1.10 - 5 minutes.

**Comment by DeepanshuA** [comment]
I will be talking about Bulk PubSub APIs coming up with Dapr v1.10

**Comment by msfussell** [comment]
Delivered
