### ISSUE TITLE
March 8th, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#278]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on Wednesday March 8th, at 9:00am  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by salaboy** [comment]
- I want to present about Knative Functions and Dapr on this meetup, is that possible?

**Comment by msfussell** [comment]
> * I want to present about Knative Functions and Dapr on this meetup, is that possible?

Yes, of course. I will be hosting this event.

**Comment by marcduiker** [comment]
The presentation by @salaboy is moved to the Community call of 22nd Mar.

**Comment by JoshVanL** [comment]
I would like to present a controller I wrote which integrates cert-manager with dapr. This controller is intended as an interim before better first class support it added.

**Comment by filintod** [comment]
Thinking on doing presentation on using [kwok](https://kwok.sigs.k8s.io/) for testing the dapr operator memory consumption. Not directly related to dapr but used during load testing of a PR to reduce memory consumption of the operator with large clusters, but could also be used in other parts to check dapr operators scalability.

**Comment by nyemade-uversky** [comment]
@JoshVanL would you be able to message me in discord so I can share a link to the slide deck we'll use for the call? My discord handle is nuversky#2099
