### ISSUE TITLE
[WIP] REQUEST: New membership for @MChorfa

### ISSUE THREAD

**Issue by MChorfa** [dapr/community#28]
### GitHub Username
@MChorfa

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed/authored
Not yet. But planning to :)
- Issues opened
https://github.com/dapr/generator-dapr/issues/20

PS: It can wait until submitting concrete PR's, docs 

Thanks

**Comment by yaron2** [comment]
Hi @MChorfa, thanks for opening this request. We'd love to have you in the Dapr org, and as you've said we would need to see more commenting on issues or PRs.
