### ISSUE TITLE
REQUEST: New membership for mcandeia

### ISSUE THREAD

**Issue by mcandeia** [dapr/community#282]
### GitHub Username

(at)mcandeia

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/dapr/pull/5132
https://github.com/dapr/dapr/pull/5102
https://github.com/dapr/dapr/pull/5262
https://github.com/dapr/dapr/pull/5514

- Issues responded to
https://github.com/dapr/dapr/issues/5575
https://github.com/dapr/dapr/issues/5858

**Comment by yaron2** [comment]
I support the membership.

**Comment by artursouza** [comment]
I approve.
