### ISSUE TITLE
REQUEST: New membership for robertojrojas

### ISSUE THREAD

**Issue by robertojrojas** [dapr/community#285]
### GitHub Username

[robertojrojas](https://github.com/robertojrojas)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  **dapr/components-contrib**
https://github.com/dapr/components-contrib/pull/42
https://github.com/dapr/components-contrib/pull/94
https://github.com/dapr/components-contrib/pull/2426
https://github.com/dapr/components-contrib/pull/2434
https://github.com/dapr/components-contrib/pull/2436
https://github.com/dapr/components-contrib/pull/2481
https://github.com/dapr/docs/pull/3038
https://github.com/dapr/docs/pull/3052
https://github.com/dapr/rust-sdk/pull/88
https://github.com/dapr/rust-sdk/pull/89
https://github.com/dapr/quickstarts/pull/800

- Issues responded to
https://github.com/dapr/dapr/issues/5798
https://github.com/dapr/components-contrib/issues/8
https://github.com/dapr/components-contrib/issues/41
https://github.com/dapr/components-contrib/issues/1062
https://github.com/dapr/components-contrib/issues/2402

**Comment by msfussell** [comment]
I support the request

**Comment by yaron2** [comment]
Done!
