### ISSUE TITLE
REQUEST: New membership for @beiwei30

### ISSUE THREAD

**Issue by beiwei30** [dapr/community#29]
### GitHub Username

@beiwei30

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored

https://github.com/dapr/dapr/pull/2268
https://github.com/dapr/dapr/pull/2253
https://github.com/dapr/dapr/pull/2251
https://github.com/dapr/dapr/pull/2137

- Issues responded to

https://github.com/dapr/dapr/issues/2163

**Comment by yaron2** [comment]
I support this request.

/cc @youngbupark

**Comment by youngbupark** [comment]
I support this request too.

**Comment by yaron2** [comment]
Added
