### ISSUE TITLE
March 2023 : Steering and Technical Committee (STC) Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#290]
# March 2023 STC meeting.
STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@paulyuk (Microsoft)
@cvictory (Alibaba)
@jackzhao (Alibaba)
@Forrest-zhao (Intel)

Absent
@johnewart (Microsoft)

Previous Feb 2023 https://github.com/dapr/community/issues/275 meeting notes

## Action items from previous meetings
- Follow up on the progress of the health metrics for the community

## Agenda and Notes

1) @yaron2 - Dapr Ambient Sandbox proposal - Yaron presented on having [Dapr Ambient](https://github.com/dapr-sandbox/dapr-ambient) be included into the Dapr Sandbox org. There was unanimous agreement that this could be beneficial to Dapr project

2) @paulyuk - Action: Raised topic of having health metrics for the community and took action to come up with a plan. Paul presented the following plan https://github.com/dapr/community/issues/295. Some of the main feedback was ensuring this was measured on a regular basis tracked through the year, understanding how the CNCF measured its velocity report and also empowering advocates to present on Dapr with a "Dapr presentation toolkit". STC members all agreed that this would be very useful to track again the 2023 project goals.

Next STC will be held on 6th April 2023.

**Comment by paulyuk** [comment]
@paulyuk - Action: Raised topic of having health metrics for the community and took action to come up with a plan.

I am ready to share this proposal today:
https://github.com/dapr/community/issues/295

@paulyuk - Suggested holding smaller local events resulting in a discussion on having a "Dapr event presentation in a box" to aid local event speakers to more easily demonstrate Dapr. Action: @paulyuk to look into proposal for this

I need more time to refine this plan, hopefully with at least one tangible event plan as a pilot.
