### ISSUE TITLE
REQUEST: New membership for @joshvanl

### ISSUE THREAD

**Issue by JoshVanL** [dapr/community#292]
### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- https://github.com/dapr/dapr/issues/3968
- https://github.com/dapr/dapr/pull/5774
- https://github.com/dapr/dapr/issues/5756
- https://github.com/dapr/dapr/pull/5767
- https://github.com/dapr/dapr/pull/5831
- https://github.com/dapr/dapr/issues/5958
- https://github.com/dapr/dapr/issues/5922
- https://github.com/dapr/components-contrib/pull/2535
- https://github.com/dapr/components-contrib/pull/2474
- https://github.com/dapr/components-contrib/pull/2500
- https://github.com/dapr/go-sdk/pull/358

**Comment by JoshVanL** [comment]
cc @ItalyPaleAle @yaron2 @artursouza

**Comment by yaron2** [comment]
I approve this request

**Comment by ItalyPaleAle** [comment]
LGTM 🚀

**Comment by artursouza** [comment]
I approve.

**Comment by artursouza** [comment]
@JoshVanL, you should have received an invite from GitHub to join the Dapr org.
