### ISSUE TITLE
Request for new sandbox project: dapr-ambient

### ISSUE THREAD

**Issue by salaboy** [dapr/community#294]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.
>

`Dapr Ambient` will enable Dapr users to use the Dapr Components functionality by relying on a different deployment strategy that doesn't use sidecars and the sidecar injector. 

`Dapr Ambient` provides the `daprd` functionality as a Kubernetes DeamonSet that applications can connect to a node local service. 

![Dapr Ambient Architecture](https://user-images.githubusercontent.com/271966/224546577-e26cea05-75c7-48f6-900c-753b10ea9432.png)

This component can be installed using a Helm Chart per Dapr application that we want to register. 
The main use case that this component is aiming to facilitate is a "Serverless Function" scenario where functions will be downscaled to zero. Causing the `daprd` sidecar to go down with the function, something that complicates the use of some Dapr components that require the `daprd` sidecar to be up at all times, for example to receive async subscriptions. An on going integration with the Knative Functions project drives this initiative. 

A similar deployment model is being used by the Open Function project: https://openfunction.dev/docs/ , but I believe there is a lot of value by having this deployment model implemented with a component that is hosted under the Dapr GitHub organization and documented under the Dapr documentation. 

2. Which programming languages will be used?
>
This component is just an extension of `daprd` so the Go programming language will be used. 

3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform
>
This component is designed for Kubernetes, and a Helm Chart will be provided for its deployment. I don't see why this can't be used outside of Kubernetes, but the main targetted deployment model will be focus on Kubernetes.

4. Enumerate the repositories this project will need to be created.
>

Only `dapr-ambient`, if we can bundle the helm chart definition here. 

5. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?
>

6 months for testing and adding enough documentation and integrations with other projects.

6. Who are the maintainers of this project and corresponding employers?
>
Mauricio Salatino @salaboy, from @diagridio. I can find out if someone from the Knative Community can help too, as the main use case that we are trying to implement is an integration with the Knative Functions project.

**Comment by salaboy** [comment]
I will look into this existing conversation and try to summarize how this thread can contribute to `dapr-ambient`: https://github.com/dapr/dapr/issues/5385

**Comment by salaboy** [comment]
hi @paulyuk thanks for your comment, and I totally get that. I think we can do this work in separate stages, as soon as we all agree on the direction. 

The idea of having a Deamonset is to reduce the hops between the apps and Dapr (`daprd`). With the Helm chart approach proposed, we can install as many deamonsets as we want per node, and I totally understand that this is not optimal, but it will allow us to refactor `daprd` to be more multi-tenant if that makes sense. 

Notice that this proposal is not suggesting an approach where we just install a single `daprd` in ambient mode.  Each tenant can deploy it's own `dapr-ambient` chart with different configurations. Does this make sense?

**Comment by yaron2** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 binding.

**Comment by salmaniqbal** [comment]
+1 binding

**Comment by jaczhao** [comment]
+1 binding

**Comment by yaron2** [comment]
This sandbox proposal is approved. @salaboy I will contact you to give you maintainer rights over the `dapr-ambient` repository once it is created.

**Comment by Forrest-zhao** [comment]
+1 binding
