### ISSUE TITLE
Proposal: Community Health Metrics

### ISSUE THREAD

**Issue by paulyuk** [dapr/community#295]
One of the key responsibilities of STC is to manage the health and growth of the Dapr community.  To do this we need metrics and mechanisms to measure health.  

The important metrics we will watch are as follows:

**Metrics**

Contributors per CommonRoom
- Monthly contributors/members spanning Github stars, Discord members, and Twitter followers
- Top 20 contributing companies: impact**, # of members, Semi-monthly qualitative check ins with companies
** Community impact – weighted system based on user activity in GitHub or Discord (e.g., fork or PR = 10; comment= 4. Learn more about the impact weighting system [here](https://docs.commonroom.io/using-common-room/members-page/impact-points)

Contributors to Dapr project in Github:
- Monthly release contributors
- Monthly release first timers

[CNCF velocity report](https://docs.google.com/spreadsheets/d/1NifFdE45BlscO6j7vlDspccQ-i9Ksgip6yx2bmhmCCs/edit#gid=0)
- Monthly pulse on project velocity rank, also 
activity | comments | prs | commits | issues | authors | pushes

Community qualitative pulse:
- Monthly qualitative pulse on sentiment and feelings around latest release using GitHub issues, Discord, social, and company calls

**Process and mechanism:**
- [Community managers](https://github.com/dapr/community/issues/284) are responsible for gathering, monitoring and analyzing on an ongoing basis
- Monthly report will be provided by community managers to STC + Maintainers
- After 3 months, evaluate which metrics and reports are most useful, and propose changes & metrics to be automated for "self service" by STC/maintainers.

@msfussell (Diagrid)
@yaron2 (Diagrid)
@johnewart (Microsoft)
@cvictory (Alibaba)
@jackzhao (Alibaba)
@Forrest-zhao (Intel)

An example of what this looks like with real data will be presented at STC meeting.

**Comment by yaron2** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 binding

**Comment by paulyuk** [comment]
+1 binding

**Comment by johnewart** [comment]
+1 binding

**Comment by msfussell** [comment]
Approved. @paulyuk to follow up with Community Managers
