### ISSUE TITLE
REQUEST: New membership for @malotho

### ISSUE THREAD

**Issue by malotho** [dapr/community#30]
### GitHub Username

@malotho

### Requirements

 > * [x]  I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
 > * [x]  I have enabled 2FA on my GitHub account. See https://github.com/settings/security
> * [x]  I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
> * [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project
I have reported/contributed to other issues on the Gitter community channel. Some have resulted in bug fix releases.
- PRs reviewed / authored  

1. https://github.com/dapr/dotnet-sdk/pull/229

- Issues responded to
1. https://github.com/dapr/dotnet-sdk/pull/260
2. https://github.com/dapr/dotnet-sdk/issues/173
3. https://github.com/dapr/dotnet-sdk/pull/220
4. https://github.com/dapr/dapr/pull/1082
5. https://github.com/dapr/dapr/issues/1870

## Lead engineer/designer  https://github.com/Ignition-Group-Open-Source-Contrib/Dapr-Microservice-Template

@yaron2

**Comment by yaron2** [comment]
I support this request.

**Comment by yaron2** [comment]
Invite sent, check your email.

**Comment by yaron2** [comment]
Added
