### ISSUE TITLE
May 17th, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#302]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on May 17th, at 9:00am PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by cghsystems** [comment]
Hi @msfussell 

@salaboy and our Company -- Syntasso -- have recently collaberated on a Dapr integration. The gist of the work is captured [here](https://blog.dapr.io/posts/2023/04/02/creating-dapr-enabled-platforms-with-kratix/). We would love to run a demo of the thoughts captured in the blog to the community.

**Comment by msfussell** [comment]
> Hi @msfussell
> 
> @salaboy and our Company -- Syntasso -- have recently collaberated on a Dapr integration. The gist of the work is captured [here](https://blog.dapr.io/posts/2023/04/02/creating-dapr-enabled-platforms-with-kratix/). We would love to run a demo of the thoughts captured in the blog to the community.

@cghsystems - Excellent. Will send you more info closer to the the time on how to join and a link to a deck that you can update, but of course all about the demo!

**Comment by nyemade-uversky** [comment]
@cghsystems and @salaboy we're working on finalizing the community call agenda for this week. Are  either of you still able to demo this week?

**Comment by aclevername** [comment]
@nyemade-uversky either myself or @cghsystems will be able to attend tomorrow to talk about dapr-kratix integration 😄

**Comment by marcduiker** [comment]
> @nyemade-uversky either myself or @cghsystems will be able to attend tomorrow to talk about dapr-kratix integration 😄 is there a deck for us to update?

The Google slides link has been sent to you via Mauricio/Salaboy 😊.

**Comment by aclevername** [comment]
@marcduiker sorry for the late notice but I won't be able to attend todays meeting as my ISP has been down all day and isn't showing any signs of improving. Can we reschedule the dapr-kratix integration presentation to the next community meeting? (31st?). Thanks and sorry again!

**Comment by msfussell** [comment]
@aclevername - Moving this conversation to https://github.com/dapr/community/issues/305. Are you able to present on Wed. I need to send you a link to the deck. Ping me on mark@diagrid.io and I can then send you a link

**Comment by msfussell** [comment]
Completed
