### ISSUE TITLE
31st May Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#305]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on 31st May at 9am  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

## Agenda

- Introduction
- Session 1: Jake Klein, Katrix-Dapr integration
- Session 2: TBD
- Dapr news / Show & tell
- Open discussion
- Closing

 <details>
    <summary>Checklists for the host</summary>

### Before the meeting

- [ ] Find speakers
   - [X]  Jake Klein
   - [ ]  Speaker 2?
- [x] Collect Dapr news (blog posts & videos found on social media, and show-and-tell Discord channel)
- [x] Prepare slide deck
- [ ] Send meeting invite to the speakers
   - [X] Jake Klein
   - [ ] Speaker 2?
- [ ] Announce the meeting on social media
  - [ ] 1 week before
  - [ ] 1 day before
  - [ ] 1 hour before

### During the meeting

- Welcome & announce that the meeting will be recorded
- Start the recording
- Show the agenda
- Welcome first speaker
- First session
- Q&A first session
- Welcome second speaker
- Second session
- Q&A second session
- Show Dapr related news, posts, videos.
- Open discussion
- Closing & mention Dapr Discord channel

### After the meeting

- [ ] Upload the meeting to YouTube
- [ ] Add chapters to the video
- [ ] Add links to the video description
  - [ ] Read-only link to slides
  - [ ] [Dapr Discord link](http://bit.ly/dapr-discord)
  - [ ] Other relevant links related to the sessions
- [ ] Announce the published video on social media
- [ ] Close this issue

</details>

**Comment by marcduiker** [comment]
Topic 1: [aclevername](https://github.com/aclevername) will present on dapr-kratix

**Comment by msfussell** [comment]
@aclevername - Are you able to present on Wed. I need to send you a link to the deck. Ping me on mark@diagrid.io and I can then send you a link

**Comment by aclevername** [comment]
> @aclevername - Are you able to present on Wed. I need to send you a link to the deck. Ping me on [mark@diagrid.io](mailto:mark@diagrid.io) and I can then send you a link

Yes! I've emailed you 😄 thanks!

**Comment by msfussell** [comment]
Complete
