### ISSUE TITLE
April 2023 STC meeting

### ISSUE THREAD

**Issue by msfussell** [dapr/community#306]
# April 2023 STC meeting.

## STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@paulyuk (Microsoft)
@johnewart (Microsoft)

## Absent
@cvictory (Alibaba)
@jackzhao (Alibaba)
@Forrest-zhao (Intel)

## Action items from previous meetings
Previous March 2023 https://github.com/dapr/community/issues/290 meeting notes
- @paulyuk Follow up on progress from last month's review of the health metrics for the community

## Agenda and Notes
* Voted on https://github.com/dapr/community/issues/295 for the community measurement report. Passed. Action: Paul to share community measurement report numbers in next 2 weeks before next STC. 
* Voted on https://github.com/dapr/community/pull/307 for the update of the nomination and voting for approvers and maintainers. Passed
* @johnewart - Proposed creating a Milestone Post Mortem template and using this after the v1.11 release to improve and release practices. Action: John to create and share template.

Next STC will be held on 11th May 2023.

**Comment by johnewart** [comment]
Sorry, meant to add this earlier today:

* Identify improvements to continuous release process / more automated testing 
* Schedule a postmortem for 1.11 release (unless I missed it -- I can create a first pass at a template if we need one) 
* Discuss thoughts about some sort of health dashboard around how long / how many PRs are open across the repos (or at least runtime/components maybe), possibly adding more information over time

**Comment by paulyuk** [comment]
>>@paulyuk Follow up on progress from last month's review of the health metrics for the community
In the spirit of being agile I suggest we go by my current proposal for one more month and see what we like and dislike.  

The main issue we discussed in the last meeting is that "Velocity score" and "impact scores" weigh different things.  I like aspects of both and would like to evaluate, which score is useful for answering which questions.

**Comment by msfussell** [comment]
Completed
