### ISSUE TITLE
REQUEST: New membership for cgillum

### ISSUE THREAD

**Issue by cgillum** [dapr/community#308]
### GitHub Username

@cgillum

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- https://github.com/dapr/dapr/issues/4576
- https://github.com/dapr/dapr/pull/5761
- https://github.com/dapr/dapr/pull/5784
- https://github.com/dapr/docs/pull/3139
- https://github.com/dapr/docs/pull/3142
- https://github.com/dapr/dotnet-sdk/pull/1012
- https://github.com/dapr/dotnet-sdk/pull/1035
- https://github.com/dapr/dotnet-sdk/pull/1059

(there are several other smaller contributions, but these are the more significant ones)

### Sponsors

- @ItalyPaleAle
- @berndverst 
- @halspang

**Comment by ItalyPaleAle** [comment]
👍

**Comment by msfussell** [comment]
👍

**Comment by berndverst** [comment]
👍 
+1 binding

**Comment by halspang** [comment]
👍

**Comment by paulyuk** [comment]
👍
+1 binding

**Comment by yaron2** [comment]
Invitation sent
