### ISSUE TITLE
REQUEST: New membership for @ashiquemd

### ISSUE THREAD

**Issue by ASHIQUEMD** [dapr/community#310]
### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- https://github.com/dapr/dapr/pull/5790
- https://github.com/dapr/dapr/pull/5974
- https://github.com/dapr/components-contrib/issues/2598
- https://github.com/dapr/quickstarts/pull/820
- https://github.com/dapr/quickstarts/pull/819
- https://github.com/dapr/quickstarts/pull/816
- https://github.com/dapr/quickstarts/pull/813
- https://github.com/dapr/quickstarts/pull/805
- https://github.com/dapr/dapr/pull/6234

**Comment by ASHIQUEMD** [comment]
cc @paulyuk

**Comment by yaron2** [comment]
+1 binding

**Comment by pravinpushkar** [comment]
+1

**Comment by berndverst** [comment]
+1 binding

**Comment by artursouza** [comment]
Invite sent to [ASHIQUEMD](https://github.com/ASHIQUEMD)
