### ISSUE TITLE
REQUEST: New membership for @yash-nisar

### ISSUE THREAD

**Issue by yash-nisar** [dapr/community#311]
### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- https://github.com/dapr/dotnet-sdk/pull/929
- https://github.com/dapr/dotnet-sdk/pull/951
- https://github.com/dapr/dotnet-sdk/pull/942
- https://github.com/dapr/dotnet-sdk/pull/962
- https://github.com/dapr/dotnet-sdk/pull/1001
- https://github.com/dapr/dotnet-sdk/pull/974
- https://github.com/dapr/dotnet-sdk/pull/1051
- https://github.com/dapr/components-contrib/pull/2123
- https://github.com/dapr/components-contrib/pull/2082
- https://github.com/dapr/components-contrib/pull/2040

**Comment by yash-nisar** [comment]
CC @berndverst @ItalyPaleAle @halspang

**Comment by berndverst** [comment]
👍🏻 I support this.

Long overdue actually.

**Comment by halspang** [comment]
👍

**Comment by mukundansundar** [comment]
+1 binding

**Comment by hueifeng** [comment]
+1

**Comment by yaron2** [comment]
Invite sent
