### ISSUE TITLE
May 2023 STC meeting.

### ISSUE THREAD

**Issue by msfussell** [dapr/community#316]
STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@paulyuk (Microsoft)
@johnewart (Microsoft)
@cvictory (Alibaba)
@jackzhao (Alibaba)
@Forrest-zhao (Intel)

## Action items from previous meetings
Previous April STC 2023 [https://github.com/dapr/community/issues/290 meeting notes](https://github.com/dapr/community/issues/306)

## Agenda and Notes
-  @paulyuk Follow up on progress from last month's review of the health metrics for the community. - Action: Paul will create a report with the latest numbers to shared with the Dapr Maintainers for the June STC. 
-  @johnewart - Proposed creating a Milestone Post Mortem template and using this after the v1.11 release to improve and release practices. Action: John to create and share template in a PR in the next week
- @yaron2 Raised the latest status on the https://github.com/dapr-sandbox/dapr-ambient project. It is looking likely that this project does not need to graduate in itself, however will become a core part of the Dapr runtime
- @Forrest-zhao - Gave an update on the goal of Intel working to ensure that Dapr runs best on Intel hardware
- @cvictory - Ask about the ability to reloading of existing components https://github.com/dapr/dapr/issues/1172 and the dynamic registration of pub/sub https://github.com/dapr/dapr/issues/814
- @msfussell - Raised the ask for getting all STC members to test the upcoming v1.11 RC and also to help contribute to the stability of the v1.12 release, which will focus more on fundamentals. 

Next STC meeting set for the 8th June 2023.

**Comment by paulyuk** [comment]
@msfussell we closed last month on the plan for community health metrics with binding vote.  I think we can remove from agenda, and leave it to me + community managers to execute regularly.  That is unless you want an agenda every month to go through metrics?

**Comment by msfussell** [comment]
Yes, I put this here since it would be good when to plan to have the first report out and set a date. I thought that we said that we would have this for the next STC, but we can pick another date.

**Comment by msfussell** [comment]
Completed
