### ISSUE TITLE
REQUEST: New membership for @MregXN

### ISSUE THREAD

**Issue by MregXN** [dapr/community#318]
### GitHub Username

@mregxn
I'm working in Microsoft Dapr China Team now. I am now trying to add E2E tests and Metadata files.

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [PRs in dapr/components-contrib](https://github.com/dapr/components-contrib/pulls?q=is%3Apr+author%3AMregXN+is%3Aclosed)
- [PRs in dapr/java-SDK](https://github.com/dapr/java-sdk/pulls?q=is%3Apr+author%3AMregXN+)
- [Repo in dapr-sandbox](https://github.com/dapr-sandbox/spring-cloud-dapr)

### Sponsors
@mukundansundar  @skyao

**Comment by skyao** [comment]
I support this request.

**Comment by mukundansundar** [comment]
+1 I support this request.

**Comment by MregXN** [comment]
@yaron2  Hi. Can you approve this issue for me ?

**Comment by yaron2** [comment]
+1

**Comment by msfussell** [comment]
@MregXN - Invitation sent

**Comment by msfussell** [comment]
Closing issue
