### ISSUE TITLE
REQUEST: New membership for chinzhiweiblank

### ISSUE THREAD

**Issue by chinzhiweiblank** [dapr/community#32]
### GitHub Username

@chinzhiweiblank

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
[List of Dapr PRs](https://github.com/dapr/dapr/pulls?q=is%3Apr+author%3Achinzhiweiblank+is%3Aclosed+)
[List of Cli PRs](https://github.com/dapr/cli/pulls?q=is%3Apr+author%3Achinzhiweiblank+is%3Aclosed+)
[List of Python-sdk PRs](https://github.com/dapr/python-sdk/pulls?q=is%3Apr+author%3Achinzhiweiblank+is%3Aclosed+)
https://github.com/dapr/python-sdk/pull/64
https://github.com/dapr/python-sdk/pull/100
https://github.com/dapr/python-sdk/pull/103
https://github.com/dapr/dapr/pull/1632
https://github.com/dapr/dapr/pull/1681
https://github.com/dapr/python-sdk/pull/61
https://github.com/dapr/cli/pull/355
- Issues responded to
https://github.com/dapr/python-sdk/issues/41
https://github.com/dapr/python-sdk/issues/53
https://github.com/dapr/python-sdk/issues/74
https://github.com/dapr/dapr/issues/924
https://github.com/dapr/cli/issues/247

### Sponsors
@yaron2 @youngbupark

**Comment by yaron2** [comment]
I support this request.

**Comment by youngbupark** [comment]
I support this request too.

**Comment by yaron2** [comment]
@chinzhiweiblank an invite has been sent, check your mail.

**Comment by chinzhiweiblank** [comment]
I have accepted the invitation.
