### ISSUE TITLE
Request for new sandbox project: dapr-kubernetes-operator

### ISSUE THREAD

**Issue by salaboy** [dapr/community#325]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.
>

With the Dapr Kubernetes Operator, community users will be able to install Dapr into a Kubernetes cluster in a declarative way. 
This also enable the scenario of installed Dapr into an Openshift cluster, and the inclusion of Dapr in the Openshift Marketplace.

2. Which programming languages will be used?
>
Go

3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform
>
No, but there might be some bits of Openshift included in the project.

4. Enumerate the repositories this project will need to be created.
>
Only one: `dapr-kubernetes-operator`

5. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?
>
The goal is to have this Operator published at https://operatorhub.io at that point, it can be considered stable. 

6. Who are the maintainers of this project and corresponding employers?
>
Red Hat @lburgazzoli and Diagrid @salaboy

**Comment by artursouza** [comment]
+1 non-binding

**Comment by artursouza** [comment]
@salaboy Can you be specific about the GitHub alias of the maintainers and their employers? Companies do not maintain projects but they sponsor people that do.

**Comment by salaboy** [comment]
@artursouza yes. I will be working on this with @lburgazzoli  as we will be bringing his implementation to this new repo: https://github.com/lburgazzoli/dapr-operator

**Comment by salaboy** [comment]
@artursouza any news on this ?

**Comment by yaron2** [comment]
+1 binding

**Comment by Forrest-zhao** [comment]
+1 binding, that would be good for Dapr to be promoted to more Openshift developers/users

**Comment by msfussell** [comment]
+1 binding

**Comment by cvictory** [comment]
+1 binding

**Comment by yaron2** [comment]
Approval is in place. Congrats @lburgazzoli and @salaboy. We'll open a new repository for you and add you as maintainers.

**Comment by yaron2** [comment]
@lburgazzoli and @salaboy look for an invite from the `dapr-sandbox` organization, the repository is now live: https://github.com/dapr-sandbox/dapr-kubernetes-operator/
