### ISSUE TITLE
REQUEST: @joshvanl as approver in dapr/dapr

### ISSUE THREAD

**Issue by JoshVanL** [dapr/community#327]
GitHub Username

@joshvanl  as approver in dapr/dapr

PRs:
https://github.com/dapr/dapr/pulls?q=author%3Ajoshvanl+ (Total: 43 Merged)

Highlights:
- Identity overhaul (though not merged due to test coverage)
  - https://github.com/dapr/dapr/pull/6171
  - https://github.com/dapr/dapr/pull/6179
  - https://github.com/dapr/dapr/pull/6193
- Integration tests/API bug fixes
  - https://github.com/dapr/dapr/pull/6327
  - https://github.com/dapr/dapr/pull/6340
  - https://github.com/dapr/dapr/pull/6463
  - https://github.com/dapr/dapr/pull/6573
- 1.11.1, 1.10.8 patch releases
  - https://github.com/dapr/dapr/pull/6555
  - https://github.com/dapr/dapr/pull/6556
- runtime/control plane refactoring for hotrloading/graceful shutdown
  - https://github.com/dapr/dapr/pull/6584
  - https://github.com/dapr/dapr/pull/6382
  - https://github.com/dapr/dapr/pull/6232
  - https://github.com/dapr/dapr/pull/6323
  - https://github.com/dapr/dapr/pull/5831
  - https://github.com/dapr/dapr/pull/5860
  - https://github.com/dapr/dapr/pull/5859
  - https://github.com/dapr/dapr/pull/6037
- SDK test jobs
  - https://github.com/dapr/dapr/pull/6310
  - https://github.com/dapr/dapr/pull/6309
  - https://github.com/dapr/dapr/pull/6304
- Placement unit test improvement
  - https://github.com/dapr/dapr/pull/6308
  - https://github.com/dapr/dapr/pull/6079
  - https://github.com/dapr/dapr/pull/6026
  - https://github.com/dapr/dapr/pull/6037

PRs reviewed: https://github.com/dapr/dapr/pulls?q=-author%3Ajoshvanl+involves%3Ajoshvanl+ (Total: 25)

Issues created: https://github.com/dapr/dapr/issues?q=is%3Aissue+author%3Ajoshvanl+ (Total: 7)

Issues from others contributed to: https://github.com/dapr/dapr/issues?q=is%3Aissue+-author%3Ajoshvanl+involves%3Ajoshvanl (Total: 19)

Sponsor: @artursouza

**Comment by artursouza** [comment]
+1 binding

**Comment by mukundansundar** [comment]
+1 binding

**Comment by yaron2** [comment]
We have enough approving votes. Closing
