### ISSUE TITLE
July 2023 Steering and Technical Committee (STC) meeting

### ISSUE THREAD

**Issue by msfussell** [dapr/community#328]
STC Attendees:
@msfussell (Diagrid)
@yaron2 (Diagrid)
@paulyuk (Microsoft)

Declined
@johnewart (Microsoft)
@cvictory (Alibaba)
@jackzhao (Alibaba)
@Forrest-zhao (Intel)

No quorum for the meeting. This meeting was cancelled and voting on issue done in separate email. 

## Action items from previous meetings
Previous June STC 2023 https://github.com/dapr/community/issues/319 meeting notes 

-  @johnewart - Proposed creating a Milestone Post Mortem template and using this after the v1.11 release to improve and release practices. Action: John to create and share template in a PR in the next week

## Agenda and Notes
@yaron2  - Proposed sandbox projects. 
     - https://github.com/dapr/community/issues/325
     - https://github.com/dapr/community/issues/309
@paulyuk - Discuss proposal for Workflow Beta in 1.12 and expected criteria per https://github.com/dapr/proposals/issues/30
 @msfussell  - Dapr Website refresh working with CNCF

Next STC meeting: 10th August 2023 @7:00pm PST (Pacific) or 11th August 2023 @ 10:00am China

**Comment by paulyuk** [comment]
One more suggested item:

- Discuss proposal for Workflow Beta in 1.12 and expected criteria per https://github.com/dapr/proposals/issues/30

**Comment by paulyuk** [comment]
Note I anticipate @johnewart will be unavailable today since he has a family emergency.

**Comment by msfussell** [comment]
Completed
