### ISSUE TITLE
REQUEST: New membership for @jjcollinge

### ISSUE THREAD

**Issue by jjcollinge** [dapr/community#33]
### GitHub Username

@jjcollinge

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/dapr/pull/1792
https://github.com/dapr/dapr/pull/1588
https://github.com/dapr/dapr/pull/1507
https://github.com/dapr/dapr/pull/1392
https://github.com/dapr/dapr/pull/1217
https://github.com/dapr/dapr/pull/1178
https://github.com/dapr/dapr/pull/1120
https://github.com/dapr/dapr/pull/1089
https://github.com/dapr/dapr/pull/1064
https://github.com/dapr/dapr/pull/1054
https://github.com/dapr/dapr/pull/962
https://github.com/dapr/components-contrib/pull/336
https://github.com/dapr/components-contrib/pull/329
https://github.com/dapr/components-contrib/pull/308
https://github.com/dapr/components-contrib/pull/228
https://github.com/dapr/components-contrib/pull/93
https://github.com/dapr/components-contrib/pull/148

- Issues responded to
https://github.com/dapr/dapr/issues/1679
https://github.com/dapr/dapr/issues/1617
https://github.com/dapr/dapr/issues/1532
https://github.com/dapr/dapr/issues/1526
https://github.com/dapr/dapr/issues/1518
https://github.com/dapr/dapr/issues/1486
https://github.com/dapr/dapr/issues/1253
https://github.com/dapr/dapr/issues/1188
https://github.com/dapr/dapr/issues/1060
https://github.com/dapr/dapr/issues/1030
https://github.com/dapr/dapr/issues/970
https://github.com/dapr/components-contrib/issues/204
https://github.com/dapr/components-contrib/issues/189
https://github.com/dapr/components-contrib/issues/164
https://github.com/dapr/components-contrib/issues/155

**Comment by yaron2** [comment]
I support this request

**Comment by yaron2** [comment]
Added
