### ISSUE TITLE
REQUEST: New membership for sicoyle

### ISSUE THREAD

**Issue by sicoyle** [dapr/community#338]
### GitHub Username

sicoyle

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

external service invocation feature: https://github.com/dapr/dapr/pull/6227
https://github.com/dapr/dapr/issues?q=is%3Aissue+sicoyle+is%3Aclosed

**Comment by yaron2** [comment]
+1 binding

**Comment by JoshVanL** [comment]
+1 non-binding

**Comment by ItalyPaleAle** [comment]
+1

**Comment by sicoyle** [comment]
I've been added to the org. Thank youuuu!
