### ISSUE TITLE
Proposal: Community tool (chat, topics, ...)

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/community#34]
As discussed, maybe we could open an issue here to see what the community favors in terms of communication tool?

An idea could be to have a topic such as this and have votes through like types such as is often done on Facebook / LinkedIn / ...

Community tool ideas:

* Gitter
* Discord
* Slack
* ...

Looking forward to thoughts and as well to see if this is the correct place for this discussion 😊

**Comment by yaron2** [comment]
@orizohar @AaronCrawfis we need to start acting on this.. gitter doesn't scale well at all for our uses.

Personally, I'd rather use Discord.

**Comment by jjcollinge** [comment]
I'm definitely struggling with Gitter. Happy for either Discord or Slack!

**Comment by XavierGeerinck** [comment]
@yaron2 how do you see the plan of action here? Were you already able to try out Discord here? (https://discord.gg/A2YjzHUV)

**Comment by AaronCrawfis** [comment]
@XavierGeerinck I have a server setup here with configured channels and community settings enabled: https://discord.gg/e9PrFHr3

**Comment by XavierGeerinck** [comment]
Thanks @AaronCrawfis I had no idea that one was already existing! I joined it and removed the other one (will remove the link as well in my previous comment)

**Comment by spottedmahn** [comment]
>I have a server setup here with configured channels and community settings enabled: https://discord.gg/e9PrFHr3

invite expired, can I search my discord name or something? 🤔

![image](https://user-images.githubusercontent.com/14079228/168906013-474c07a7-5dd0-40fc-8750-5c18360c60d1.png)

**Comment by AaronCrawfis** [comment]
> > I have a server setup here with configured channels and community settings enabled: https://discord.gg/e9PrFHr3
> 
> invite expired, can I search my discord name or something? 🤔
> 
> ![image](https://user-images.githubusercontent.com/14079228/168906013-474c07a7-5dd0-40fc-8750-5c18360c60d1.png)

Try http://aka.ms/dapr-discord, that should have an updated invite link
