### ISSUE TITLE
REQUEST: Approver status for @berndverst in dapr/docs

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/community#340]
### GitHub Username

@berndverst 

### Requirements

Bernd has:
- [x] Reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] Enabled 2FA on GitHub account. See https://github.com/settings/security
- [x] Subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] Contributed (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

[Commented on 23 issues](https://github.com/search?q=repo%3Adapr%2Fdocs%20commenter%3Aberndverst&type=issues)
[Opened 9 issues (opened more indirectly through Dapr bot)](https://github.com/search?q=repo%3Adapr%2Fdocs+author%3Aberndverst&type=issues)
[Opened 60 PRs](https://github.com/search?q=repo%3Adapr%2Fdocs+author%3Aberndverst&type=pullrequests)
[Reviewed 31 PRs](https://github.com/search?q=repo%3Adapr%2Fdocs+reviewed-by%3Aberndverst&type=pullrequests)

**Comment by greenie-msft** [comment]
+1 for this

**Comment by hhunter-ms** [comment]
+1

**Comment by msfussell** [comment]
+1

**Comment by berndverst** [comment]
Can this be completed now? :)

**Comment by msfussell** [comment]
+1
