### ISSUE TITLE
REQUEST: New membership for @kendallroden

### ISSUE THREAD

**Issue by kendallroden** [dapr/community#347]
### GitHub Username

@kendallroden

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

Recent samples PR 
- https://github.com/dapr/samples/pull/159

Code contributions for Dapr outside of Dapr repos
- https://github.com/azure-samples/containerapps-dapralbums

Recent community contributions 
- https://www.youtube.com/watch?v=mBgQBMhboyU&t=2s

**Comment by msfussell** [comment]
+1

**Comment by yaron2** [comment]
+1
