### ISSUE TITLE
DAPR binding for SOAP API

### ISSUE THREAD

**Issue by sachtec** [dapr/community#348]
Hi,

Does Dapr binding Support SOAP API binding? If not then what is the good approach to bind SOAP?

**Comment by msfussell** [comment]
Dapr does not support any SOAP specifications. It supports gRPC and HTTP as protocols, but you cannot communicate with SOAP endpoints. You would need to find a SOAP serialization library in the code of your choice.

**Comment by sachtec** [comment]
Thanks for immediate revert.
