### ISSUE TITLE
REQUEST: New membership for @alicejgibbons

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/community#350]
### GitHub Username

@alicejgibbons

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored:
  - https://github.com/dapr/docs/pull/3727
  - https://github.com/dapr/docs/pull/3688
- Issues created/responded to:
  - https://github.com/dapr/components-contrib/issues/2942
  - https://github.com/dapr/components-contrib/issues/2941
  - https://github.com/dapr/components-contrib/issues/2940
  - https://github.com/dapr/dapr/issues/5939
  - https://github.com/dapr/dapr/issues/6087
  - https://github.com/dapr/dapr/issues/6288
  - https://github.com/dapr/dapr/issues/6517

@msfussell @yaron2 @artursouza

**Comment by yaron2** [comment]
+1

**Comment by msfussell** [comment]
+1

**Comment by msfussell** [comment]
Approved
