### ISSUE TITLE
REQUEST: New membership for elena-kolevska

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/community#353]
### GitHub Username

@elena-kolevska

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

#### PRs
- [python-sdk: TLS support and standardised environment variables for endpoints](https://github.com/dapr/python-sdk/pull/597)
- [js-sdk: Support for the DAPR_HTTP_ENDPOINT and DAPR_GRPC_ENDPOINT environment variables. Adds support for DAPR_API_TOKEN to gRPC client](https://github.com/dapr/js-sdk/pull/519)
- [components-contrib: Fix failing GCP tests](https://github.com/dapr/components-contrib/pull/3169)
- [ENV variables support for the python sdk workflow extension](https://github.com/dapr/python-sdk/issues/609)
- [cpp-sdk: update protos and fix Dockerfile](https://github.com/dapr/cpp-sdk/pull/53)
- [rust-sdk: update protos and documentation](https://github.com/dapr/rust-sdk/pull/102)

#### Proposals:
- [proposal: Standardise use of env variables for dapr api token](https://github.com/dapr/proposals/pull/38)

### Sponsors
@artursouza , @yaron2

**Comment by msfussell** [comment]
+1

**Comment by yaron2** [comment]
+1 binding

**Comment by artursouza** [comment]
@elena-kolevska You should have an invite to join Dapr's members group.

**Comment by elena-kolevska** [comment]
Thank you everyone. I'm now a part of the org 🙏
