### ISSUE TITLE
Opportunity: Dapr Hacktoberfest participation

### ISSUE THREAD

**Issue by sicoyle** [dapr/community#354]
https://github.com/topics/hacktoberfest
https://hacktoberfest.com/

Hacktoberfest docs say: 
> Register anytime between September 26 and October 31

> Hacktoberfest is a month-long celebration of open source projects, their maintainers, and the entire community of contributors. Each October, open source maintainers give new contributors extra attention as they guide developers through their first pull requests on GitHub.

We've been pulling together a lot of good first time issues for the Grace Hopper Celebration (tomorrow), and I think it is an opportunity for the Dapr community to look at what other outreach opportunities there are for new contributors. Hacktoberfest is another great opportunity that I want to throw out there. While it does start in 4 days, we can still start the process and join late, or be extra prepped for next year 😎 

As I understand it, in order to participate we would just have to add the Hacktoberfest tag for each repo to join in, and add the label on issues for people participating in the event to find and work on.

**Comment by marcduiker** [comment]
I love Hacktoberfest! But I would like to see us better prepared, and I think we need more time for:
- Writing clearer contributing docs
- Creating contibuting videos
- Better issue descriptions with:
  - current behaviour
  - expected outcome
  - how to verify the expected outcome
- A longer lead time to announce that Dapr is joining Hacktoberfest, we can share on social media/Discord etc.
- Create Holopin badges for the event.

**Comment by msfussell** [comment]
Passed
