### ISSUE TITLE
Improve community awareness through additional/standardized repo Github badges

### ISSUE THREAD

**Issue by sicoyle** [dapr/community#355]
It would be nice if all of the dapr repositories had the same Github badges listed in their repositories.

This has benefits in that we could then look at where we're at today, and what needs improvements. Such as if a build is failing, and needs correcting... or if code coverage is low, and needs to be increased moving forward.

Action items:
- [ ] Please review each dapr repository
- [ ] Note which labels are missing for each
- [ ] Add missing labels to each repository

[Repositories to check](https://github.com/dapr).

Additional context:
An example of the github badges for the `dapr/dapr` repo can be found at the bottom of this image:
<img width="828" alt="image" src="https://github.com/dapr/community/assets/25728646/2a91c54c-9ce1-4a5f-b1f0-712102ba0e2f">

**Comment by marcduiker** [comment]
I really like this idea @sicoyle. The badges probably fall into two categories:

1. Badges that are the same for all repos (Discord, Twitter, License).
2. Badges specific to the repo (package download, test coverage etc).

I suggest creating separate issues for all the Dapr repos and listing the required badges in those issues. I will help with this. Then we have them labelled as good-first-issue.

**Comment by marcduiker** [comment]
Individual issues have been created for the repos
