### ISSUE TITLE
REQUEST: New membership for olitomlinson

### ISSUE THREAD

**Issue by olitomlinson** [dapr/community#362]
### GitHub Username

olitomlinson

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- **2 PRs authored**
https://github.com/dapr/dapr/pull/6851
https://github.com/dapr/docs/pull/3788

- **23 + 4 + 13 + 5 + 3 Issues created**
https://github.com/dapr/dapr/issues?q=is%3Aissue+author%3Aolitomlinson+
https://github.com/dapr/components-contrib/issues?q=author%3Aolitomlinson+
https://github.com/dapr/docs/issues?q=is%3Aissue+author%3Aolitomlinson
https://github.com/dapr/dotnet-sdk/issues?q=+author%3Aolitomlinson+
https://github.com/dapr/java-sdk/issues?q=author%3Aolitomlinson

- **78 + 8 + 6 Issues commented on**
https://github.com/dapr/dapr/issues?q=commenter%3Aolitomlinson
https://github.com/dapr/components-contrib/issues?q=commenter%3Aolitomlinson
https://github.com/dapr/dotnet-sdk/issues?q=commenter%3Aolitomlinson

- **1,831 comments made on Discord**

**Comment by yaron2** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 binding

**Comment by yaron2** [comment]
@olitomlinson you're now an org member.
