### ISSUE TITLE
REQUEST: New membership for @mikeee

### ISSUE THREAD

**Issue by mikeee** [dapr/community#368]
### GitHub Username

@mikeee

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- dapr/go-sdk#439
- dapr/sig-api#9
- dapr/docs#3798
- dapr/go-sdk#460
- dapr/docs#3797
- dapr/docs#3796
- dapr/docs#3798
- dapr/go-sdk#440
- dapr/go-sdk#441
- dapr/go-sdk#442
- dapr/go-sdk#443
- dapr/dapr#6757
- dapr/dapr#6851
- dapr/dapr#7077
- dapr/go-sdk#468

**Comment by yaron2** [comment]
+1 binding

**Comment by shubham1172** [comment]
+1 binding
