### ISSUE TITLE
REQUEST: New membership for trondhindenes

### ISSUE THREAD

**Issue by trondhindenes** [dapr/community#37]
### GitHub Username
trondhindenes

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project
https://github.com/dapr/components-contrib/pull/340
https://github.com/dapr/components-contrib/pull/347
https://github.com/dapr/components-contrib/pull/525
https://github.com/dapr/components-contrib/issues/339

Was told by @yaron2 to add him as a sponsor

**Comment by yaron2** [comment]
I support this request

**Comment by youngbupark** [comment]
I support this request too.

**Comment by yaron2** [comment]
@trondhindenes look out for an invite from GitHub and welcome to the Dapr community.

**Comment by trondhindenes** [comment]
got it - thanks!
