### ISSUE TITLE
REQUEST: New membership for cicoyle

### ISSUE THREAD

**Issue by cicoyle** [dapr/community#370]
### GitHub Username

cicoyle

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [distributed scheduler proposal](https://github.com/dapr/proposals/pull/44)
- [opened an issue for removing the conformance test requirement for binding components](https://github.com/dapr/proposals/issues/37) && [updated the docs](https://github.com/dapr/docs/pull/3731)
- [helped with the v1.12 endgame](https://github.com/dapr/dapr/issues/6899): updated quickstarts/tutorials to check rc && tested/validated dashboard
- [reviewed this zeebe components certification test PR](https://github.com/dapr/components-contrib/pull/3112)

**Comment by sicoyle** [comment]
+1 nonbinding and only partially biased 😉  👯‍♀️

**Comment by msfussell** [comment]
+1

**Comment by JoshVanL** [comment]
+1 non-binding

**Comment by ItalyPaleAle** [comment]
+1

**Comment by berndverst** [comment]
+1 binding

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
Invite sent.
