### ISSUE TITLE
Document triage process for all subprojects

### ISSUE THREAD

**Issue by yaron2** [dapr/community#38]
Dapr repositories should undergo a regular process for triaging issues.

We need to address the following:

* Describe basic triage work responsibilities - following up on stale issues, addressing issues, etc.
* Adding labels to issues
* Ensuring issues are assigned when someone is working on them
* Marking issues and PRs as duplicates
* Tooling for project-wide, cross repository visibility

**Comment by msfussell** [comment]
This has been addressed
