### ISSUE TITLE
Open call for a Dapr community manager

### ISSUE THREAD

**Issue by marcduiker** [dapr/community#396]
**Do you want to be a Dapr community manager?** 

A Dapr community manager is responsible for engaging with the community, helping the community grow, and providing insights to maintainers and Steering & Technical Committee (STC) members (more info in this [doc](https://github.com/dapr/community/blob/master/COMMUNITY-MANAGER.md)).

Currently, I'm the only one fulfilling this role. Another member would be very welcome to help me give the community and the Dapr project the attention they need.

Things you'll be doing as a Dapr community manager:

- 🎙️ Take turns in hosting the bi-weekly Dapr community call (this is live-streamed and published to YouTube).
- 📚 Collect community generated content (blogs/tweets) to highlight during the community calls.
- 🏆 Award Dapr community members with digital badges and physical stickers.
- 💬 Engage with new Dapr Discord members, help to answer questions, or connect them to other Dapr users/maintainers.
- 📈 Collect and report community and SDK metrics (bi-weekly).
- 🔎 Find speakers for the community call.
- 🎯 Identify organizations / OSS projects to collaborate with. 

Requirements:

- Good networking & relationship building skills.
- Familiar with technical OSS communities.

The expected workload is around 2-3 hours per week. The bi-weekly community calls are on Wednesdays between 9:00-10:00 PST / 18:00-19:00 CEST.

I will help you onboard in this role, so don't worry that you'll have to figure everything out by yourself. This is a voluntary role with an initial term of 12 months, which can be extended. The process of becoming a community member is described [here](https://github.com/dapr/community/blob/master/COMMUNITY-MANAGER.md#process-to-become-a-community-manager). Please submit your application before December 15th 2023.

I hope to see your application soon and let's work together on growing a happy and healthy Dapr community! 🚀

Marc Duiker
@marcduiker

**Comment by techcraver** [comment]
Hi there - I'm curious - are you still considering applicants? I'd like to be involved!
