### ISSUE TITLE
REQUEST: New membership for gdhuper

### ISSUE THREAD

**Issue by gdhuper** [dapr/community#40]
### GitHub Username

@gdhuper

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Gitter channel](https://gitter.im/dapr/community)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
   [dapr/rust-sdk](https://github.com/dapr/rust-sdk/pull/34)
   [dapr/rust-sdk](https://github.com/dapr/rust-sdk/pull/26)
   [dapr/rust-sdk](https://github.com/dapr/rust-sdk/pull/20)
   [dapr/rust-sdk](https://github.com/dapr/rust-sdk/pull/18)
   [dapr/rust-sdk](https://github.com/dapr/rust-sdk/pull/16)
   [dapr/cli](https://github.com/dapr/cli/pull/383)
   [dapr/cli](https://github.com/dapr/cli/pull/387)
   
- Issues responded to
  [dapr/rust-sdk](https://github.com/dapr/rust-sdk/issues/33)
  [dapr/cli](https://github.com/dapr/cli/issues/406)
  [dapr/cli](https://github.com/dapr/cli/issues/341)

Issue opened as requested by @youngbupark

**Comment by youngbupark** [comment]
I supported this request.

**Comment by yaron2** [comment]
+1

**Comment by yaron2** [comment]
Hey @gdhuper, look out for a GitHub invite in your mailbox.
