### ISSUE TITLE
Application for Community Manager (sp6370)

### ISSUE THREAD

**Issue by sp6370** [dapr/community#408]
Hey Dapr Team,

After being introduced to Dapr through Kendall and Alice's talk at KubeCon Chicago and meeting Marc and Artur, I'm eager to apply for the Dapr Community Manager role. The passion of the community members has inspired me to actively contribute to the project's growth. I'm ready to commit 2-3 hours per week to the role and excited about the opportunity to contribute to the thriving Dapr community.

Related: #396

**Comment by sp6370** [comment]
Hi @marcduiker!
Please do let me know if you need any mor information from my end.

**Comment by marcduiker** [comment]
> Hi @marcduiker! Please do let me know if you need any mor information from my end.

Thank you for applying @sp6370! If you have any OSS experience or community experience, you should include that in your application so the Steering and Technical Committee (STC) can make an informed decision.

**Comment by marcduiker** [comment]
Hi @sp6370, can you please email me at marc@diagrid.io, so I can inform you about your community manager application?
