### ISSUE TITLE
Applying for Dapr Community Manager (AnnuCode)

### ISSUE THREAD

**Issue by AnnuCode** [dapr/community#410]
reference: #396 
Hi, I am interested in contributing to the Dapr Community by becoming a Community Manager and accomplish the tasks required in this role. I think community plays a vital role in success and adoption of any open source project, and I am passionate to play the part which would enable the community members to learn more about Dapr and its progress.
A few of my past open source contributions are: 

### Komiser
- [Feature: Added support for AWS RDS Proxies](https://github.com/tailwarden/komiser/pull/808)
- [Feature: Added support for MongoDB Atlas Serverless clusters](https://github.com/tailwarden/komiser/pull/648)
- [Feature: Added support for GCP Clusters](https://github.com/tailwarden/komiser/pull/693)
- [Feature: Added support for AWS RDS Cluster Snapshot](https://github.com/tailwarden/komiser/pull/836)
### Meshery
- [Enabled Meshery application integration with GitHub Codespaces](https://discuss.layer5.io/t/successfully-setup-cloud-based-developer-environment-to-contribute-to-meshery-using-github-codespaces/1822)
- [Feature: Doc for installing/running Meshery on GitHub Codespaces](https://github.com/meshery/meshery/pull/6952)
- [New User of the Month](https://discuss.layer5.io/badges/44/new-user-of-the-month?username=annu.singh)
### Prisma
- [Discovered a GraphQL error in Nexus library, during it's integration with Prisma](https://github.com/prisma/prisma/discussions/14148#discussioncomment-4174142)

**Comment by marcduiker** [comment]
Thank you for applying @AnnuCode! The Dapr STC will select the community manager end of December.

**Comment by marcduiker** [comment]
Hi @AnnuCode, can you please email me at marc@diagrid.io, so I can inform you about your community manager application?

**Comment by marcduiker** [comment]
@AnnuCode has accepted the role and onboarding process is started.
