### ISSUE TITLE
Community Manager Application (Cecil)

### ISSUE THREAD

**Issue by cecilphillip** [dapr/community#412]
Hi folks 👋🏾,

I’d like to formally submit my application for one of the community manager positions for Dapr. I’ve been a long time fan and supporter of the project since its release in 2019. During my time at Microsoft, I worked alongside the Dapr team and members of my own to dogfood the developer experience, build demos, and help promote its use throughout the developer community.

Since that time I’ve continued to deliver conference talks and randomly pop up in the discord channel to help answer questions; more so around the .NET SDK. I’d love the opportunity to continue to support the community in other ways.

Recorded Dapr Talks
- [Exploring Pub/Sub messaging with Dapr](https://www.youtube.com/watch?v=1dqe1k-FXJQ) 
- [Building Microservices with Dapr and .NET](https://www.youtube.com/watch?v=VumVciZtLjc)  
- [Zero to hero with Dapr](https://www.youtube.com/watch?v=AAQSShtl9S0)
- [Add a little Dapr to your .NET Microservices](https://www.youtube.com/watch?v=g-gOlkD9lKs)

Related: [#396](https://github.com/dapr/community/issues/396)

**Comment by marcduiker** [comment]
Thank you for applying @cecilphillip! The Dapr STC will select the community manager end of December.

**Comment by marcduiker** [comment]
Hi @cecilphillip, can you please email me at marc@diagrid.io, so I can inform you about your community manager application?

**Comment by marcduiker** [comment]
@cecilphillip has accepted the role and an invitation is sent to start the onboarding.
