### ISSUE TITLE
Application for Dapr community manager (Alex)

### ISSUE THREAD

**Issue by iamalexmang** [dapr/community#413]
Hi, friends! 👋

It is my absolute pleasure to be able to proudly submit my self-nomination for the Dapr Community Manager role.

## 🏖️ "Aren't you busy enough, Alex?" 

Besides my appreciation for Dapr ever since I first learnt about it in 2019 (same year I delivered my first Dapr talk, at CloudBrew in Belgium) and my support for the technology, product and team, I am an avid developer and advocate constantly ensuring it is encompassed in most of the products my team and I are responsible for. 

It should come as no surprise that one of my most viewed conference video-recordings is on Dapr ([my talk at dotnetdays in February 2020](https://www.youtube.com/watch?v=a2OZ0VI4JTg), when in-person events were still a thing).

All of these, as well as my advocacy for Dapr and generally-speaking, well writen code, made me believe that the Community Manager role is not only a role I'd pursue, but also one that would fit me perfectly.

## 😎 What recommends me for the role? 

By the time of this writing, there are already three fantastic submissions for the role, all submitted by strong personalities and well respected authorities in the community. They've done more than anyone could ever ask for in terms of raising, fostering, and supporting a community. They deserve nothing than everyone's respect and I'm humble to know some of them personally and even call friends. As a community member and avid Dapr user I couldn't be happier with either of them representing Dapr as Community Managers.

Nevertheless, I strongly believe that my background as a Dapr developer and a seasoned distributed systems and messaging architect aid in the process of understanding the typical developer's pain points in context to Dapr's strong points. This, as well as my Microsoft MVP experience, helped me remain constantly engaged and has in turn helped others by having their questions answered.

Additionally, my experience overseeing and managing hundreds of diverse software development projects stand as proof of my ability to manage and delegate, as does [Global Azure](https://globalazure.net/), a community-driven effort I am responsible for globally, alongside with other 6 amazing community members). Moreover, Global Azure helped me stay connected with thousands of cloud enthusiasts worldwide, among which some are also Dapr users.

Last but not least, my public speaking engagements (over a couple dozen conference presentations delivered in the last half-decade) recommend me as a person highly capable of building good networking and relationships. Additionally, my partnership with [Microsoft Developer](https://www.youtube.com/@MicrosoftDeveloper/search?query=mang) on supporting the community-driven effort of Learn Live proves yet again my ability to moderate a live-stream, remain engaged even in the most stressful situations and take quick decisions to ensure a high-quality spotless live presentation.

## 💬 Let's chat! 

In the remaining months of 2023 I will deliver two more Dapr talks, one in Amsterdam (NL) at [ESPC 23](https://www.sharepointeurope.com/conference/speakers/alex-mang-microsoft-regional-director-mvp/), and the other one in Mechlen (BE) at [CloudBrew 2023](https://www.cloudbrew.be/#session-your-microservices-supercharged-). Should you be in the neighborhood, please stop by and say 'Hi' 👋.

---
relates to #396

**Comment by marcduiker** [comment]
Thank you for applying @iamalexmang! The Dapr STC will select the community manager end of December. I'll see you at CloudBrew :).
