### ISSUE TITLE
Community Manager Application (Will Velida)

### ISSUE THREAD

**Issue by willvelida** [dapr/community#414]
Hi everyone!

Raising this issue to formally apply for one of the community manager positions for Dapr! 🚀

## Who are you? 🤔

I'm Will, I'm a Lead Software Engineer for Mantel Group based in Melbourne, Victoria, Australia 🦘 Prior to that I was a Customer Engineer for Microsoft, working in the Fast Track for Azure team. I have also been a Microsoft MVP, and I'm also an average Aussie Rules and Rugby player 🏉

## Why you? 🫵

I've been a user and fan of Dapr since it's release.  Over the past few years, I've given a number of talks and workshops on Dapr, teaching developers across the world about Dapr, written blog posts on how to use Dapr, and created samples that showcase Dapr and shared them with the community via my GitHub (as well as raise [the odd contribution to the Dapr docs](https://github.com/dapr/docs/pull/2280)).

I have been a Microsoft MVP, where I have helped organize communities in the ANZ region, such as the [Aotearoa Azure User Group](https://www.meetup.com/auckland-azure-usergroup/), [The Auckland Connected System User Group](https://www.meetup.com/auckland-connected-systems-user-group/) and the [Azure Cosmos DB Global User Group](https://www.meetup.com/azure-cosmos-db-global-user-group/).

My motivation for applying for a community manager role is to see the Dapr framework grow! I believe that the Dapr framework simplifies the building of distributed applications, and helps developers be more productive when building distributed apps. I want to highlight the awesome things the Dapr community are building, help others overcome roadblocks they encounter when using Dapr and create a safe-space for developers of all skills and backgrounds to come and share their knowledge, questions and insights on Dapr 🚀

In my career, I've given numerous workshops and talks on Dapr, and have written blog posts and samples that I've shared with the community. Some of which I've highlighted below 👇

### Workshops 🎓

I've given two workshops this year on building applications using the Dapr framework:

- [Building portable and reliable microservices with the Dapr Framework and Azure - Cloud Native Summit ANZ 2023](https://www.cloudnativesummit.co/Building-portable-and-reliable-microservices-with-the-Dapr-Framework-and-Azure.html)
- [Building Applications with Azure Container Apps - Techorama Belgium 2023](https://techorama.be/workshops/building-applications-with-azure-container-apps/)

### Conference/meetup talks 🎙️

I've spoken at a variety of different conferences and meetups in the ANZ region and across the world

- [Developing and Deploying Containers and Microservices with Azure Container Apps - NDC Sydney 2022](https://www.youtube.com/watch?v=ILH1tJp0Vac&ab_channel=NDCConferences)
- [Developing and Deploying Microservices with Azure Container Apps - Global Azure London 2023](https://www.youtube.com/watch?v=qjVcH53-1SI&ab_channel=MicrosoftReactor)
- [Developing and Deploying Microservices with Azure Container Apps - Microsoft Reactor ANZ 2022](https://www.youtube.com/watch?v=1PgUhyV1wc0&ab_channel=MicrosoftReactor)

### Dapr Samples 🖥️

- [Dapr Resources](https://github.com/willvelida/dapr-resources) - Includes samples on Cron Jobs, Pub/Sub and State Management.

### Blog posts 📝

I blog quite a bit on my [website](https://www.willvelida.com/), but here's some Dapr-related blogs that I've written:

- [Implementing Dapr Pub/Sub functionality to ASP.NET Core Web APIs](https://www.willvelida.com/posts/dapr-pub-sub-asp-net-core/)
- [Building Simple Dapr Cron Jobs with ASP.NET Core Web APIs](https://www.willvelida.com/posts/dapr-simple-cron-jobs/)
- [Implementing Dapr State Management in ASP.NET Core Web APIs](https://www.willvelida.com/posts/dapr-state-management-asp-net-core/)
- [Dapr Service Invocation with Azure Container Apps](https://www.willvelida.com/posts/dapr-service-invocation-container-apps/)

## Want to find out more? ✅

If you want to ask me a question about my application, or just want to chat, feel free to [send me a tweet or Xeet on Twitter/X](https://twitter.com/willvelida), chat to me [where the Sky is Blue](https://bsky.app/profile/willvelida.bsky.social) or [connect with me on LinkedIn](https://www.linkedin.com/in/willvelida/). I'd love to have a chat with you!

relates to #396

**Comment by marcduiker** [comment]
Thank you for applying @willvelida! The Dapr STC will select the community manager end of December.

**Comment by marcduiker** [comment]
Hi @willvelida, can you please email me at marc@diagrid.io, so I can inform you about your community manager application?
