### ISSUE TITLE
REQUEST: New membership for @sadath-12

### ISSUE THREAD

**Issue by sadath-12** [dapr/community#419]
### GitHub Username

@sadath-12

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- [x] https://github.com/dapr/dapr/pull/7271 
- [x] https://github.com/dapr/components-contrib/pull/3243
- [x] https://github.com/dapr/components-contrib/pull/3241
- [x] https://github.com/dapr/dapr/pull/7177
- [x] https://github.com/dapr/dapr/pull/7175 
- [x] https://github.com/dapr/components-contrib/pull/3223

**Comment by ItalyPaleAle** [comment]
+1

**Comment by cicoyle** [comment]
+1 nonbinding

**Comment by artursouza** [comment]
+1

**Comment by artursouza** [comment]
Invite sent.

**Comment by sadath-12** [comment]
thank you 🤝😃
