### ISSUE TITLE
Maintainer Request .NET SDK: Add Phillip Hoff

### ISSUE THREAD

**Issue by halspang** [dapr/community#433]
Nominating @philliphoff to become a maintainer in the [.NET SDK](https://github.com/dapr/dotnet-sdk). 

He has been assisting me in the repo for some time now and has already taken on a role reviewing and authoring PRs. I would like him to have the official role in the repo which will also help me address the community needs and requirements faster.

**Comment by artursouza** [comment]
This needs to be done via e-mail first where maintainers of .Net SDK approves it. Unless the existing .Net SDK maintainers want to vote publicly here.

**Comment by halspang** [comment]
When I spoke with @yaron2, he said that since I'm the only maintainer in the repo it would need to be an issue and then voted on it by the STC.

**Comment by msfussell** [comment]
This was voted on by the Dapr STC at the Jan meeting https://github.com/dapr/community/issues/423  and Phillip was accepted as a maintainer to the .NET SDK repo.

**Comment by artursouza** [comment]
OK. Adding @philliphoff

**Comment by artursouza** [comment]
@philliphoff should have received an invite to join the Dapr org and the Members and .Net SDK maintainers groups.

**Comment by berndverst** [comment]
Congrats @philliphoff

**Comment by msfussell** [comment]
Closing issue.
