### ISSUE TITLE
REQUEST: Approver status for @elena-kolevska in python-sdk

### ISSUE THREAD

**Issue by berndverst** [dapr/community#435]
As the sole Python SDK maintainer I intend to make [elena-kolevska](https://github.com/elena-kolevska) an approver of the Python SDK.

This issue serves as the mandatory one week notice for maintainers to object.

### GitHub Username

[elena-kolevska](https://github.com/elena-kolevska)

**Comment by artursouza** [comment]
+1

**Comment by berndverst** [comment]
As the sole maintainer this doesn't need any votes :) We just need to make sure there are no objections within a week.

**Comment by artursouza** [comment]
Added @elena-kolevska to list of approvers of Python-SDK. Congrats, @elena-kolevska! Thanks @berndverst for reviewing PRs, issues and supporting Elena.

**Comment by elena-kolevska** [comment]
Thank you guys 🙏
