### ISSUE TITLE
REQUEST: Remove maintainer status at components-contrib for @artursouza

### ISSUE THREAD

**Issue by artursouza** [dapr/community#437]
### GitHub Username

@artursouza

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

I would like to be removed from maintainer status at components-contrib repo. Please, do not add me as an approver, just remove from the maintainers' list at components-contrib. My goal is to dedicate my time to runtime and java-sdk repositories.

**Comment by shubham1172** [comment]
I think we should consider having an "emeritus" maintainer position (like http://technosophos.com/2018/01/11/introducing-helm-emeritus-core-maintainers.html). What do you think @artursouza?

**Comment by yaron2** [comment]
I think it's a requirement for us to have emeritus status per CNCF guidelines.

**Comment by artursouza** [comment]
LGTM. Let me create an issue for this and STC can vote.

**Comment by berndverst** [comment]
I think we should remove all inactive approvers and maintainers after 6 months. And after 3 months we send a warning or something like that.

As for Emeritus maintainer - I commented on that issue - it's really just a shoutout to former maintainers in the respective repo's Readme. Nothing else, right?

**Comment by yaron2** [comment]
>  it's really just a shoutout to former maintainers in the respective repo's Readme. Nothing else, right?

Correct

**Comment by artursouza** [comment]
> I think we should remove all inactive approvers and maintainers after 6 months. And after 3 months we send a warning or something like that.

Please, create a separate issue for that discussion. The scope of this issue is well defined.

**Comment by artursouza** [comment]
Done. Removed myself.

It has been great helping with components-contrib in the past 4 years and proud to have helped onboard 2 more maintainers that have been doing an amazing job there. Thanks!
