### ISSUE TITLE
REQUEST: Remove artursouza from approvers in Python SDK

### ISSUE THREAD

**Issue by artursouza** [dapr/community#439]
### GitHub Username

artursouza

Please, remove myself from the list of approvers for Python-SDK as I am no longer active in that repository and don't intend to pursue maintainer status or keep my current approver status.

**Comment by berndverst** [comment]
We should also look into automatically removing approvers and maintainers who are inactive in a given repo. Maybe an automated warning after 3 months and after 6 months of complete inactivity we remove them. That's a pretty low bar.

**Comment by artursouza** [comment]
> We should also look into automatically removing approvers and maintainers who are inactive in a given repo. Maybe an automated warning after 3 months and after 6 months of complete inactivity we remove them. That's a pretty low bar.

Please, start a different issue for this topic. The scope for this issue is small and well defined.

**Comment by artursouza** [comment]
Done. Removed myself.

It was great helping the Python SDK in the early days with the original author and then help a new maintainer come in to continue the amazing work.
