### ISSUE TITLE
Approver nomination for the Go-SDK: @mikeee

### ISSUE THREAD

**Issue by yaron2** [dapr/community#440]
I'd like to nominate @mikeee to become an approver in the Go-SDK. Having worked with Mike on the SDK for a long while I think he would make a great approver, having reviewed many community PRs, committing to the project over time and taking on large initiatives such as Workflows for Go.

**Comment by artursouza** [comment]
My vote does not count, but show my support anyway: +1

**Comment by msfussell** [comment]
+1 non-binding

**Comment by msfussell** [comment]
@skyao @daixiang0

**Comment by yaron2** [comment]
Completed
