### ISSUE TITLE
REQUEST: Remove @artursouza and @msfussell as approvers for CLI

### ISSUE THREAD

**Issue by artursouza** [dapr/community#442]
It has been a great journey in the past 4 years and see the Dapr's open governance taking shape. The CLI was a special one as the maintainers and approvers that have joined in the past 2 years are just doing an amazing work there. I appreciate everything you are all doing for the CLI. Shoutout to @pravinpushkar and @shubham1172.

Now, it's time for me to focus my energy on runtime and Java SDK. Thanks!

**Comment by msfussell** [comment]
Remove both @msfussell and @artursouza from approver group
