### ISSUE TITLE
REQUEST: Remove @artursouza as approver for docs

### ISSUE THREAD

**Issue by artursouza** [dapr/community#443]
It has been a great journey in the past 4 years and see the Dapr's open governance taking shape. The Dapr Docs is a big part of the project's success. I am happy to have helped approve PRs in Dapr Docs and now there are plenty of super talented people taking care of it.

Now, it's time for me to focus my energy on runtime and Java SDK. Thanks!

**Comment by msfussell** [comment]
+1

**Comment by msfussell** [comment]
@artursouza  removed from docs repo.
