### ISSUE TITLE
PROPOSAL: archive sig-sdk-spec in favor of proposals repo

### ISSUE THREAD

**Issue by artursouza** [dapr/community#444]
We did not have much progress in the sdk-spec SIG. We had many other priorities that took over our time and left the sdk-spec idle. Although I still believe we should have an sdk-spec, I noticed that the `proposals` repo is serving as a tool to drive consistency across SDKs with a much smaller process overhead.

Long story short, I propose we archive the sig-sdk-spec and drive consistency across SDKs via proposals in the `proposals` repo.

**Comment by msfussell** [comment]
Will raise this in the April STC meeting. See https://github.com/dapr/community/issues/465

**Comment by msfussell** [comment]
STC - Approves the removal of this SIG.

**Comment by msfussell** [comment]
Archived https://github.com/dapr/sig-sdk-spec
