### ISSUE TITLE
Approver nomination for the Docs repo: @marcduiker 

### ISSUE THREAD

**Issue by msfussell** [dapr/community#447]
I'd like to nominate @marcduiker to become an approver in the docs repo. Marc has contributed to many of the Dapr workflow docs, including details on the usage and updated diagrams. More recently he has provide updated contributor guidance, a devcontainer and a getting started video to improve the onboarding experience for new people wanting to contribute to the docs repo.

Marc's PRs - https://github.com/dapr/docs/pulls?q=is%3Apr+is%3Aclosed+author%3Amarcduiker
Marc's Issues raised - https://github.com/dapr/docs/issues?q=+is%3Aissue+author%3Amarcduiker+

Marc will be able to bring a balanced view to the docs and due to his contributor guidance updates, understand the expectations required for an approver.

**Comment by greenie-msft** [comment]
+1 in favor of @marcduiker as a docs approver.

**Comment by artursouza** [comment]
+1 non-binding

**Comment by hhunter-ms** [comment]
+1 in favor

**Comment by msfussell** [comment]
@marcduiker Added to the docs repo
