### ISSUE TITLE
Update Maintainers and STC Membership

### ISSUE THREAD

**Issue by msfussell** [dapr/community#456]
**STC**
- Hal Spang has taken the STC seat for MSFT https://github.com/dapr/community/blob/master/steering-and-technical-committee-charter.md replacing John Ewart who resigned on 16th January 2024.

**Maintainers no longer active and have been asked to be removed**
- Ryan Nowak (Microsoft) [@rynowak](https://github.com/rynowak) (Removed from .NET Repo)
- Amulya Varote (Microsoft) [@amulyavarote](https://github.com/amulyavarote) (Remove from Quickstarts Repo)

**The following maintainers have been added**
- @philliphoff (Added to .NET Repo)
- @JoshVanL (Added to Dapr/Dapr runtime)
- @mikeee (Added for Rust SDK Maintainer)

As as result of this update give access rights to Discord, 1Password, added to the CNCF mailing list and the CNCF Dapr Maintainers list along with updating https://github.com/dapr/community/blob/master/MAINTAINERS.md

Tasks
- [x] Update Maintainers doc on Google Drive (@marcduiker)
- [x] Update Maintainers.md in this repo (@marcduiker)
- [x] Update [CNCF project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) (@marcduiker) https://github.com/cncf/foundation/pull/778
- [x] Message CNCF about emails to add/remove for mailing lists (@marcduiker) https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2255?created=true

**Comment by artursouza** [comment]
Also need to add @philliphoff to list of maintainers in CNCF.

**Comment by mikeee** [comment]
#457 - small update for your eyes @msfussell

**Comment by msfussell** [comment]
Completed
