### ISSUE TITLE
Request for graduation of sandbox project: Dapr Kubernetes Operator

### ISSUE THREAD

**Issue by yaron2** [dapr/community#459]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios. Highlight changes from the original vision.

> A Kubernetes Operator streamlines the deployment experience of Dapr on both OpenShift and cloud based Kubernetes clusters. It gives ops teams a CI/CD and GitOps friendly way to manage Dapr and encapsulates a lot of the best practices users need to know when using Helm directly

2. Who are the maintainers for the project and corresponding employers?

- Mauricio Salatino, Diagrid
- Luca Burgazzoli, Red Hat

3. Describe 3 users with 1 scenario each in production.

> The Dapr Operator is used by well over 10 different companies from the Red Hat OpenShift Marketplace

4. Which automated tests are implemented in the project (unit tests, end-to-end tests, performance tests, stress tests, etc). Please, provide a link to most recent test runs.

> The operator is tested and validated end-to-end in the OpenShift marketplace using the OpenShift Operator Lifecycle Manager

5. Provide usage scenarios samples, documentation and future milestone plans.

> Scenarios include operating Dapr using CI/CD systems such as Tekton Pipelines, Flux, ArgoCD which utilize CRDs to control the lifecycle of Dapr on Kubernetes. Documentation is self contained within the repository.

**Comment by msfussell** [comment]
The Dapr STC voted to move this repo to the Dapr Org in the March STC meeting. Actions
1) @yaron2 - To move the repo
2) @salaboy - To work with Luca from RedHat to get this updated accordingly

**Comment by msfussell** [comment]
Both actions items completed above. Repo moved and Luca/Mauricio added as maintainers to the repo
