### ISSUE TITLE
REQUEST: New membership for @cvictory

### ISSUE THREAD

**Issue by cvictory** [dapr/community#46]
### GitHub Username

@cvictory

I'm working for Alibaba / Alicloud, we are now trying to apply dapr in Alibaba internal system and AliCloud. My team had a meeting with @yaron2  and I look forward to making more contributions to the dapr community.

### Requirements

- [ x ] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ x ] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [ x ] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
[dapr prs](https://github.com/dapr/dapr/pulls?q=+is%3Apr+author%3Acvictory+ )
[dapr component contrib](https://github.com/dapr/components-contrib/pulls?q=+is%3Apr+author%3Acvictory+)

- Issues responded to
[dapr proposal](https://github.com/dapr/dapr/issues?q=+is%3Aissue+author%3Acvictory+)

**Comment by yaron2** [comment]
I support this request.

/cc @artursouza

**Comment by artursouza** [comment]
I support this request.

**Comment by yaron2** [comment]
Request has been sent, please check now.
