### ISSUE TITLE
REQUEST: Revoke @pkedy approver status

### ISSUE THREAD

**Issue by artursouza** [dapr/community#461]
I have removed @pkedy from the following groups since keeping inactive users with write access is a security concern. This issue is for STC to vote on revoking @pkedy as an official approver in Dapr in these repositories.

- approvers-components-contrib
- approvers-cli

**Comment by msfussell** [comment]
Acknowledge. Will raise this in the April STC for visibility https://github.com/dapr/community/issues/465
