### ISSUE TITLE
REQUEST: Revoke @CodeMonkeyLeet approver status

### ISSUE THREAD

**Issue by artursouza** [dapr/community#462]
I have removed @CodeMonkeyLeet from the following groups since keeping inactive users with write access is a security concern. This issue is for STC to vote on revoking @CodeMonkeyLeet as an official approver in these repositories.

- approvers-components-contrib

**Comment by msfussell** [comment]
Acknowledge. Will raise this in the April STC for visibility https://github.com/dapr/community/issues/465
