### ISSUE TITLE
Update Administrator term to be 2y

### ISSUE THREAD

**Issue by artursouza** [dapr/community#464]
My admin term is 2y but the original proposal was for 6mo, so I ask STC to update the terms so we don't need to have frequent voting to renew administrators: https://github.com/dapr/community/blob/master/ADMINISTRATORS.md

**Comment by msfussell** [comment]
@artursouza - Agreed. Can you create a PR for this update?

**Comment by yaron2** [comment]
Ping @artursouza

**Comment by artursouza** [comment]
PR opened: https://github.com/dapr/community/pull/492
