### ISSUE TITLE
April 2024 Steering and Technical Committee (STC) meeting

### ISSUE THREAD

**Issue by olitomlinson** [dapr/community#465]
Date: Wed April 17th 2024 @ 10:00pm PST (Pacific),  April 18th 2023 @ 6:00am UK @ 2:00pm China

**Attendees**
@msfussell (Diagrid)
@yaron2 (Diagrid)
@daixiang0 (Intel)
@halspang (Microsoft)

**Decline/Not present**
@olitomlinson (Dotmatics)
@paulyuk (Microsoft) 
@jackzhao (Alibaba)

## Action items and notes from previous meetings
[March 2023 Steering and Technical Committee (STC) meeting](https://github.com/dapr/community/issues/425)

Add agenda items in the comments below 

## Agenda and Notes
1) @olitomlinson - I would like to reopen discussions about being more direct about the future deprecation of the Query API.
Action: Deferred this to the next STC on the 15th May.

2) @yaron2 - Vote on Dapr Shared to move from Sandbox to Dapr Org. https://github.com/dapr/community/issues/474
Action: @yaron2 described this proposal and will send out a vote to close 1 week from today to STC members

3) @msfussell - Removal of inactive users from Dapr Groups - https://github.com/dapr/community/issues/445
There are people who are no longer active in Dapr and these people should be automatically removed
Action: This was approved by the STC to have the script to automatically removed inactive people from team security groups
   - https://github.com/dapr/community/issues/462
   - https://github.com/dapr/community/issues/461
   - https://github.com/dapr/community/issues/442
   - https://github.com/dapr/community/issues/453
   - Others to review - Removed @rynowak from .NET SDK
   
4) @msfussell  - Archive sig-sdk-spec in favor of proposals repo of the https://github.com/dapr/community/issues/444
Action: This was approved by the STC to archive the sig-sdk-spec in favor of proposals

5) @msfussell - (Re)Nomination for Marc Duiker as Community Manager https://github.com/dapr/community/issues/470
Action: @marcduiker was approved by the STC for another 1 year as a community manager

**Comment by olitomlinson** [comment]
**Agenda Item**

I would like to reopen discussions about being more direct about the future deprecation of the Query API.

IMO It's not good that users are continuing to adopt it and hitting issues, while being unaware that there is no appetite to support it.

**Comment by artursouza** [comment]
> **Agenda Item**
> 
> I would like to reopen discussions about being more direct about the future deprecation of the Query API.
> 
> IMO It's not good that users are continuing to adopt it and hitting issues, while being unaware that there is no appetite to support it.

I agree with that item. We need someone to have the time commitment to fix this. I am dedicating most of my business hours working on the distributed scheduler, which (AFAIK) wins in priority when compared to the document store API (which, AFAIK, is the vision to fix this issue).

**Comment by marcduiker** [comment]
Agenda item proposal: #470

**Comment by msfussell** [comment]
The meeting occurred and notes captured
