### ISSUE TITLE
REQUEST: Approver access for pkedy to dapr/components-contrib

### ISSUE THREAD

**Issue by pkedy** [dapr/community#47]
### GitHub Username

[pkedy](https://github.com/pkedy)

Requesting approver access to [`dapr/components-contrib`](https://github.com/dapr/components-contrib).

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs [reviewed](https://github.com/dapr/components-contrib/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me+-author%3Apkedy) / [authored](https://github.com/dapr/components-contrib/pulls?q=is%3Apr+author%3Apkedy+is%3Aclosed)
- Issues [responded to](https://github.com/dapr/components-contrib/pulls?q=is%3Aissue+commenter%3Apkedy)

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
I support this.

**Comment by pkedy** [comment]
This was done. Thanks!
