### ISSUE TITLE
Self (re)nomination for Dapr Community Manager

### ISSUE THREAD

**Issue by marcduiker** [dapr/community#470]
My Community Manager term ended last February. I hereby self nominate for another year of being a Dapr Community Manager (CM).

As a Dapr CM during the last year I:

- Hosted many Dapr Community Calls.
- Reached out to Dapr (end) users for Community Call sessions and CNCF case studies. 
- Started a new section in the Community Call called _show-and-tell_ where we highlight community contributions found on social media.
- Managed and contributed to the Dapr website redesign.
- Created content to explain how to contribute to the Dapr docs.
- Created a handbook for new Dapr Community Managers.
- Organized and co-hosted Dapr Day in Feb 2024.
- Created a new Dapr OSS slide deck.
- Started with a community championship program by using digital badges to award community contributions. The [community supporter badge](https://www.holopin.io/sticker/clo41x3yv150610flaripifeqm) has been claimed 276 times.

**Comment by msfussell** [comment]
Renomination approved by the STC.
