### ISSUE TITLE
REQUEST: @cicoyle as approver od dapr/java-sdk

### ISSUE THREAD

**Issue by artursouza** [dapr/community#473]
### GitHub Username

@cicoyle as an approver in dapr/java-sdk

### List of contributions

Highlights
* https://github.com/dapr/java-sdk/pull/1003
* https://github.com/dapr/java-sdk/pull/998
* https://github.com/dapr/java-sdk/pull/981
* https://github.com/dapr/java-sdk/pull/918
* https://github.com/dapr/java-sdk/pull/913
* https://github.com/dapr/java-sdk/pull/947 (reviewer)
* https://github.com/dapr/java-sdk/pull/949 (reviewer) 

### Nomination

Nominated by @artursouza. @cicoyle has authored and reviewed some relevant PRs for Java-SDK, and has been a core contributor to the Java SDK overall quality improvements.

**Comment by artursouza** [comment]
+1 binding

**Comment by mukundansundar** [comment]
+1 binding

**Comment by artursouza** [comment]
Thanks. Cassie is now an approver of Java SDK.
