### ISSUE TITLE
Request for graduation of sandbox project: Dapr Shared

### ISSUE THREAD

**Issue by yaron2** [dapr/community#474]
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios. Highlight changes from the original vision.
> Running Dapr as a shared instance allows users to save memory as Dapr does not need anymore an instance per Pod. Furthermore, this allows Dapr to better run in serverless or FaaS based environments where multiple instances of the same function or compute unit can share the same Dapr instance, and their lifecycle is completely separate than Dapr.

2. Who are the maintainers for the project and corresponding employers?
> Mauricio Salatino, Diagrid

3. Will any maintainer stop contributing in case of employment change?
> No

**Comment by yaron2** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 binding

**Comment by olitomlinson** [comment]
+1 binding

**Comment by yaron2** [comment]
Thank you STC members, this vote is now closed in favor of graduating Dapr Shared
