### ISSUE TITLE
July 24th 2024, Community Meeting Agenda

### ISSUE THREAD

**Issue by marcduiker** [dapr/community#490]
## 📞 Dapr Community Meeting

Every two weeks we host a [community meeting](../#community-meetings) to highlight community created content, showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion among the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on <Date>, at 9 AM PST ([See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240724T09&p1=234&msg=Dapr+Community+Call)). The meeting agenda is finalized by a Community Call Host prior to the meeting.

We'll be live-streaming to [YouTube](https://www.youtube.com/@DaprDev/streams). See you at the community call! 👋

## Agenda

- Introduction
- Session 1: Service invocation with gRPC proxy in Java by @artursouza 
- Session 2: Dapr Scheduler API by @cicoyle 
- Dapr news / Show & tell
- Open discussion
- Closing

 <details>
    <summary>Checklists for the host</summary>

### Before the meeting

- [ ] Find speakers
- [ ] Collect Dapr news (blog posts & videos found on social media, and show-and-tell Discord channel)
- [ ] Prepare slide deck
- [ ] Send meeting invite to the speakers
- [ ] Announce the meeting on social media
  - [ ] 1 week before
  - [ ] 1 day before
  - [ ] 1 hour before

### During the meeting

- Welcome & announce that the meeting will be recorded
- Start the recording
- Show the agenda
- Welcome first speaker
- First session
- Q&A first session
- Welcome second speaker
- Second session
- Q&A second session
- Show Dapr related news, posts, videos.
- Open discussion
- Closing & mention Dapr Discord channel

### After the meeting

- [ ] Upload the meeting to YouTube
- [ ] Add chapters to the video
- [ ] Add links to the video description
  - [ ] Read-only link to slides
  - [ ] [Dapr Discord link](http://bit.ly/dapr-discord)
  - [ ] Other relevant links related to the sessions
- [ ] Announce the published video on social media
- [ ] Close this issue

</details>

**Comment by paulyuk** [comment]
I can present or co-present "Contributing to, testing, and debugging Quickstarts" for this July 24th meeting.  July 10th is too soon unfortunately.

@cecilphillip @AnnuCode @marcduiker @msfussell

**Comment by msfussell** [comment]
Will have someone (@cicoyle or @rochabr ) present to the Jobs API in the v1.14 release with a quickstart demo

**Comment by leecalcote** [comment]
Hi All, if there happens to be time on tomorrow’s meeting agenda for a presentation and discussion of Meshery’s integration with Dapr, contributors of Meshery, who have been collaborating with @salaboy, would love to join and chat on the topic, if you’ll have us. 

Topic: Meshery ❤️ Dapr
1. Modeling of Meshery relationships of each Dapr resource. 
1. Meshery as the [CNCF Hub](https://docs.google.com/presentation/d/1OqY5EvYYxj91MFEwoMaJVLyStDX9rTc7CyiF4w6qbNA/edit#).
1. Empowering Dapr maintainers to curate and approve verified reference architectures in the [catalog](https://meshery.layer5.io/catalog). 

@innocentrda @muzairs15 @aabidsofi19 @captain-akshay @deepak4566 @alero-awani @dragon-slayer875 @humblenginr @jougan-0 @ctcarrier

**Comment by cecilphillip** [comment]
@paulyuk sounds good to me. Let's get it on the agenda. Did you want to do this solo or was there someone else in mind?

@msfussell will this be another short update like Mike's Dapr 1.14 release or a full 20mins. Asking so I can know if we'll be able to fit another session in on this date.

**Comment by cecilphillip** [comment]
> Hi All, if there happens to be time on tomorrow’s meeting agenda for a presentation and discussion of Meshery’s integration with Dapr, contributors of Meshery, who have been collaborating with @salaboy, would love to join and chat on the topic, if you’ll have us.

@leecalcote  This sounds like an interesting session. Let's see if we can git this in

**Comment by yaron2** [comment]
@leecalcote can you confirm you'll be participating in this week's community call?
