### ISSUE TITLE
REQUEST: Dapr runtime approver role for Sky

### ISSUE THREAD

**Issue by yaron2** [dapr/community#51]
I would like to propose @skyao as an Approver of the `dapr/dapr` repository.

@skyao has been a Dapr org member for more than 6 months, is a maintainer of the Go SDK and made sizable contributions including reviews to the Dapr runtime, components-contrib and the Java SDK.

In addition, @skyao demonstrated he has a deep knowledge of Dapr by contributing sizable and impactful PRs for the project, more recently coming up with a very detailed [design proposal](https://github.com/dapr/dapr/issues/2988) for the Configuration API.

**Comment by nobodyiam** [comment]
+1

**Comment by yaron2** [comment]
@artursouza @msfussell we need an approval from either of you (being  a dapr/dapr Maintainer and Steering Committee member respectively) to make sky an Approver.

**Comment by skyao** [comment]
Thank you all very much!

**Comment by rahuahua** [comment]
I approve.

**Comment by codjust** [comment]
+1

**Comment by barrypt** [comment]
1

**Comment by myFirstway** [comment]
I approve.

**Comment by myFirstway** [comment]
I approve.

**Comment by charleszhn** [comment]
I approve.

**Comment by zhchlmm** [comment]
+1

**Comment by chenzuo** [comment]
+1

**Comment by ChenHaoHu** [comment]
great

**Comment by zhonglang115** [comment]
> +1

**Comment by sheng-jie** [comment]
+1

**Comment by pathing** [comment]
+1

**Comment by yaron2** [comment]
@skyao, you have been granted the Approver role in `dapr/dapr`. Congratulations.

**Comment by msfussell** [comment]
I approve.

**Comment by skyao** [comment]
> I approve.

Thank you Mark, thank you Yaron. Thank you everyone.

I'm so glad for this honor.
