### ISSUE TITLE
REQUEST: Remove maintainer status at js-sdk for @shubham1172

### ISSUE THREAD

**Issue by shubham1172** [dapr/community#516]
### GitHub Username

@shubham1172

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

I would like to step down as a JS SDK maintainer. My priorities have changed and I am not able to find bandwidth to contribute as a maintainer. Thank you @XavierGeerinck for nominating and onboarding me as a maintainer and also @DeepanshuA for the work we did together. Cheers!

**Comment by yaron2** [comment]
Done. Thanks for the hard work you put in the SDK over the years.

**Comment by marcduiker** [comment]
Thanks for all your work @shubham1172! <3

**Comment by elena-kolevska** [comment]
Thanks for everything @shubham1172, it was a real pleasure working with you.
