### ISSUE TITLE
REQUEST: Remove membership for @XavierGeerinck

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/community#518]
### GitHub Username

@XavierGeerinck

### Feedback

Hi All! I am sad to announce that I will stepping down as a JS SDK maintainer. Not only was the last year immensely difficult to contribute due to my role as CTO, but I am also seeing a changing ecosystem that makes it hard to live and provide the passion I once had. 

I want the Dapr project to grow and have contributes that can provide both the quality and quantity that I am not able to provide at this moment.

Thank you so much everyone for the nice collaboration, and a huge shout-out to the JS SDK team for making this possible!

**Comment by yaron2** [comment]
Done. Thanks for all the work you did to get the SDK running from scratch.

**Comment by marcduiker** [comment]
Thanks a ton @XavierGeerinck <3

**Comment by artursouza** [comment]
Thanks @XavierGeerinck!
