### ISSUE TITLE
PROPOSAL: create adopters pages for dapr users

### ISSUE THREAD

**Issue by skyao** [dapr/community#52]
We should create adopters pages for dapr users and accepte the PR from users to add them into the user list.  This page should be a part of dapr website. 

It can be two list in this page: one for adopted, one for planning to adapte.

We also should provide a template for this.

**Comment by yaron2** [comment]
Good idea. Do you think the `ADOPTERS` file needs to be in the community repo or `dapr/dapr` repo?

**Comment by skyao** [comment]
> Good idea. Do you think the `ADOPTERS` file needs to be in the community repo or `dapr/dapr` repo?

I would like to add adopters pages in our dapr website so that it will be included in the web site automately, but repo https://github.com/dapr/website is private....

So anyway we need to "copy" the content of adopters pages to web site. 

For community repo or dapr/dapr repo, I found that now community repo is for dapr contributors, not for dapr end users. But I think the end users is also a important part of community, so I suggest to use community repo.

**Comment by skyao** [comment]
> > Good idea. Do you think the `ADOPTERS` file needs to be in the community repo or `dapr/dapr` repo?
> 
> I would like to add adopters pages in our dapr website so that it will be included in the web site automately, but repo https://github.com/dapr/website is private....
> 
> So anyway we need to "copy" the content of adopters pages to web site.
> 
> For community repo or dapr/dapr repo, I found that now community repo is for dapr contributors, not for dapr end users. But I think the end users are also a important part of community, so I suggest to use community repo.

**Comment by msfussell** [comment]
Yes to creating this ADOPTERS.MD file

**Comment by yaron2** [comment]
File is created.
