### ISSUE TITLE
REQUEST: New membership for @rochabr

### ISSUE THREAD

**Issue by rochabr** [dapr/community#520]
### GitHub Username

@rochabr 

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

https://github.com/dapr/quickstarts/pull/1064
https://github.com/dapr/docs/pull/4279

**Comment by paulyuk** [comment]
+1 vote to approve

**Comment by yaron2** [comment]
+1

**Comment by olitomlinson** [comment]
+1

**Comment by mikeee** [comment]
+1

**Comment by msfussell** [comment]
+1

**Comment by rochabr** [comment]
Thank you, everyone
