### ISSUE TITLE
REQUEST: New membership for Arhell

### ISSUE THREAD

**Issue by Arhell** [dapr/community#521]
### GitHub Username

[Arhell](https://github.com/arhell)

I want to work on the sites, fix bugs, make improvements

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- https://github.com/dapr/website/pulls/Arhell
https://github.com/dapr/website/pull/108

- Issues responded to
https://github.com/dapr/website/issues/created_by/Arhell
https://github.com/dapr/website/issues/107

**Comment by Arhell** [comment]
https://github.com/dapr/docs/commits?author=Arhell

**Comment by artursouza** [comment]
@Arhell Invite sent.
