### ISSUE TITLE
REQUEST: Remove Maintainer Role in js-sdk for DeepanshuA

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/community#522]
### GitHub Username

@DeepanshuA 

### Requirements

- [] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

I want to step down from Maintainer Role of js-sdk project.
I am not able to take out time for js-sdk activities anymore due to shift in my Professional and Personal priorities. So, I won't be able to justify for the bandwidth required for this role anymore.
It was fun working with @XavierGeerinck and @shubham1172 on js-sdk.
Thanks!

**Comment by artursouza** [comment]
Thanks for everything you did @DeepanshuA!

**Comment by artursouza** [comment]
Done.
