### ISSUE TITLE
REQUEST: Approver status in dapr/dapr for cicoyle

### ISSUE THREAD

**Issue by artursouza** [dapr/community#526]
@cicoyle as approver in dapr/dapr

PRs:
https://github.com/dapr/dapr/pulls?q=author%3Acicoyle+

Highlights:
- Standardize error messages
  - https://github.com/dapr/dapr/pull/7322
  - https://github.com/dapr/dapr/pull/7768 (this one is worth multiple PRs, it added dist scheduler service + job API)
  - https://github.com/dapr/dapr/pull/7916

PRs reviewed: https://github.com/dapr/dapr/pulls?q=-author%3Acicoyle+involves%3Acicoyle+

Issues created: https://github.com/dapr/dapr/issues?q=is%3Aissue+author%3Acicoyle+

Issues from others contributed to: https://github.com/dapr/dapr/issues?q=is%3Aissue+-author%3Acicoyle+involves%3Acicoyle

Sponsor: @artursouza

**Comment by artursouza** [comment]
+1 binding

**Comment by JoshVanL** [comment]
+1 binding
