### ISSUE TITLE
Steering and Technical Committee (STC) meetings

### ISSUE THREAD

**Issue by dims** [dapr/community#530]
- Are these meetings always private?
- Do you open some of these meetings to be public?
- If so, do you publish recordings of the public STC meetings?

Would you consider holding some public STC meetings?

xref: https://github.com/cncf/toc/issues/1354

**Comment by yaron2** [comment]
> Are these meetings always private?

Its a private invite, but community members are invited proactively by STC to these meetings when needed

> Do you open some of these meetings to be public?

Yes, when there's a specific topic to discuss with the broader community

> Would you consider holding some public STC meetings?

Yes, we can allocate every other meeting to be made publicly accessible.

**Comment by yaron2** [comment]
@dims can this be closed? we took an action item to hold several STC public meetings and announce them before they happen.

**Comment by dims** [comment]
yes, please go ahead and close this
