### ISSUE TITLE
What is a `subproject`?

### ISSUE THREAD

**Issue by dims** [dapr/community#531]
Some docs talk about `subproject`(s) example https://github.com/dapr/community/blob/master/community-membership.md?plain=1#L126

- How do you define subprojects?
- What is the current list of subprojects?
- Are there distinct repositories with its own release cadence?

Do you really mean repositories when you say subprojects?

Can we please document the language and list exactly the current list. thanks

xref: https://github.com/cncf/toc/issues/1354

**Comment by Rockyman-star** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by yaron2** [comment]
The membership doc outlines in the first paragraph that subprojects are synonymous with repositories:

```
... Responsibilities for roles are scoped to these sub-projects (repos).
```

**Comment by yaron2** [comment]
@dims do you feel like we can close this? Re: listing all the repositories, there are over 30 and some are getting added and removed pretty dynamically sometimes. that might present a challenge in regards to updating

**Comment by dims** [comment]
@yaron2 sure. please go ahead and close it.

(I think i was thinking about the sentence that says `The Dapr project is subdivided into sub-projects under (predominantly, but not exclusively) runtime (dapr), components-contrib, CLI, quickstarts, docs and language-specific SDKs.` and hoping that would be sort of delineation instead of repos.)

**Comment by yaron2** [comment]
> @yaron2 sure. please go ahead and close it.
> 
> (I think i was thinking about the sentence that says `The Dapr project is subdivided into sub-projects under (predominantly, but not exclusively) runtime (dapr), components-contrib, CLI, quickstarts, docs and language-specific SDKs.` and hoping that would be sort of delineation instead of repos.)

I'll push a change to make the language clearer

**Comment by yaron2** [comment]
Improved with https://github.com/dapr/community/pull/540.
