### ISSUE TITLE
Failure to restart AKS service on dapr v1.13.4

### ISSUE THREAD

**Issue by tan-ey** [dapr/community#534]
hi,

We were using dapr v1.13.4 on azure in an azure kubernetes service when we realised that some our services were unable to perform a restart without upgrading to dapr v1.14.1 released on 14 Aug 2024. This behavior was observed on 28 Aug 2024. As we understand, v1.13.4 is still supported at this point. 

We would like to seek advices from the community if this behavior have been observed before and if it is expected or a known issue?

Attached a screenshot of the messages shown on AKS logs when attempting to perform a restart on v1.13.4
![image](https://github.com/user-attachments/assets/a747563d-853b-4609-b838-c9290246a851)

**Comment by yaron2** [comment]
I believe your root certs might have expired. Follow these instructions (using the CLI is recommended) and report back if this is solved: https://docs.dapr.io/operations/security/mtls/#root-and-issuer-certificate-upgrade-using-cli-recommended

**Comment by msfussell** [comment]
Resolved
