### ISSUE TITLE
Location of agenda and meeting notes from the STC meetings?

### ISSUE THREAD

**Issue by dims** [dapr/community#537]
https://github.com/dapr/community/tree/master/steering-and-technical-committee-meetings directory is empty. Is this information stored elsewhere?

Also the link in https://github.com/dapr/community/tree/master/steering-and-technical-committee-meetings#code-of-conduct is broken

**Comment by dims** [comment]
xref: https://github.com/cncf/toc/issues/1354

**Comment by dims** [comment]
Looks like there are STC issues with details... can we update the page with a github query or something then?

**Comment by yaron2** [comment]
Done (fixed broken link, added link to past STC meetings). Great suggestion on the query!
