### ISSUE TITLE
Switch to CNCF Code of Conduct

### ISSUE THREAD

**Issue by dims** [dapr/community#538]
Is the STC very attched to the current text? https://github.com/dapr/community/blob/master/CODE-OF-CONDUCT.md 

We do have a CNCF code of conduct that is used across all CNCF projects, it is adapted from the very same Contributor Covenant as well but tailored to CNCF. Will the STC consider switching?
https://github.com/cncf/foundation/blob/main/code-of-conduct.md

(example https://kubernetes.io/community/code-of-conduct/ just points to the CNCF one)

**Comment by dims** [comment]
xref: https://github.com/cncf/toc/issues/1354

**Comment by yaron2** [comment]
Yes, we can switch - this has been discussed before in STC. Would it be ok to simply link to [this](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) in our existing code of conduct documents?

**Comment by dims** [comment]
@yaron2 yep, linking is ok, but the enforcement/reporting etc should still be in your docs

**Comment by yaron2** [comment]
Fixed via https://github.com/dapr/community/blob/master/CODE-OF-CONDUCT.md.
