### ISSUE TITLE
REQUEST: New membership for @cinience

### ISSUE THREAD

**Issue by cinience** [dapr/community#54]
### GitHub Username

@cinience

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project
dapr/components-contrib#814
dapr/components-contrib#815
dapr/components-contrib#816
dapr/components-contrib#817

**Comment by artursouza** [comment]
Our community membership guidelines states that "Members are continuously active contributors in the community. They can have issues and PRs assigned to them. Members are expected to participate in community discussions and remain active contributors to the community."

Although the contributions above were relevant, my interpretation of the statement above would be that "continuously active contributors" would require more time to be observed before this membership can be approved.

I do not approve this membership as of now.
