### ISSUE TITLE
Update Integration Docs for Vendor Neutrality

### ISSUE THREAD

**Issue by angellk** [dapr/community#541]
Please remove this paragraph from the [Diagrid Conductor](https://docs.dapr.io/developing-applications/integrations/diagrid/diagrid-conductor/) Integration page to ensure vendor neutrality:

> Try out [Conductor Free](https://www.diagrid.io/pricing), ideal for individual developers building and testing Dapr applications on Kubernetes.

**Comment by yaron2** [comment]
Paragraph removed via https://github.com/dapr/docs/pull/4344
