### ISSUE TITLE
REQUEST: @salaboy as approver of dapr/java-sdk

### ISSUE THREAD

**Issue by artursouza** [dapr/community#542]
### GitHub Username

@salaboy as an approver in dapr/java-sdk

### List of contributions

TestContainers and SpringBoot integration added to Java SDK.

- PRs:
https://github.com/dapr/java-sdk/pulls?q=is%3Apr+author%3Asalaboy+is%3Aclosed
- Reviews:
https://github.com/dapr/java-sdk/pulls?q=is%3Apr+-author%3Asalaboy+salaboy

### Nomination

Nominated by @artursouza. @salaboy  has authored and reviewed some relevant PRs for Java-SDK, and has been a core contributor to the Java SDK overall quality improvements.

**Comment by artursouza** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 Non-binding

**Comment by cicoyle** [comment]
+1

**Comment by msfussell** [comment]
Completed and closing
