### ISSUE TITLE
Update maintainers list

### ISSUE THREAD

**Issue by msfussell** [dapr/community#546]
Update https://github.com/dapr/community/blob/master/MAINTAINERS.md due to 
- https://github.com/dapr/community/issues/516
- https://github.com/dapr/community/issues/525
- https://github.com/dapr/community/issues/518
- Mauricio Salatino - Maintainer of the Dapr Shared project - See https://github.com/dapr/community/issues/474

Give access rights to Discord, 1Password, added to the CNCF mailing list and the CNCF Dapr Maintainers list along with updating https://github.com/dapr/community/blob/master/MAINTAINERS.md

Tasks
- [x] Discord (@marcduiker)
- [X] Remove maintainers from 1Password Maintainers Vault (@marcduiker )
- [x] Invite @WhitWaldo and @salaboy to Dapr 1Password (@msfussell)
- [x] Update role in Dapr org teams
- [x] Update Maintainers doc on Google Drive (@marcduiker)
- [x] Update Maintainers.md in this repo (@marcduiker)
- [x] Update [CNCF project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) (@marcduiker) https://github.com/cncf/foundation/pull/778
- [x] Message CNCF about emails to add/remove for mailing lists (@marcduiker) https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2255?created=true

**Comment by marcduiker** [comment]
@msfussell I can't update 1Password access, can you do that please?

**Comment by msfussell** [comment]
@marcduiker - can we include https://github.com/dapr/community/issues/553 in this issue?

**Comment by marcduiker** [comment]
All completed
