### ISSUE TITLE
New Maintainer Onboarding: Whit Waldo

### ISSUE THREAD

**Issue by yaron2** [dapr/community#553]
Whit Waldo (@WhitWaldo) has been added as a Dotnet SDK maintainer. This issue is to capture the different activities needed to onboard him.

**Comment by WhitWaldo** [comment]
If I could be added to the Maintainers list as "Whit Waldo (Innovian)", I'd appreciate it!

**Comment by marcduiker** [comment]
I'll take care of:

- [ ] Add maintainer to [MAINTAINERS.md](https://github.com/dapr/community/blob/master/MAINTAINERS.md).
- [ ] Add maintainer from [CNCF project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv).
- [ ] Add maintainer add _Dapr Maintainers & Community Managers_ doc on Google Drive.
- [X] Add maintainer to _maintainers_ role on Discord. (already done by some-one else)
