### ISSUE TITLE
REQUEST: New membership for Taction

### ISSUE THREAD

**Issue by Taction** [dapr/community#56]
### GitHub Username

@Taction

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored

dapr/components-contrib#763
dapr/components-contrib#769
dapr/components-contrib#804
dapr/components-contrib#823
dapr/components-contrib#832
dapr/components-contrib#835
dapr/components-contrib#868
dapr/components-contrib#842
dapr/components-contrib#859
dapr/components-contrib#860
dapr/components-contrib#862
dapr/docs#1334
dapr/docs#1432
dapr/docs#1447
dapr/docs#1453
dapr/docs#1459

- Issues responded to

dapr/components-contrib#784
dapr/components-contrib#833
dapr/components-contrib#867
dapr/docs#1452

More here:
https://github.com/dapr/docs/issues?q=is%3Aissue+author%3ATaction+is%3Aclosed
https://github.com/dapr/components-contrib/issues?q=+is%3Aissue+author%3ATaction+

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
I approve.

**Comment by yaron2** [comment]
@Taction an invite has been sent, check your associated email.

**Comment by Taction** [comment]
Thank you all for your approval. :tada:
