### ISSUE TITLE
REQUEST: New membership for daixiang0

### ISSUE THREAD

**Issue by daixiang0** [dapr/community#62]
### GitHub Username

@daixiang0

discussed with @mukundansundar @artursouza

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs authored
https://github.com/dapr/dapr/pull/3241
https://github.com/dapr/dapr/pull/3227
https://github.com/dapr/dapr/pull/3205
https://github.com/dapr/dapr/pull/3197
https://github.com/dapr/dapr/pull/3196
https://github.com/dapr/dapr/pull/3195
https://github.com/dapr/dapr/pull/3186
https://github.com/dapr/dapr/pull/3247
https://github.com/dapr/dapr/pull/3227
https://github.com/dapr/dapr/pull/3206
https://github.com/dapr/dapr/pull/3248
https://github.com/dapr/components-contrib/pull/922
https://github.com/dapr/components-contrib/pull/886
https://github.com/dapr/components-contrib/pull/910
https://github.com/dapr/components-contrib/pull/887
https://github.com/dapr/python-sdk/pull/223

- PRs reviewed
https://github.com/dapr/dapr/pull/3202

- Issues responded to
https://github.com/dapr/dapr/issues/3226
https://github.com/dapr/dapr/issues/3240
https://github.com/dapr/go-sdk/issues/168

**Comment by artursouza** [comment]
@daixiang0 Thanks for your contributions. The PRs link only shows PRs for the person that clicks on the link and not yours - please, correct that. Ideally, listing the actual PRs is better because it makes this issue an immutable record.

As per our guidelines, I would like to wait for consistent contributions over a period of time to justify membership.

**Comment by daixiang0** [comment]
update contributions list.  @mukundansundar @artursouza @yaron2

**Comment by yaron2** [comment]
I support this request.

**Comment by artursouza** [comment]
I support this request.

**Comment by daixiang0** [comment]
@yaron2 @artursouza thanks for support!

**Comment by yaron2** [comment]
@daixiang0 you have been invited to the Dapr org. check for an invitation email from GitHub.
