### ISSUE TITLE
REQUEST: New maintainer status for @wcs1only dapr/quickstarts

### ISSUE THREAD

**Issue by wcs1only** [dapr/community#67]
### GitHub Username

@wcs1only

Formally requesting maintainer status for dapr/quickstarts.

Nominations by existing maintainers:
dapr/quickstarts @orizohar 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  - dapr/quickstarts: [reviewed](https://github.com/dapr/quickstarts/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Awcs1only), [authored](https://github.com/dapr/quickstarts/pulls?q=is%3Apr+is%3Aclosed+author%3Awcs1only+). A few selected highlights:
     - dapr/quickstarts#360
     - dapr/quickstarts#415
     - dapr/quickstarts#431

---
- Issues responded to
  - dapr/quickstarts: [issues](https://github.com/dapr/quickstarts/issues?q=is%3Aissue+is%3Aclosed+commenter%3Awcs1only+)

**Comment by orizohar** [comment]
Very much supportive of this! @wcs1only has done really great work on the quickstarts!

**Comment by yaron2** [comment]
Voted and approved.
