### ISSUE TITLE
REQUEST: New maintainer status for @wcs1only dapr/python-sdk

### ISSUE THREAD

**Issue by wcs1only** [dapr/community#68]
### GitHub Username

@wcs1only

Formally requesting maintainer status for dapr/python-sdk.

Nominations by existing maintainers:
@artursouza 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  - dapr/python-sdk: [reviewed](https://github.com/dapr/python-sdk/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Awcs1only), [authored](https://github.com/dapr/python-sdk/pulls?q=is%3Apr+is%3Aclosed+author%3Awcs1only+). A few selected highlights:
    - dapr/python-sdk#171
    - dapr/python-sdk#82
    - dapr/python-sdk#203

---
- Issues responded to
  - dapr/python-sdk: [issues](https://github.com/dapr/python-sdk/issues?q=is%3Aissue+is%3Aclosed+commenter%3Awcs1only+)

**Comment by artursouza** [comment]
I approve this request.

**Comment by yaron2** [comment]
Voted and approved.
