### ISSUE TITLE
REQUEST: Member level access for dmitsh to dapr/dapr and dapr/components-contrib

### ISSUE THREAD

**Issue by dmitsh** [dapr/community#70]
### GitHub Username

@dmitsh

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/docs/pull/1571
https://github.com/dapr/docs/pull/1591
https://github.com/dapr/dapr/pull/3342
https://github.com/dapr/dapr/pull/3307
https://github.com/dapr/components-contrib/pull/947
https://github.com/dapr/components-contrib/pull/948
https://github.com/dapr/components-contrib/pull/942
https://github.com/dapr/cli/pull/745
https://github.com/dapr/cli/pull/746
https://github.com/dapr/go-sdk/pull/171
https://github.com/dapr/go-sdk/pull/172
https://github.com/dapr/go-sdk/pull/178
https://github.com/dapr/quickstarts/pull/451
https://github.com/dapr/quickstarts/pull/449

- Issues responded to
https://github.com/dapr/docs/issues/1568
https://github.com/dapr/docs/issues/1589
https://github.com/dapr/dapr/issues/3341
https://github.com/dapr/dapr/issues/2906
https://github.com/dapr/components-contrib/issues/904
https://github.com/dapr/components-contrib/issues/691
https://github.com/dapr/cli/issues/599
https://github.com/dapr/cli/issues/705
https://github.com/dapr/dashboard/issues/148

**Comment by dmitsh** [comment]
tagging my sponsor @artursouza

**Comment by artursouza** [comment]
I sponsor Dmitry as a member in dapr/dapr and dapr/components-contrib

**Comment by msfussell** [comment]
I sponsor Dmitry as a member in dapr/dapr and dapr/components-contrib
