### ISSUE TITLE
REQUEST: New membership for CodeMonkeyLeet

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/community#73]
### GitHub Username

@codemonkeyleet

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs authored
https://github.com/dapr/dapr/pull/3290
https://github.com/dapr/dapr/pull/3282
https://github.com/dapr/dapr/pull/3278
https://github.com/dapr/dapr/pull/3264
https://github.com/dapr/dapr/pull/3230
https://github.com/dapr/dapr/pull/3193
https://github.com/dapr/components-contrib/pull/975
https://github.com/dapr/components-contrib/pull/936
https://github.com/dapr/components-contrib/pull/917
https://github.com/dapr/quickstarts/pull/436
https://github.com/dapr/docs/pull/1522
https://github.com/dapr/docs/pull/1503
https://github.com/dapr/docs/pull/1502
https://github.com/dapr/docs/pull/1489
https://github.com/dapr/cli/pull/687

- PRs reviewed
https://github.com/dapr/components-contrib/pull/986
https://github.com/dapr/components-contrib/pull/944
https://github.com/dapr/dapr/pull/3248
https://github.com/dapr/dapr/pull/3237
https://github.com/dapr/dapr/pull/3343

- Issues responded to
https://github.com/dapr/dapr/issues/3378
https://github.com/dapr/dapr/issues/3368
https://github.com/dapr/dapr/issues/3362
https://github.com/dapr/dapr/issues/3361
https://github.com/dapr/dapr/issues/3358
https://github.com/dapr/dapr/issues/3339
https://github.com/dapr/dapr/issues/3338
https://github.com/dapr/dapr/issues/3322
https://github.com/dapr/dapr/issues/3320
https://github.com/dapr/dapr/issues/3318
https://github.com/dapr/dapr/issues/3293
https://github.com/dapr/dapr/issues/3268
https://github.com/dapr/dapr/issues/3257
https://github.com/dapr/dapr/issues/3245
https://github.com/dapr/dapr/issues/3208
https://github.com/dapr/dapr/issues/3192
https://github.com/dapr/dapr/issues/3168
https://github.com/dapr/dapr/issues/3079
https://github.com/dapr/dapr/issues/2844
https://github.com/dapr/dapr/issues/2840
https://github.com/dapr/dapr/issues/2483
https://github.com/dapr/dapr/issues/2367
https://github.com/dapr/docs/issues/1408
https://github.com/dapr/components-contrib/issues/974
https://github.com/dapr/components-contrib/issues/964
https://github.com/dapr/components-contrib/issues/943
https://github.com/dapr/components-contrib/issues/928
https://github.com/dapr/components-contrib/issues/913
https://github.com/dapr/components-contrib/issues/895
https://github.com/dapr/components-contrib/issues/894

**Comment by CodeMonkeyLeet** [comment]
@AaronCrawfis @artursouza @pkedy @wcs1only

**Comment by yaron2** [comment]
@CodeMonkeyLeet who are your sponsors?

**Comment by CodeMonkeyLeet** [comment]
> @CodeMonkeyLeet who are your sponsors?

@artursouza though he's out currently, and I'm hoping one of the others in the list will provide a second sponsorship.

**Comment by artursouza** [comment]
I sponsor this request.

**Comment by CodeMonkeyLeet** [comment]
Pinging for @AaronCrawfis @pkedy @wcs1only

**Comment by pkedy** [comment]
I also sponsor this request to add @CodeMonkeyLeet as a member of Dapr.

**Comment by AaronCrawfis** [comment]
I also sponsor this request to add @CodeMonkeyLeet as a member of Dapr.

**Comment by artursouza** [comment]
@yaron2 Can you add @CodeMonkeyLeet  as Dapr member?

**Comment by yaron2** [comment]
Done
