### ISSUE TITLE
REQUEST: New approver status for @greenie-msft dapr/docs

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/community#74]
## PRs contributed to

- https://github.com/dapr/docs/pull/1501
- https://github.com/dapr/docs/pull/1593
- https://github.com/dapr/docs/pull/1608
- https://github.com/dapr/docs/pull/1607
- https://github.com/dapr/docs/pull/1466
- https://github.com/dapr/docs/pull/1546
- https://github.com/dapr/docs/pull/1579
- https://github.com/dapr/docs/pull/1578
- https://github.com/dapr/docs/pull/1577
- https://github.com/dapr/docs/pull/1505

**Comment by AaronCrawfis** [comment]
Per @orizohar's guidance I'm switching this to an approver request

**Comment by orizohar** [comment]
Since this was first opened, additional PRs:

https://github.com/dapr/docs/pull/1660
https://github.com/dapr/docs/pull/1686
https://github.com/dapr/docs/pull/1688
https://github.com/dapr/docs/pull/1689

**Comment by orizohar** [comment]
This was approved and implemented
