### ISSUE TITLE
REQUEST: New approver role for CodeMonkeyLeet in dapr/components-contrib

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/community#80]
### GitHub Username

@CodeMonkeyLeet sponsored by @artursouza 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- **PRs reviewed / authored**
  - Component fixes:
    - https://github.com/dapr/components-contrib/pull/1069
    - https://github.com/dapr/components-contrib/pull/1015
    - https://github.com/dapr/components-contrib/pull/1009
    - https://github.com/dapr/components-contrib/pull/1052
    - https://github.com/dapr/components-contrib/pull/1093
  - Fundamentals and testing:
    - https://github.com/dapr/components-contrib/pull/1047
    - https://github.com/dapr/components-contrib/pull/1064
    - https://github.com/dapr/components-contrib/pull/1050
    - https://github.com/dapr/components-contrib/pull/1044
    - https://github.com/dapr/components-contrib/pull/1040
    - https://github.com/dapr/components-contrib/pull/1002
    - https://github.com/dapr/components-contrib/pull/1001
    - https://github.com/dapr/components-contrib/pull/975
  - Developer/contributor experience:
    - https://github.com/dapr/components-contrib/pull/936
    - https://github.com/dapr/components-contrib/pull/917
  - Code reviews:
    - https://github.com/dapr/components-contrib/pull/1078
    - https://github.com/dapr/components-contrib/pull/1079
    - https://github.com/dapr/components-contrib/pull/1055
    - https://github.com/dapr/components-contrib/pull/1008
    - https://github.com/dapr/components-contrib/pull/944

- **Issues responded to**
  - Opened, in-flight:
    - https://github.com/dapr/components-contrib/issues/1053
    - https://github.com/dapr/components-contrib/issues/1051
    - https://github.com/dapr/components-contrib/issues/1007
    - https://github.com/dapr/components-contrib/issues/1046
  - Design discussions:
    - https://github.com/dapr/components-contrib/issues/964
    - https://github.com/dapr/components-contrib/issues/949
    - https://github.com/dapr/components-contrib/issues/951
    - https://github.com/dapr/components-contrib/issues/928
    - https://github.com/dapr/components-contrib/issues/1084
  - Troubleshooting:
    - https://github.com/dapr/components-contrib/issues/1085
    - https://github.com/dapr/components-contrib/issues/1094
    - https://github.com/dapr/components-contrib/issues/1092

**Comment by artursouza** [comment]
I support this request.

**Comment by yaron2** [comment]
I support, request approved.
