### ISSUE TITLE
REQUEST: New membership for @willtsai

### ISSUE THREAD

**Issue by willtsai** [dapr/community#82]
### GitHub Username

@willtsai

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  - https://github.com/dapr/docs/pull/1736

- Issues responded to
  - https://github.com/dapr/docs/issues/1633
  - https://github.com/dapr/setup-dapr/issues/9

**Comment by msfussell** [comment]
+ 1 to support this request

**Comment by yaron2** [comment]
Approved, @willtsai look for an invitation from GitHub.

**Comment by willtsai** [comment]
@yaron2 joined, thank you! 🎉
