### ISSUE TITLE
REQUEST: New approver status for @daixiang0 dapr/dapr

### ISSUE THREAD

**Issue by daixiang0** [dapr/community#84]
### GitHub Username

@daixiang0 

Nominations by existing maintainers:
@artursouza

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs authored
https://github.com/dapr/dapr/pull/3652
https://github.com/dapr/dapr/pull/3621
https://github.com/dapr/dapr/pull/3582
https://github.com/dapr/dapr/pull/3529
https://github.com/dapr/dapr/pull/3509
https://github.com/dapr/dapr/pull/3369
https://github.com/dapr/dapr/pull/3296
https://github.com/dapr/dapr/pull/3570
https://github.com/dapr/dapr/pull/3575
https://github.com/dapr/dapr/pull/3582
https://github.com/dapr/dapr/pull/3594
https://github.com/dapr/dapr/pull/3593

- PRs reviewed:
https://github.com/dapr/dapr/pull/3663
https://github.com/dapr/dapr/pull/3605
https://github.com/dapr/dapr/pull/3254
https://github.com/dapr/dapr/pull/3589
https://github.com/dapr/dapr/pull/3544

- Issues responded to
https://github.com/dapr/dapr/issues/3563
https://github.com/dapr/dapr/issues/3287
https://github.com/dapr/dapr/issues/3510
https://github.com/dapr/dapr/issues/3496
https://github.com/dapr/dapr/issues/3591
https://github.com/dapr/dapr/issues/3502
https://github.com/dapr/dapr/issues/2864
https://github.com/dapr/dapr/issues/3320
https://github.com/dapr/dapr/issues/3450
https://github.com/dapr/dapr/issues/3283
https://github.com/dapr/dapr/issues/2918
https://github.com/dapr/dapr/issues/3596
https://github.com/dapr/dapr/issues/3258

**Comment by yaron2** [comment]
I support this request. @artursouza please confirm your support.

**Comment by artursouza** [comment]
I support this request.

**Comment by yaron2** [comment]
Approved. @daixiang0 you have been added to the approvers group in `dapr/dapr`. Welcome.
