### ISSUE TITLE
REQUEST: New approver status for @daixiang0 dapr/components-contrib

### ISSUE THREAD

**Issue by daixiang0** [dapr/community#85]
### GitHub Username

@daixiang0 

Nominations by existing maintainers:
@artursouza

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs authored:
https://github.com/dapr/components-contrib/pull/1147
https://github.com/dapr/components-contrib/pull/1102
https://github.com/dapr/components-contrib/pull/1045
https://github.com/dapr/components-contrib/pull/995
https://github.com/dapr/components-contrib/pull/993
https://github.com/dapr/components-contrib/pull/985
https://github.com/dapr/components-contrib/pull/944
https://github.com/dapr/components-contrib/pull/906
https://github.com/dapr/components-contrib/pull/905

- PRs reviewed:
https://github.com/dapr/components-contrib/pull/1116
https://github.com/dapr/components-contrib/pull/1112
https://github.com/dapr/components-contrib/pull/1025

- Issues responded to
https://github.com/dapr/components-contrib/issues/1010
https://github.com/dapr/components-contrib/issues/994
https://github.com/dapr/components-contrib/issues/979
https://github.com/dapr/components-contrib/issues/978

**Comment by yaron2** [comment]
I support this request. @artursouza please confirm your support.

**Comment by artursouza** [comment]
I support this request.

**Comment by yaron2** [comment]
Approved. @daixiang0 you have been added to the approvers group in `dapr/components-contrib`. Welcome.
