### ISSUE TITLE
REQUEST: New membership for @l0ll098

### ISSUE THREAD

**Issue by l0ll098** [dapr/community#87]
### GitHub Username

@l0ll098

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
  - Dashboard
    - dapr/dashboard/pull/149
    - dapr/dashboard/pull/158
    - dapr/dashboard/pull/170
    - dapr/dashboard/pull/168
  - Docs
    - dapr/docs/pull/1696
    - dapr/docs/pull/1643
    - dapr/docs/pull/1816

**Comment by yaron2** [comment]
I approve the request.

**Comment by msfussell** [comment]
I approve this request

**Comment by msfussell** [comment]
@l0ll098 - Apologies this has taken a while to add you as a member. New member link has been sent.
