### ISSUE TITLE
REQUEST: New membership for @1046102779

### ISSUE THREAD

**Issue by 1046102779** [dapr/community#89]
### GitHub Username

@1046102779

discussed with @daixiang0

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/dapr/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Dapr community Discord server](https://aka.ms/dapr-discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Dapr repositories

### List of contributions to the Dapr project

- PRs reviewed / authored
https://github.com/dapr/dapr/pull/3579
https://github.com/dapr/dapr/pull/3544
https://github.com/dapr/dapr/pull/3519
https://github.com/dapr/dapr/pull/3375
https://github.com/dapr/dapr/pull/3073
https://github.com/dapr/dapr/pull/3072
https://github.com/dapr/dapr/pull/3061
https://github.com/dapr/dapr/pull/3053
https://github.com/dapr/dapr/pull/2930
https://github.com/dapr/dapr/pull/2863
https://github.com/dapr/dapr/pull/2849
https://github.com/dapr/dapr/pull/2845
https://github.com/dapr/dapr/pull/2841
https://github.com/dapr/dapr/pull/2835
https://github.com/dapr/dapr/pull/2834
https://github.com/dapr/dapr/pull/2832
https://github.com/dapr/dapr/pull/2781
https://github.com/dapr/dapr/pull/2779
https://github.com/dapr/dapr/pull/2777
https://github.com/dapr/dapr/pull/2762
https://github.com/dapr/dapr/pull/2673
https://github.com/dapr/dapr/pull/2663
https://github.com/dapr/dapr/pull/2656
https://github.com/dapr/dapr/pull/2653
https://github.com/dapr/dapr/pull/2553
https://github.com/dapr/components-contrib/pull/1112
https://github.com/dapr/components-contrib/pull/825
https://github.com/dapr/components-contrib/pull/761
https://github.com/dapr/go-sdk/pull/160

- Issues responded to
https://github.com/dapr/dapr/issues/3599

**Comment by daixiang0** [comment]
I support this request, @1046102779 has contributed a lot, he is from Tencent

**Comment by yaron2** [comment]
I approve.

**Comment by yaron2** [comment]
@1046102779 check for a GitHub invite, you have been added.

**Comment by 1046102779** [comment]
> @1046102779 check for a GitHub invite, you have been added.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/20457624/185389934-e73379b7-8f3c-4cf3-ad84-07a3405ab32b.png">

My phone was broken and I replaced it with a new phone, but I didn't save the Recovery Code before. And my account to be removed by `dapr` organization. Can you help me add it back?
