### ISSUE TITLE
Community meetings process

### ISSUE THREAD

**Issue by yaron2** [dapr/community#91]
Dapr hosts regular community meetings on Zoom.

Today, the agenda and topics are decided in advance in private by various community members. In order to facilitate inclusion of the broader Dapr community and allow for more diverse topics and speakers, I recommend we open here for discussion suggestions on how to open up this process.

My suggestion is to add a public process that is lightweight and transparent:

1. Use the `dapr/community` repository as the focal point.
2. 3 pinned issues titled "X community call agenda" will be created for the next 3 community calls, where X is the date of the upcoming call. For example: "Nov 3 community call agenda".
3. The upcoming call issue will be posted on Discord in the `#announcements` channel, and optionally tweeted from the daprdev account, one week prior.
4. The meeting agenda is finalized by a community role of `community call host`, of which there can be more than one. Community members (members of the Dapr GitHub org) can nominate themselves via an issue on the `dapr/community` repository. Members become approved community call hosts when 2 or more existing hosts approve their request, similar to how members and approvers get accepted today. To bootstrap community call hosts, I suggest long standing community members who have served as call hosts until today can get bootstrapped automatically if they choose to. Specifically, I'm calling out for @msfussell @greenie-msft @AaronCrawfis and @orizohar.

**Comment by msfussell** [comment]
I like this idea. This enables everyone in the community to have a chance to put ideas forward for topics and demos. It way be useful to open up the issues for the next 3 community calls, so that people can book a date/time in advance, not just the most immediate. We would then announce the upcoming one on the channel

**Comment by yaron2** [comment]
> I like this idea. This enables everyone in the community to have a chance to put ideas forward for topics and demos. It way be useful to open up the issues for the next 3 community calls, so that people can book a date/time in advance, not just the most immediate. We would then announce the upcoming one on the channel

Good suggestion, changed item #2.

**Comment by msfussell** [comment]
This has been adopted and needs to be recorded onto the community readme page site.
