### ISSUE TITLE
Add @berndverst as approver for components-contrib

### ISSUE THREAD

**Issue by berndverst** [dapr/community#97]
This is a request to add @berndverst as approver for components-contrib.

PRs:

https://github.com/dapr/components-contrib/pulls?q=is%3Apr+author%3Aberndverst+

dapr/components-contrib#1245
dapr/components-contrib#1238
dapr/components-contrib#1237
dapr/components-contrib#1233
dapr/components-contrib#1232
dapr/components-contrib#1223
dapr/components-contrib#1206
dapr/components-contrib#1202
dapr/components-contrib#1180
dapr/components-contrib#1176 
dapr/components-contrib#1159 
dapr/components-contrib#1152 
dapr/components-contrib#1079 
dapr/components-contrib#1078 
dapr/components-contrib#1059 
dapr/components-contrib#1011 
dapr/components-contrib#996 
dapr/components-contrib#991 
dapr/components-contrib#990 

Issues created:
dapr/components-contrib#1060
dapr/components-contrib#1175 

Please also see the conversations in Discord in #general and #components-contrib

**Comment by berndverst** [comment]
@yaron2 anything else needed here?

**Comment by yaron2** [comment]
+1.

**Comment by yaron2** [comment]
@berndverst you've been added as an approver to components-contrib.
